packages:
  - .
  - documentation

allowBuilds:
  '@swc/core': true
  bcrypt: true
  better-sqlite3: true
  core-js: true
  esbuild: true
  puppeteer: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - core-js
  - core-js-pure
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver
