/* eslint-disable */
export default {
  "key": "api",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "errors": {
          "unauthorized": "Unauthorized access - Please login to continue",
          "forbidden": "Access forbidden - You do not have permission",
          "notFound": "Resource not found",
          "methodNotAllowed": "Method not allowed",
          "requestTimeout": "Request timeout - Please try again",
          "conflict": "Conflict - Resource may have been modified",
          "tooManyRequests": "Too many requests - Please wait before trying again",
          "internalServerError": "Internal server error - Please try again later",
          "notImplemented": "Feature not implemented",
          "badGateway": "Bad gateway - Service unavailable",
          "serviceUnavailable": "Service temporarily unavailable",
          "gatewayTimeout": "Gateway timeout - Please try again",
          "networkError": "Network error - Please check your connection",
          "parseError": "Invalid response format",
          "validationError": "Validation failed - Please check your input",
          "unknownError": "An unknown error occurred"
        },
        "success": {
          "created": "Created successfully",
          "updated": "Updated successfully",
          "deleted": "Deleted successfully",
          "accepted": "Request accepted",
          "completed": "Completed successfully",
          "uploaded": "Uploaded successfully",
          "downloaded": "Downloaded successfully",
          "imported": "Imported successfully",
          "exported": "Exported successfully",
          "sent": "Sent successfully",
          "received": "Received successfully",
          "processed": "Processed successfully",
          "queued": "Queued successfully",
          "started": "Started successfully",
          "stopped": "Stopped successfully",
          "paused": "Paused successfully",
          "resumed": "Resumed successfully",
          "refreshed": "Refreshed successfully",
          "reloaded": "Reloaded successfully",
          "reset": "Reset successfully",
          "cleared": "Cleared successfully",
          "saved": "Saved successfully",
          "copied": "Copied successfully",
          "moved": "Moved successfully"
        },
        "validation": {
          "required": "This field is required",
          "invalid": "Invalid value",
          "tooShort": "Must be at least {min} characters",
          "tooLong": "Must be at most {max} characters",
          "tooSmall": "Must be at least {min}",
          "tooLarge": "Must be at most {max}",
          "invalidFormat": "Invalid format",
          "invalidEmail": "Invalid email address",
          "invalidUrl": "Invalid URL",
          "invalidNumber": "Invalid number",
          "invalidDate": "Invalid date",
          "invalidTime": "Invalid time",
          "invalidColor": "Invalid color",
          "invalidPhone": "Invalid phone number",
          "invalidPostalCode": "Invalid postal code",
          "invalidCountry": "Invalid country",
          "invalidLanguage": "Invalid language",
          "invalidCurrency": "Invalid currency",
          "invalidTimezone": "Invalid timezone",
          "invalidCharset": "Invalid charset",
          "invalidEncoding": "Invalid encoding",
          "invalidMimeType": "Invalid mime type",
          "invalidFileSize": "File size too large",
          "invalidFileType": "Invalid file type",
          "duplicate": "Duplicate value",
          "conflict": "Conflict with existing data",
          "notFound": "Not found",
          "notAllowed": "Not allowed",
          "notSupported": "Not supported",
          "notAvailable": "Not available",
          "notAccessible": "Not accessible",
          "notConnected": "Not connected",
          "notReachable": "Not reachable",
          "notResponding": "Not responding",
          "notReady": "Not ready",
          "notEnabled": "Not enabled",
          "notDisabled": "Not disabled",
          "notActive": "Not active",
          "notInactive": "Not inactive",
          "notOnline": "Not online",
          "notOffline": "Not offline",
          "notOpen": "Not open",
          "notClosed": "Not closed",
          "notLocked": "Not locked",
          "notUnlocked": "Not unlocked",
          "notEmpty": "Cannot be empty",
          "notBlank": "Cannot be blank",
          "notNull": "Cannot be null",
          "notUndefined": "Cannot be undefined",
          "notBoolean": "Must be a boolean",
          "notString": "Must be a string",
          "notNumber": "Must be a number",
          "notObject": "Must be an object",
          "notArray": "Must be an array",
          "notFunction": "Must be a function",
          "notDate": "Must be a date",
          "notRegExp": "Must be a regular expression",
          "notError": "Must be an error object",
          "notPromise": "Must be a promise",
          "notIterable": "Must be iterable",
          "notAsync": "Must be async",
          "notGenerator": "Must be a generator",
          "notSymbol": "Must be a symbol",
          "notBigInt": "Must be a BigInt"
        },
        "server": {
          "added": "Server added successfully",
          "updated": "Server updated successfully",
          "deleted": "Server deleted successfully",
          "connected": "Server connected successfully",
          "disconnected": "Server disconnected",
          "online": "Server is online",
          "offline": "Server is offline",
          "testing": "Testing server connection...",
          "testSuccess": "Connection test successful",
          "testFailed": "Connection test failed",
          "backupStarted": "Backup started successfully",
          "backupCompleted": "Backup completed successfully",
          "backupFailed": "Backup failed",
          "backupCancelled": "Backup cancelled",
          "backupRetried": "Backup retry initiated",
          "configurationUpdated": "Server configuration updated",
          "statusUpdated": "Server status updated",
          "settingsUpdated": "Server settings updated",
          "notificationsUpdated": "Server notifications updated"
        },
        "backup": {
          "started": "Backup started",
          "completed": "Backup completed",
          "failed": "Backup failed",
          "cancelled": "Backup cancelled",
          "paused": "Backup paused",
          "resumed": "Backup resumed",
          "retried": "Backup retry started",
          "deleted": "Backup deleted",
          "downloaded": "Backup downloaded",
          "uploaded": "Backup uploaded",
          "verified": "Backup verified",
          "restored": "Backup restored",
          "scheduled": "Backup scheduled",
          "unscheduled": "Backup unscheduled",
          "enabled": "Backup enabled",
          "disabled": "Backup disabled",
          "configurationUpdated": "Backup configuration updated",
          "settingsUpdated": "Backup settings updated",
          "retentionUpdated": "Backup retention policy updated",
          "cleanupStarted": "Backup cleanup started",
          "cleanupCompleted": "Backup cleanup completed",
          "cleanupFailed": "Backup cleanup failed"
        },
        "user": {
          "created": "User created successfully",
          "updated": "User updated successfully",
          "deleted": "User deleted successfully",
          "logged": "User logged in",
          "loggedOut": "User logged out",
          "passwordChanged": "Password changed successfully",
          "passwordReset": "Password reset successfully",
          "emailVerified": "Email verified successfully",
          "phoneVerified": "Phone number verified successfully",
          "twoFactorEnabled": "Two-factor authentication enabled",
          "twoFactorDisabled": "Two-factor authentication disabled",
          "sessionCreated": "Session created successfully",
          "sessionExpired": "Session expired",
          "sessionTerminated": "Session terminated successfully",
          "profileUpdated": "Profile updated successfully",
          "preferencesUpdated": "Preferences updated successfully",
          "notificationsUpdated": "Notification preferences updated",
          "apiKeyGenerated": "API key generated successfully",
          "apiKeyRegenerated": "API key regenerated successfully",
          "apiKeyRevoked": "API key revoked successfully"
        },
        "notification": {
          "sent": "Notification sent successfully",
          "delivered": "Notification delivered successfully",
          "failed": "Notification failed to send",
          "queued": "Notification queued for delivery",
          "processed": "Notification processed successfully",
          "read": "Notification marked as read",
          "unread": "Notification marked as unread",
          "archived": "Notification archived successfully",
          "deleted": "Notification deleted successfully",
          "settingsUpdated": "Notification settings updated",
          "templateUpdated": "Notification template updated",
          "channelUpdated": "Notification channel updated",
          "subscriptionCreated": "Notification subscription created",
          "subscriptionUpdated": "Notification subscription updated",
          "subscriptionDeleted": "Notification subscription deleted",
          "preferencesUpdated": "Notification preferences updated"
        }
      },
      "de": {
        "errors": {
          "unauthorized": "Nicht autorisierter Zugriff - Bitte melden Sie sich an",
          "forbidden": "Zugriff verboten - Sie haben keine Berechtigung",
          "notFound": "Ressource nicht gefunden",
          "methodNotAllowed": "Methode nicht erlaubt",
          "requestTimeout": "Anfrage-Timeout - Bitte versuchen Sie es erneut",
          "conflict": "Konflikt - Ressource wurde möglicherweise geändert",
          "tooManyRequests": "Zu viele Anfragen - Bitte warten Sie vor einem erneuten Versuch",
          "internalServerError": "Interner Serverfehler - Bitte versuchen Sie es später erneut",
          "notImplemented": "Funktion nicht implementiert",
          "badGateway": "Falsches Gateway - Dienst nicht verfügbar",
          "serviceUnavailable": "Dienst vorübergehend nicht verfügbar",
          "gatewayTimeout": "Gateway-Timeout - Bitte versuchen Sie es erneut",
          "networkError": "Netzwerkfehler - Bitte überprüfen Sie Ihre Verbindung",
          "parseError": "Ungültiges Antwortformat",
          "validationError": "Validierung fehlgeschlagen - Bitte überprüfen Sie Ihre Eingabe",
          "unknownError": "Ein unbekannter Fehler ist aufgetreten"
        },
        "success": {
          "created": "Erfolgreich erstellt",
          "updated": "Erfolgreich aktualisiert",
          "deleted": "Erfolgreich gelöscht",
          "accepted": "Anfrage angenommen",
          "completed": "Erfolgreich abgeschlossen",
          "uploaded": "Erfolgreich hochgeladen",
          "downloaded": "Erfolgreich heruntergeladen",
          "imported": "Erfolgreich importiert",
          "exported": "Erfolgreich exportiert",
          "sent": "Erfolgreich gesendet",
          "received": "Erfolgreich empfangen",
          "processed": "Erfolgreich verarbeitet",
          "queued": "Erfolgreich in Warteschlange gestellt",
          "started": "Erfolgreich gestartet",
          "stopped": "Erfolgreich gestoppt",
          "paused": "Erfolgreich pausiert",
          "resumed": "Erfolgreich fortgesetzt",
          "refreshed": "Erfolgreich aktualisiert",
          "reloaded": "Erfolgreich neu geladen",
          "reset": "Erfolgreich zurückgesetzt",
          "cleared": "Erfolgreich gelöscht",
          "saved": "Erfolgreich gespeichert",
          "copied": "Erfolgreich kopiert",
          "moved": "Erfolgreich verschoben"
        },
        "validation": {
          "required": "Dieses Feld ist erforderlich",
          "invalid": "Ungültiger Wert",
          "tooShort": "Mindestens {min} Zeichen",
          "tooLong": "Maximal {max} Zeichen",
          "tooSmall": "Mindestens {min}",
          "tooLarge": "Maximal {max}",
          "invalidFormat": "Ungültiges Format",
          "invalidEmail": "Ungültige E-Mail-Adresse",
          "invalidUrl": "Ungültige URL",
          "invalidNumber": "Ungültige Zahl",
          "invalidDate": "Ungültiges Datum",
          "invalidTime": "Ungültige Zeit",
          "invalidColor": "Ungültige Farbe",
          "invalidPhone": "Ungültige Telefonnummer",
          "invalidPostalCode": "Ungültige Postleitzahl",
          "invalidCountry": "Ungültiges Land",
          "invalidLanguage": "Ungültige Sprache",
          "invalidCurrency": "Ungültige Währung",
          "invalidTimezone": "Ungültige Zeitzone",
          "invalidCharset": "Ungültiger Zeichensatz",
          "invalidEncoding": "Ungültige Kodierung",
          "invalidMimeType": "Ungültiger MIME-Typ",
          "invalidFileSize": "Dateigröße zu groß",
          "invalidFileType": "Ungültiger Dateityp",
          "duplicate": "Doppelter Wert",
          "conflict": "Konflikt mit vorhandenen Daten",
          "notFound": "Nicht gefunden",
          "notAllowed": "Nicht erlaubt",
          "notSupported": "Nicht unterstützt",
          "notAvailable": "Nicht verfügbar",
          "notAccessible": "Nicht zugänglich",
          "notConnected": "Nicht verbunden",
          "notReachable": "Nicht erreichbar",
          "notResponding": "Antwortet nicht",
          "notReady": "Nicht bereit",
          "notEnabled": "Nicht aktiviert",
          "notDisabled": "Nicht deaktiviert",
          "notActive": "Nicht aktiv",
          "notInactive": "Nicht inaktiv",
          "notOnline": "Nicht online",
          "notOffline": "Nicht offline",
          "notOpen": "Nicht offen",
          "notClosed": "Nicht geschlossen",
          "notLocked": "Nicht gesperrt",
          "notUnlocked": "Nicht entsperrt",
          "notEmpty": "Darf nicht leer sein",
          "notBlank": "Darf nicht leer sein",
          "notNull": "Darf nicht null sein",
          "notUndefined": "Darf nicht undefiniert sein",
          "notBoolean": "Muss ein Boolean sein",
          "notString": "Muss ein String sein",
          "notNumber": "Muss eine Zahl sein",
          "notObject": "Muss ein Objekt sein",
          "notArray": "Muss ein Array sein",
          "notFunction": "Muss eine Funktion sein",
          "notDate": "Muss ein Datum sein",
          "notRegExp": "Muss ein regulärer Ausdruck sein",
          "notError": "Muss ein Fehlerobjekt sein",
          "notPromise": "Muss ein Promise sein",
          "notIterable": "Muss iterierbar sein",
          "notAsync": "Muss async sein",
          "notGenerator": "Muss ein Generator sein",
          "notSymbol": "Muss ein Symbol sein",
          "notBigInt": "Muss ein BigInt sein"
        },
        "server": {
          "added": "Server erfolgreich hinzugefügt",
          "updated": "Server erfolgreich aktualisiert",
          "deleted": "Server erfolgreich gelöscht",
          "connected": "Server erfolgreich verbunden",
          "disconnected": "Server getrennt",
          "online": "Server ist online",
          "offline": "Server ist offline",
          "testing": "Serververbindung wird getestet...",
          "testSuccess": "Verbindungstest erfolgreich",
          "testFailed": "Verbindungstest fehlgeschlagen",
          "backupStarted": "Sicherung erfolgreich gestartet",
          "backupCompleted": "Sicherung erfolgreich abgeschlossen",
          "backupFailed": "Sicherung fehlgeschlagen",
          "backupCancelled": "Sicherung abgebrochen",
          "backupRetried": "Sicherungswiederholung eingeleitet",
          "configurationUpdated": "Serverkonfiguration aktualisiert",
          "statusUpdated": "Serverstatus aktualisiert",
          "settingsUpdated": "Servereinstellungen aktualisiert",
          "notificationsUpdated": "Serverbenachrichtigungen aktualisiert"
        },
        "backup": {
          "started": "Sicherung gestartet",
          "completed": "Sicherung abgeschlossen",
          "failed": "Sicherung fehlgeschlagen",
          "cancelled": "Sicherung abgebrochen",
          "paused": "Sicherung pausiert",
          "resumed": "Sicherung fortgesetzt",
          "retried": "Sicherungswiederholung gestartet",
          "deleted": "Sicherung gelöscht",
          "downloaded": "Sicherung heruntergeladen",
          "uploaded": "Sicherung hochgeladen",
          "verified": "Sicherung überprüft",
          "restored": "Sicherung wiederhergestellt",
          "scheduled": "Sicherung geplant",
          "unscheduled": "Sicherung nicht geplant",
          "enabled": "Sicherung aktiviert",
          "disabled": "Sicherung deaktiviert",
          "configurationUpdated": "Sicherungskonfiguration aktualisiert",
          "settingsUpdated": "Sicherungseinstellungen aktualisiert",
          "retentionUpdated": "Sicherungsaufbewahrungsrichtlinie aktualisiert",
          "cleanupStarted": "Sicherungsbereinigung gestartet",
          "cleanupCompleted": "Sicherungsbereinigung abgeschlossen",
          "cleanupFailed": "Sicherungsbereinigung fehlgeschlagen"
        },
        "user": {
          "created": "Benutzer erfolgreich erstellt",
          "updated": "Benutzer erfolgreich aktualisiert",
          "deleted": "Benutzer erfolgreich gelöscht",
          "logged": "Benutzer angemeldet",
          "loggedOut": "Benutzer abgemeldet",
          "passwordChanged": "Passwort erfolgreich geändert",
          "passwordReset": "Passwort erfolgreich zurückgesetzt",
          "emailVerified": "E-Mail erfolgreich verifiziert",
          "phoneVerified": "Telefonnummer erfolgreich verifiziert",
          "twoFactorEnabled": "Zwei-Faktor-Authentifizierung aktiviert",
          "twoFactorDisabled": "Zwei-Faktor-Authentifizierung deaktiviert",
          "sessionCreated": "Sitzung erfolgreich erstellt",
          "sessionExpired": "Sitzung abgelaufen",
          "sessionTerminated": "Sitzung erfolgreich beendet",
          "profileUpdated": "Profil erfolgreich aktualisiert",
          "preferencesUpdated": "Einstellungen erfolgreich aktualisiert",
          "notificationsUpdated": "Benachrichtigungseinstellungen aktualisiert",
          "apiKeyGenerated": "API-Schlüssel erfolgreich generiert",
          "apiKeyRegenerated": "API-Schlüssel erfolgreich neu generiert",
          "apiKeyRevoked": "API-Schlüssel erfolgreich widerrufen"
        },
        "notification": {
          "sent": "Benachrichtigung erfolgreich gesendet",
          "delivered": "Benachrichtigung erfolgreich zugestellt",
          "failed": "Benachrichtigung konnte nicht gesendet werden",
          "queued": "Benachrichtigung für Zustellung in Warteschlange gestellt",
          "processed": "Benachrichtigung erfolgreich verarbeitet",
          "read": "Benachrichtigung als gelesen markiert",
          "unread": "Benachrichtigung als ungelesen markiert",
          "archived": "Benachrichtigung erfolgreich archiviert",
          "deleted": "Benachrichtigung erfolgreich gelöscht",
          "settingsUpdated": "Benachrichtigungseinstellungen aktualisiert",
          "templateUpdated": "Benachrichtigungsvorlage aktualisiert",
          "channelUpdated": "Benachrichtigungskanal aktualisiert",
          "subscriptionCreated": "Benachrichtigungsabonnement erstellt",
          "subscriptionUpdated": "Benachrichtigungsabonnement aktualisiert",
          "subscriptionDeleted": "Benachrichtigungsabonnement gelöscht",
          "preferencesUpdated": "Benachrichtigungseinstellungen aktualisiert"
        }
      },
      "fr": {
        "errors": {
          "unauthorized": "Accès non autorisé - Veuillez vous connecter",
          "forbidden": "Accès interdit - Vous n'avez pas la permission",
          "notFound": "Ressource introuvable",
          "methodNotAllowed": "Méthode non autorisée",
          "requestTimeout": "Délai d'attente dépassé - Veuillez réessayer",
          "conflict": "Conflit - La ressource a peut-être été modifiée",
          "tooManyRequests": "Trop de demandes - Veuillez attendre avant de réessayer",
          "internalServerError": "Erreur interne du serveur - Veuillez réessayer plus tard",
          "notImplemented": "Fonctionnalité non implémentée",
          "badGateway": "Mauvaise passerelle - Service indisponible",
          "serviceUnavailable": "Service temporairement indisponible",
          "gatewayTimeout": "Délai d'attente de la passerelle dépassé - Veuillez réessayer",
          "networkError": "Erreur réseau - Veuillez vérifier votre connexion",
          "parseError": "Format de réponse invalide",
          "validationError": "Validation échouée - Veuillez vérifier votre saisie",
          "unknownError": "Une erreur inconnue est survenue"
        },
        "success": {
          "created": "Créé avec succès",
          "updated": "Mis à jour avec succès",
          "deleted": "Supprimé avec succès",
          "accepted": "Demande acceptée",
          "completed": "Terminé avec succès",
          "uploaded": "Téléchargé avec succès",
          "downloaded": "Téléchargé avec succès",
          "imported": "Importé avec succès",
          "exported": "Exporté avec succès",
          "sent": "Envoyé avec succès",
          "received": "Reçu avec succès",
          "processed": "Traité avec succès",
          "queued": "Mis en file d'attente avec succès",
          "started": "Démarré avec succès",
          "stopped": "Arrêté avec succès",
          "paused": "Mis en pause avec succès",
          "resumed": "Repris avec succès",
          "refreshed": "Actualisé avec succès",
          "reloaded": "Rechargé avec succès",
          "reset": "Réinitialisé avec succès",
          "cleared": "Effacé avec succès",
          "saved": "Enregistré avec succès",
          "copied": "Copié avec succès",
          "moved": "Déplacé avec succès"
        },
        "validation": {
          "required": "Ce champ est obligatoire",
          "invalid": "Valeur invalide",
          "tooShort": "Doit contenir au moins {min} caractères",
          "tooLong": "Doit contenir au plus {max} caractères",
          "tooSmall": "Doit être au moins {min}",
          "tooLarge": "Doit être au plus {max}",
          "invalidFormat": "Format invalide",
          "invalidEmail": "Adresse e-mail invalide",
          "invalidUrl": "URL invalide",
          "invalidNumber": "Nombre invalide",
          "invalidDate": "Date invalide",
          "invalidTime": "Heure invalide",
          "invalidColor": "Couleur invalide",
          "invalidPhone": "Numéro de téléphone invalide",
          "invalidPostalCode": "Code postal invalide",
          "invalidCountry": "Pays invalide",
          "invalidLanguage": "Langue invalide",
          "invalidCurrency": "Devise invalide",
          "invalidTimezone": "Fuseau horaire invalide",
          "invalidCharset": "Jeu de caractères invalide",
          "invalidEncoding": "Encodage invalide",
          "invalidMimeType": "Type MIME invalide",
          "invalidFileSize": "Taille de fichier trop grande",
          "invalidFileType": "Type de fichier invalide",
          "duplicate": "Valeur en double",
          "conflict": "Conflit avec les données existantes",
          "notFound": "Introuvable",
          "notAllowed": "Non autorisé",
          "notSupported": "Non pris en charge",
          "notAvailable": "Indisponible",
          "notAccessible": "Inaccessible",
          "notConnected": "Non connecté",
          "notReachable": "Inaccessible",
          "notResponding": "Ne répond pas",
          "notReady": "Pas prêt",
          "notEnabled": "Non activé",
          "notDisabled": "Non désactivé",
          "notActive": "Inactif",
          "notInactive": "Non inactif",
          "notOnline": "Hors ligne",
          "notOffline": "En ligne",
          "notOpen": "Fermé",
          "notClosed": "Ouvert",
          "notLocked": "Déverrouillé",
          "notUnlocked": "Non déverrouillé",
          "notEmpty": "Ne peut pas être vide",
          "notBlank": "Ne peut pas être vide",
          "notNull": "Ne peut pas être nul",
          "notUndefined": "Ne peut pas être indéfini",
          "notBoolean": "Doit être un booléen",
          "notString": "Doit être une chaîne",
          "notNumber": "Doit être un nombre",
          "notObject": "Doit être un objet",
          "notArray": "Doit être un tableau",
          "notFunction": "Doit être une fonction",
          "notDate": "Doit être une date",
          "notRegExp": "Doit être une expression régulière",
          "notError": "Doit être un objet d'erreur",
          "notPromise": "Doit être une promesse",
          "notIterable": "Doit être itérable",
          "notAsync": "Doit être async",
          "notGenerator": "Doit être un générateur",
          "notSymbol": "Doit être un symbole",
          "notBigInt": "Doit être un BigInt"
        },
        "server": {
          "added": "Serveur ajouté avec succès",
          "updated": "Serveur mis à jour avec succès",
          "deleted": "Serveur supprimé avec succès",
          "connected": "Serveur connecté avec succès",
          "disconnected": "Serveur déconnecté",
          "online": "Le serveur est en ligne",
          "offline": "Le serveur est hors ligne",
          "testing": "Test de la connexion du serveur...",
          "testSuccess": "Test de connexion réussi",
          "testFailed": "Test de connexion échoué",
          "backupStarted": "Sauvegarde démarrée avec succès",
          "backupCompleted": "Sauvegarde terminée avec succès",
          "backupFailed": "Sauvegarde échouée",
          "backupCancelled": "Sauvegarde annulée",
          "backupRetried": "Nouvelle tentative de sauvegarde",
          "configurationUpdated": "Configuration du serveur mise à jour",
          "statusUpdated": "Statut du serveur mis à jour",
          "settingsUpdated": "Paramètres du serveur mis à jour",
          "notificationsUpdated": "Notifications du serveur mises à jour"
        },
        "backup": {
          "started": "Sauvegarde démarrée",
          "completed": "Sauvegarde terminée",
          "failed": "Sauvegarde échouée",
          "cancelled": "Sauvegarde annulée",
          "paused": "Sauvegarde en pause",
          "resumed": "Sauvegarde reprise",
          "retried": "Nouvelle tentative de sauvegarde",
          "deleted": "Sauvegarde supprimée",
          "downloaded": "Sauvegarde téléchargée",
          "uploaded": "Sauvegarde téléchargée",
          "verified": "Sauvegarde vérifiée",
          "restored": "Sauvegarde restaurée",
          "scheduled": "Sauvegarde planifiée",
          "unscheduled": "Sauvegarde non planifiée",
          "enabled": "Sauvegarde activée",
          "disabled": "Sauvegarde désactivée",
          "configurationUpdated": "Configuration de sauvegarde mise à jour",
          "settingsUpdated": "Paramètres de sauvegarde mis à jour",
          "retentionUpdated": "Politique de rétention des sauvegardes mise à jour",
          "cleanupStarted": "Nettoyage des sauvegardes démarré",
          "cleanupCompleted": "Nettoyage des sauvegardes terminé",
          "cleanupFailed": "Nettoyage des sauvegardes échoué"
        },
        "user": {
          "created": "Utilisateur créé avec succès",
          "updated": "Utilisateur mis à jour avec succès",
          "deleted": "Utilisateur supprimé avec succès",
          "logged": "Utilisateur connecté",
          "loggedOut": "Utilisateur déconnecté",
          "passwordChanged": "Mot de passe changé avec succès",
          "passwordReset": "Mot de passe réinitialisé avec succès",
          "emailVerified": "E-mail vérifié avec succès",
          "phoneVerified": "Numéro de téléphone vérifié avec succès",
          "twoFactorEnabled": "Authentification à deux facteurs activée",
          "twoFactorDisabled": "Authentification à deux facteurs désactivée",
          "sessionCreated": "Session créée avec succès",
          "sessionExpired": "Session expirée",
          "sessionTerminated": "Session terminée avec succès",
          "profileUpdated": "Profil mis à jour avec succès",
          "preferencesUpdated": "Préférences mises à jour avec succès",
          "notificationsUpdated": "Préférences de notification mises à jour",
          "apiKeyGenerated": "Clé API générée avec succès",
          "apiKeyRegenerated": "Clé API régénérée avec succès",
          "apiKeyRevoked": "Clé API révoquée avec succès"
        },
        "notification": {
          "sent": "Notification envoyée avec succès",
          "delivered": "Notification livrée avec succès",
          "failed": "Échec de l'envoi de la notification",
          "queued": "Notification mise en file d'attente pour livraison",
          "processed": "Notification traitée avec succès",
          "read": "Notification marquée comme lue",
          "unread": "Notification marquée comme non lue",
          "archived": "Notification archivée avec succès",
          "deleted": "Notification supprimée avec succès",
          "settingsUpdated": "Paramètres de notification mis à jour",
          "templateUpdated": "Modèle de notification mis à jour",
          "channelUpdated": "Canal de notification mis à jour",
          "subscriptionCreated": "Abonnement de notification créé",
          "subscriptionUpdated": "Abonnement de notification mis à jour",
          "subscriptionDeleted": "Abonnement de notification supprimé",
          "preferencesUpdated": "Préférences de notification mises à jour"
        }
      },
      "es": {
        "errors": {
          "unauthorized": "Acceso no autorizado - Por favor inicie sesión",
          "forbidden": "Acceso prohibido - No tiene permiso",
          "notFound": "Recurso no encontrado",
          "methodNotAllowed": "Método no permitido",
          "requestTimeout": "Tiempo de espera agotado - Por favor inténtelo de nuevo",
          "conflict": "Conflicto - Es posible que el recurso haya sido modificado",
          "tooManyRequests": "Demasiadas solicitudes - Por favor espere antes de intentarlo de nuevo",
          "internalServerError": "Error interno del servidor - Por favor inténtelo más tarde",
          "notImplemented": "Función no implementada",
          "badGateway": "Puerta de enlace incorrecta - Servicio no disponible",
          "serviceUnavailable": "Servicio temporalmente no disponible",
          "gatewayTimeout": "Tiempo de espera de la puerta de enlace agotado - Por favor inténtelo de nuevo",
          "networkError": "Error de red - Por favor verifique su conexión",
          "parseError": "Formato de respuesta inválido",
          "validationError": "Validación fallida - Por favor verifique su entrada",
          "unknownError": "Ocurrió un error desconocido"
        },
        "success": {
          "created": "Creado exitosamente",
          "updated": "Actualizado exitosamente",
          "deleted": "Eliminado exitosamente",
          "accepted": "Solicitud aceptada",
          "completed": "Completado exitosamente",
          "uploaded": "Subido exitosamente",
          "downloaded": "Descargado exitosamente",
          "imported": "Importado exitosamente",
          "exported": "Exportado exitosamente",
          "sent": "Enviado exitosamente",
          "received": "Recibido exitosamente",
          "processed": "Procesado exitosamente",
          "queued": "Puesto en cola exitosamente",
          "started": "Iniciado exitosamente",
          "stopped": "Detenido exitosamente",
          "paused": "Pausado exitosamente",
          "resumed": "Reanudado exitosamente",
          "refreshed": "Actualizado exitosamente",
          "reloaded": "Recargado exitosamente",
          "reset": "Restablecido exitosamente",
          "cleared": "Limpiado exitosamente",
          "saved": "Guardado exitosamente",
          "copied": "Copiado exitosamente",
          "moved": "Movido exitosamente"
        },
        "validation": {
          "required": "Este campo es obligatorio",
          "invalid": "Valor inválido",
          "tooShort": "Debe tener al menos {min} caracteres",
          "tooLong": "Debe tener como máximo {max} caracteres",
          "tooSmall": "Debe ser al menos {min}",
          "tooLarge": "Debe ser como máximo {max}",
          "invalidFormat": "Formato inválido",
          "invalidEmail": "Dirección de correo electrónico inválida",
          "invalidUrl": "URL inválida",
          "invalidNumber": "Número inválido",
          "invalidDate": "Fecha inválida",
          "invalidTime": "Hora inválida",
          "invalidColor": "Color inválido",
          "invalidPhone": "Número de teléfono inválido",
          "invalidPostalCode": "Código postal inválido",
          "invalidCountry": "País inválido",
          "invalidLanguage": "Idioma inválido",
          "invalidCurrency": "Moneda inválida",
          "invalidTimezone": "Zona horaria inválida",
          "invalidCharset": "Juego de caracteres inválido",
          "invalidEncoding": "Codificación inválida",
          "invalidMimeType": "Tipo MIME inválido",
          "invalidFileSize": "Tamaño de archivo demasiado grande",
          "invalidFileType": "Tipo de archivo inválido",
          "duplicate": "Valor duplicado",
          "conflict": "Conflicto con datos existentes",
          "notFound": "No encontrado",
          "notAllowed": "No permitido",
          "notSupported": "No compatible",
          "notAvailable": "No disponible",
          "notAccessible": "No accesible",
          "notConnected": "No conectado",
          "notReachable": "Inalcanzable",
          "notResponding": "No responde",
          "notReady": "No está listo",
          "notEnabled": "No habilitado",
          "notDisabled": "No deshabilitado",
          "notActive": "Inactivo",
          "notInactive": "No inactivo",
          "notOnline": "No en línea",
          "notOffline": "En línea",
          "notOpen": "Cerrado",
          "notClosed": "Abierto",
          "notLocked": "No bloqueado",
          "notUnlocked": "No desbloqueado",
          "notEmpty": "No puede estar vacío",
          "notBlank": "No puede estar en blanco",
          "notNull": "No puede ser nulo",
          "notUndefined": "No puede ser indefinido",
          "notBoolean": "Debe ser un booleano",
          "notString": "Debe ser una cadena",
          "notNumber": "Debe ser un número",
          "notObject": "Debe ser un objeto",
          "notArray": "Debe ser un array",
          "notFunction": "Debe ser una función",
          "notDate": "Debe ser una fecha",
          "notRegExp": "Debe ser una expresión regular",
          "notError": "Debe ser un objeto de error",
          "notPromise": "Debe ser una promesa",
          "notIterable": "Debe ser iterable",
          "notAsync": "Debe ser async",
          "notGenerator": "Debe ser un generador",
          "notSymbol": "Debe ser un símbolo",
          "notBigInt": "Debe ser un BigInt"
        },
        "server": {
          "added": "Servidor agregado exitosamente",
          "updated": "Servidor actualizado exitosamente",
          "deleted": "Servidor eliminado exitosamente",
          "connected": "Servidor conectado exitosamente",
          "disconnected": "Servidor desconectado",
          "online": "El servidor está en línea",
          "offline": "El servidor está fuera de línea",
          "testing": "Probando conexión del servidor...",
          "testSuccess": "Prueba de conexión exitosa",
          "testFailed": "Prueba de conexión fallida",
          "backupStarted": "Respaldo iniciado exitosamente",
          "backupCompleted": "Respaldo completado exitosamente",
          "backupFailed": "Respaldo fallido",
          "backupCancelled": "Respaldo cancelado",
          "backupRetried": "Reintento de respaldo iniciado",
          "configurationUpdated": "Configuración del servidor actualizada",
          "statusUpdated": "Estado del servidor actualizado",
          "settingsUpdated": "Configuración del servidor actualizada",
          "notificationsUpdated": "Notificaciones del servidor actualizadas"
        },
        "backup": {
          "started": "Respaldo iniciado",
          "completed": "Respaldo completado",
          "failed": "Respaldo fallido",
          "cancelled": "Respaldo cancelado",
          "paused": "Respaldo pausado",
          "resumed": "Respaldo reanudado",
          "retried": "Reintento de respaldo iniciado",
          "deleted": "Respaldo eliminado",
          "downloaded": "Respaldo descargado",
          "uploaded": "Respaldo subido",
          "verified": "Respaldo verificado",
          "restored": "Respaldo restaurado",
          "scheduled": "Respaldo programado",
          "unscheduled": "Respaldo no programado",
          "enabled": "Respaldo habilitado",
          "disabled": "Respaldo deshabilitado",
          "configurationUpdated": "Configuración de respaldo actualizada",
          "settingsUpdated": "Configuración de respaldo actualizada",
          "retentionUpdated": "Política de retención de respaldos actualizada",
          "cleanupStarted": "Limpieza de respaldos iniciada",
          "cleanupCompleted": "Limpieza de respaldos completada",
          "cleanupFailed": "Limpieza de respaldos fallida"
        },
        "user": {
          "created": "Usuario creado exitosamente",
          "updated": "Usuario actualizado exitosamente",
          "deleted": "Usuario eliminado exitosamente",
          "logged": "Usuario inició sesión",
          "loggedOut": "Usuario cerró sesión",
          "passwordChanged": "Contraseña cambiada exitosamente",
          "passwordReset": "Contraseña restablecida exitosamente",
          "emailVerified": "Correo electrónico verificado exitosamente",
          "phoneVerified": "Número de teléfono verificado exitosamente",
          "twoFactorEnabled": "Autenticación de dos factores habilitada",
          "twoFactorDisabled": "Autenticación de dos factores deshabilitada",
          "sessionCreated": "Sesión creada exitosamente",
          "sessionExpired": "Sesión expirada",
          "sessionTerminated": "Sesión terminada exitosamente",
          "profileUpdated": "Perfil actualizado exitosamente",
          "preferencesUpdated": "Preferencias actualizadas exitosamente",
          "notificationsUpdated": "Preferencias de notificación actualizadas",
          "apiKeyGenerated": "Clave API generada exitosamente",
          "apiKeyRegenerated": "Clave API regenerada exitosamente",
          "apiKeyRevoked": "Clave API revocada exitosamente"
        },
        "notification": {
          "sent": "Notificación enviada exitosamente",
          "delivered": "Notificación entregada exitosamente",
          "failed": "Falló enviar notificación",
          "queued": "Notificación puesta en cola para entrega",
          "processed": "Notificación procesada exitosamente",
          "read": "Notificación marcada como leída",
          "unread": "Notificación marcada como no leída",
          "archived": "Notificación archivada exitosamente",
          "deleted": "Notificación eliminada exitosamente",
          "settingsUpdated": "Configuración de notificación actualizada",
          "templateUpdated": "Plantilla de notificación actualizada",
          "channelUpdated": "Canal de notificación actualizado",
          "subscriptionCreated": "Suscripción de notificación creada",
          "subscriptionUpdated": "Suscripción de notificación actualizada",
          "subscriptionDeleted": "Suscripción de notificación eliminada",
          "preferencesUpdated": "Preferencias de notificación actualizadas"
        }
      },
      "pt-BR": {
        "errors": {
          "unauthorized": "Acesso não autorizado - Por favor, faça login",
          "forbidden": "Acesso proibido - Você não tem permissão",
          "notFound": "Recurso não encontrado",
          "methodNotAllowed": "Método não permitido",
          "requestTimeout": "Tempo limite da solicitação - Por favor, tente novamente",
          "conflict": "Conflito - O recurso pode ter sido modificado",
          "tooManyRequests": "Muitas solicitações - Por favor, aguarde antes de tentar novamente",
          "internalServerError": "Erro interno do servidor - Por favor, tente novamente mais tarde",
          "notImplemented": "Recurso não implementado",
          "badGateway": "Gateway inválido - Serviço indisponível",
          "serviceUnavailable": "Serviço temporariamente indisponível",
          "gatewayTimeout": "Tempo limite do gateway - Por favor, tente novamente",
          "networkError": "Erro de rede - Por favor, verifique sua conexão",
          "parseError": "Formato de resposta inválido",
          "validationError": "Validação falhou - Por favor, verifique sua entrada",
          "unknownError": "Ocorreu um erro desconhecido"
        },
        "success": {
          "created": "Criado com sucesso",
          "updated": "Atualizado com sucesso",
          "deleted": "Excluído com sucesso",
          "accepted": "Solicitação aceita",
          "completed": "Concluído com sucesso",
          "uploaded": "Enviado com sucesso",
          "downloaded": "Baixado com sucesso",
          "imported": "Importado com sucesso",
          "exported": "Exportado com sucesso",
          "sent": "Enviado com sucesso",
          "received": "Recebido com sucesso",
          "processed": "Processado com sucesso",
          "queued": "Enfileirado com sucesso",
          "started": "Iniciado com sucesso",
          "stopped": "Parado com sucesso",
          "paused": "Pausado com sucesso",
          "resumed": "Retomado com sucesso",
          "refreshed": "Atualizado com sucesso",
          "reloaded": "Recarregado com sucesso",
          "reset": "Redefinido com sucesso",
          "cleared": "Limpo com sucesso",
          "saved": "Salvo com sucesso",
          "copied": "Copiado com sucesso",
          "moved": "Movido com sucesso"
        },
        "validation": {
          "required": "Este campo é obrigatório",
          "invalid": "Valor inválido",
          "tooShort": "Deve ter pelo menos {min} caracteres",
          "tooLong": "Deve ter no máximo {max} caracteres",
          "tooSmall": "Deve ser pelo menos {min}",
          "tooLarge": "Deve ser no máximo {max}",
          "invalidFormat": "Formato inválido",
          "invalidEmail": "Endereço de e-mail inválido",
          "invalidUrl": "URL inválida",
          "invalidNumber": "Número inválido",
          "invalidDate": "Data inválida",
          "invalidTime": "Hora inválida",
          "invalidColor": "Cor inválida",
          "invalidPhone": "Número de telefone inválido",
          "invalidPostalCode": "CEP inválido",
          "invalidCountry": "País inválido",
          "invalidLanguage": "Idioma inválido",
          "invalidCurrency": "Moeda inválida",
          "invalidTimezone": "Fuso horário inválido",
          "invalidCharset": "Charset inválido",
          "invalidEncoding": "Codificação inválida",
          "invalidMimeType": "Tipo MIME inválido",
          "invalidFileSize": "Tamanho de arquivo muito grande",
          "invalidFileType": "Tipo de arquivo inválido",
          "duplicate": "Valor duplicado",
          "conflict": "Conflito com dados existentes",
          "notFound": "Não encontrado",
          "notAllowed": "Não permitido",
          "notSupported": "Não suportado",
          "notAvailable": "Indisponível",
          "notAccessible": "Não acessível",
          "notConnected": "Não conectado",
          "notReachable": "Inacessível",
          "notResponding": "Não está respondendo",
          "notReady": "Não está pronto",
          "notEnabled": "Não habilitado",
          "notDisabled": "Não desabilitado",
          "notActive": "Não ativo",
          "notInactive": "Não inativo",
          "notOnline": "Não está online",
          "notOffline": "Não está offline",
          "notOpen": "Não está aberto",
          "notClosed": "Não está fechado",
          "notLocked": "Não está bloqueado",
          "notUnlocked": "Não está desbloqueado",
          "notEmpty": "Não pode estar vazio",
          "notBlank": "Não pode estar em branco",
          "notNull": "Não pode ser nulo",
          "notUndefined": "Não pode ser indefinido",
          "notBoolean": "Deve ser um booleano",
          "notString": "Deve ser uma string",
          "notNumber": "Deve ser um número",
          "notObject": "Deve ser um objeto",
          "notArray": "Deve ser um array",
          "notFunction": "Deve ser uma função",
          "notDate": "Deve ser uma data",
          "notRegExp": "Deve ser uma expressão regular",
          "notError": "Deve ser um objeto de erro",
          "notPromise": "Deve ser uma promise",
          "notIterable": "Deve ser iterável",
          "notAsync": "Deve ser async",
          "notGenerator": "Deve ser um generator",
          "notSymbol": "Deve ser um symbol",
          "notBigInt": "Deve ser um BigInt"
        },
        "server": {
          "added": "Servidor adicionado com sucesso",
          "updated": "Servidor atualizado com sucesso",
          "deleted": "Servidor excluído com sucesso",
          "connected": "Servidor conectado com sucesso",
          "disconnected": "Servidor desconectado",
          "online": "O servidor está online",
          "offline": "O servidor está offline",
          "testing": "Testando conexão do servidor...",
          "testSuccess": "Teste de conexão bem-sucedido",
          "testFailed": "Teste de conexão falhou",
          "backupStarted": "Backup iniciado com sucesso",
          "backupCompleted": "Backup concluído com sucesso",
          "backupFailed": "Backup falhou",
          "backupCancelled": "Backup cancelado",
          "backupRetried": "Nova tentativa de backup iniciada",
          "configurationUpdated": "Configuração do servidor atualizada",
          "statusUpdated": "Status do servidor atualizado",
          "settingsUpdated": "Configurações do servidor atualizadas",
          "notificationsUpdated": "Notificações do servidor atualizadas"
        },
        "backup": {
          "started": "Backup iniciado",
          "completed": "Backup concluído",
          "failed": "Backup falhou",
          "cancelled": "Backup cancelado",
          "paused": "Backup pausado",
          "resumed": "Backup retomado",
          "retried": "Nova tentativa de backup iniciada",
          "deleted": "Backup excluído",
          "downloaded": "Backup baixado",
          "uploaded": "Backup enviado",
          "verified": "Backup verificado",
          "restored": "Backup restaurado",
          "scheduled": "Backup agendado",
          "unscheduled": "Backup não agendado",
          "enabled": "Backup habilitado",
          "disabled": "Backup desabilitado",
          "configurationUpdated": "Configuração de backup atualizada",
          "settingsUpdated": "Configurações de backup atualizadas",
          "retentionUpdated": "Política de retenção de backup atualizada",
          "cleanupStarted": "Limpeza de backup iniciada",
          "cleanupCompleted": "Limpeza de backup concluída",
          "cleanupFailed": "Limpeza de backup falhou"
        },
        "user": {
          "created": "Usuário criado com sucesso",
          "updated": "Usuário atualizado com sucesso",
          "deleted": "Usuário excluído com sucesso",
          "logged": "Usuário fez login",
          "loggedOut": "Usuário saiu",
          "passwordChanged": "Senha alterada com sucesso",
          "passwordReset": "Senha redefinida com sucesso",
          "emailVerified": "E-mail verificado com sucesso",
          "phoneVerified": "Número de telefone verificado com sucesso",
          "twoFactorEnabled": "Autenticação de dois fatores habilitada",
          "twoFactorDisabled": "Autenticação de dois fatores desabilitada",
          "sessionCreated": "Sessão criada com sucesso",
          "sessionExpired": "Sessão expirou",
          "sessionTerminated": "Sessão encerrada com sucesso",
          "profileUpdated": "Perfil atualizado com sucesso",
          "preferencesUpdated": "Preferências atualizadas com sucesso",
          "notificationsUpdated": "Preferências de notificação atualizadas",
          "apiKeyGenerated": "Chave API gerada com sucesso",
          "apiKeyRegenerated": "Chave API regenerada com sucesso",
          "apiKeyRevoked": "Chave API revogada com sucesso"
        },
        "notification": {
          "sent": "Notificação enviada com sucesso",
          "delivered": "Notificação entregue com sucesso",
          "failed": "Falha ao enviar notificação",
          "queued": "Notificação enfileirada para entrega",
          "processed": "Notificação processada com sucesso",
          "read": "Notificação marcada como lida",
          "unread": "Notificação marcada como não lida",
          "archived": "Notificação arquivada com sucesso",
          "deleted": "Notificação excluída com sucesso",
          "settingsUpdated": "Configurações de notificação atualizadas",
          "templateUpdated": "Modelo de notificação atualizado",
          "channelUpdated": "Canal de notificação atualizado",
          "subscriptionCreated": "Inscrição de notificação criada",
          "subscriptionUpdated": "Inscrição de notificação atualizada",
          "subscriptionDeleted": "Inscrição de notificação excluída",
          "preferencesUpdated": "Preferências de notificação atualizadas"
        }
      }
    }
  },
  "localIds": [
    "api::local::src/app/[locale]/content/api.content.ts"
  ]
} as const;
