/* eslint-disable */
export default {
  "key": "application-logs-viewer",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Application Logs Viewer",
        "refreshLogs": "Refresh logs",
        "refresh": "Refresh",
        "fileVersion": "File Version",
        "current": "Current",
        "search": "Search",
        "searchPlaceholder": "Filter by text (case-insensitive)",
        "clearSearch": "Clear search",
        "linesToShow": "Lines to Show",
        "autoScroll": "Auto-scroll",
        "enableAutoScroll": "Enable auto-scroll",
        "copy": "Copy",
        "download": "Download",
        "loadingLogs": "Loading logs...",
        "noLogsMatch": "No logs match the current filters",
        "noLogsAvailable": "No logs available",
        "showingLines": "Showing {filtered} of {total} lines",
        "scrollToTop": "Scroll to top",
        "scrollToBottom": "Scroll to bottom",
        "lastModified": "Last modified:",
        "fileMismatch": "File mismatch detected. Please refresh.",
        "failedToLoadLogs": "Failed to load logs",
        "logsCopied": "Logs copied to clipboard",
        "failedToCopy": "Failed to copy logs to clipboard",
        "logsExported": "Logs exported successfully",
        "failedToExport": "Failed to export logs"
      },
      "de": {
        "title": "Anwendungsprotokoll-Viewer",
        "refreshLogs": "Protokolle aktualisieren",
        "refresh": "Aktualisieren",
        "fileVersion": "Dateiversion",
        "current": "Aktuell",
        "search": "Suchen",
        "searchPlaceholder": "Nach Text filtern (Groß-/Kleinschreibung ignorieren)",
        "clearSearch": "Suche löschen",
        "linesToShow": "Anzuzeigende Zeilen",
        "autoScroll": "Automatisches Scrollen",
        "enableAutoScroll": "Automatisches Scrollen aktivieren",
        "copy": "Kopieren",
        "download": "Herunterladen",
        "loadingLogs": "Protokolle werden geladen...",
        "noLogsMatch": "Keine Protokolle entsprechen den aktuellen Filtern",
        "noLogsAvailable": "Keine Protokolle verfügbar",
        "showingLines": "Zeige {filtered} von {total} Zeilen",
        "scrollToTop": "Nach oben scrollen",
        "scrollToBottom": "Nach unten scrollen",
        "lastModified": "Zuletzt geändert:",
        "fileMismatch": "Dateiinkonsistenz erkannt. Bitte aktualisieren.",
        "failedToLoadLogs": "Fehler beim Laden der Protokolle",
        "logsCopied": "Protokolle in die Zwischenablage kopiert",
        "failedToCopy": "Fehler beim Kopieren der Protokolle in die Zwischenablage",
        "logsExported": "Protokolle erfolgreich exportiert",
        "failedToExport": "Fehler beim Exportieren der Protokolle"
      },
      "fr": {
        "title": "Visualiseur de journaux d'application",
        "refreshLogs": "Actualiser les journaux",
        "refresh": "Actualiser",
        "fileVersion": "Version du fichier",
        "current": "Actuel",
        "search": "Rechercher",
        "searchPlaceholder": "Filtrer par texte (insensible à la casse)",
        "clearSearch": "Effacer la recherche",
        "linesToShow": "Lignes à afficher",
        "autoScroll": "Défilement automatique",
        "enableAutoScroll": "Activer le défilement automatique",
        "copy": "Copier",
        "download": "Télécharger",
        "loadingLogs": "Chargement des journaux...",
        "noLogsMatch": "Aucun journal ne correspond aux filtres actuels",
        "noLogsAvailable": "Aucun journal disponible",
        "showingLines": "Affichage de {filtered} sur {total} lignes",
        "scrollToTop": "Défiler vers le haut",
        "scrollToBottom": "Défiler vers le bas",
        "lastModified": "Dernière modification:",
        "fileMismatch": "Incohérence de fichier détectée. Veuillez actualiser.",
        "failedToLoadLogs": "Échec du chargement des journaux",
        "logsCopied": "Journaux copiés dans le presse-papiers",
        "failedToCopy": "Échec de la copie des journaux dans le presse-papiers",
        "logsExported": "Journaux exportés avec succès",
        "failedToExport": "Échec de l'exportation des journaux"
      },
      "es": {
        "title": "Visor de registros de aplicación",
        "refreshLogs": "Actualizar registros",
        "refresh": "Actualizar",
        "fileVersion": "Versión del archivo",
        "current": "Actual",
        "search": "Buscar",
        "searchPlaceholder": "Filtrar por texto (sin distinción de mayúsculas y minúsculas)",
        "clearSearch": "Limpiar búsqueda",
        "linesToShow": "Líneas a mostrar",
        "autoScroll": "Desplazamiento automático",
        "enableAutoScroll": "Habilitar desplazamiento automático",
        "copy": "Copiar",
        "download": "Descargar",
        "loadingLogs": "Cargando registros...",
        "noLogsMatch": "Ningún registro coincide con los filtros actuales",
        "noLogsAvailable": "No hay registros disponibles",
        "showingLines": "Mostrando {filtered} de {total} líneas",
        "scrollToTop": "Desplazarse hacia arriba",
        "scrollToBottom": "Desplazarse hacia abajo",
        "lastModified": "Última modificación:",
        "fileMismatch": "Inconsistencia de archivo detectada. Por favor, actualice.",
        "failedToLoadLogs": "Error al cargar los registros",
        "logsCopied": "Registros copiados al portapapeles",
        "failedToCopy": "Error al copiar los registros al portapapeles",
        "logsExported": "Registros exportados exitosamente",
        "failedToExport": "Error al exportar los registros"
      },
      "pt-BR": {
        "title": "Visualizador de registros do aplicativo",
        "refreshLogs": "Atualizar registros",
        "refresh": "Atualizar",
        "fileVersion": "Versão do arquivo",
        "current": "Atual",
        "search": "Pesquisar",
        "searchPlaceholder": "Filtrar por texto (sem distinção entre maiúsculas e minúsculas)",
        "clearSearch": "Limpar pesquisa",
        "linesToShow": "Linhas para mostrar",
        "autoScroll": "Rolagem automática",
        "enableAutoScroll": "Habilitar rolagem automática",
        "copy": "Copiar",
        "download": "Baixar",
        "loadingLogs": "Carregando registros...",
        "noLogsMatch": "Nenhum registro corresponde aos filtros atuais",
        "noLogsAvailable": "Nenhum registro disponível",
        "showingLines": "Mostrando {filtered} de {total} linhas",
        "scrollToTop": "Rolar para o topo",
        "scrollToBottom": "Rolar para baixo",
        "lastModified": "Última modificação:",
        "fileMismatch": "Inconsistência de arquivo detectada. Por favor, atualize.",
        "failedToLoadLogs": "Falha ao carregar registros",
        "logsCopied": "Registros copiados para a área de transferência",
        "failedToCopy": "Falha ao copiar registros para a área de transferência",
        "logsExported": "Registros exportados com sucesso",
        "failedToExport": "Falha ao exportar registros"
      }
    }
  },
  "localIds": [
    "application-logs-viewer::local::src/components/settings/application-logs-viewer.content.ts"
  ]
} as const;
