/* eslint-disable */
export default {
  "key": "audit-log-viewer",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Audit Log",
        "description": "View application audit log entries",
        "retention": "Log Retention",
        "auditLogViewer": "Audit Log Viewer",
        "refresh": "Refresh",
        "refreshAuditLogs": "Refresh audit logs",
        "auditLogViewerFilters": "Audit Log Viewer - Filters",
        "reset": "Reset",
        "csv": "CSV",
        "json": "JSON",
        "startDate": "Start Date",
        "endDate": "End Date",
        "username": "Username",
        "action": "Action",
        "category": "Category",
        "status": "Status",
        "filterByUsername": "Filter by username",
        "allActions": "All actions",
        "allCategories": "All categories",
        "allStatuses": "All statuses",
        "loadingAuditLogs": "Loading audit logs...",
        "noAuditLogsFound": "No audit logs found",
        "tableNumber": "#",
        "timestamp": "Timestamp",
        "user": "User",
        "actionHeader": "Action",
        "categoryHeader": "Category",
        "statusHeader": "Status",
        "target": "Target",
        "actions": "Actions",
        "system": "System",
        "viewDetails": "View details",
        "loadingMore": "Loading more...",
        "noMoreLogsToLoad": "No more logs to load",
        "loadedXOfYTotal": "Loaded {loaded} of {total} total ({percentage}% loaded)",
        "noLogsAvailable": "No logs available",
        "resetToTop": "Reset to Top",
        "auditLogDetails": "Audit Log Details",
        "completeInformationForAuditLogEntry": "Complete information for audit log entry #{id}",
        "timestampLabel": "Timestamp",
        "statusLabel": "Status",
        "userLabel": "User",
        "categoryLabel": "Category",
        "actionLabel": "Action",
        "ipAddress": "IP Address",
        "targetType": "Target Type",
        "targetId": "Target ID",
        "userAgent": "User Agent",
        "details": "Details",
        "errorMessage": "Error Message",
        "success": "Success",
        "failure": "Failure",
        "error": "Error",
        "failedToLoadAuditLogs": "Failed to load audit logs",
        "failedToLoadMoreAuditLogs": "Failed to load more audit logs",
        "failedToLoadFilterValues": "Failed to load filter values. Using loaded records only.",
        "auditLogDownloadedAs": "Audit log downloaded as {format}",
        "failedToDownloadAuditLogs": "Failed to download audit logs"
      },
      "de": {
        "title": "Prüfprotokoll",
        "description": "Anwendungsprüfprotokolleinträge anzeigen",
        "retention": "Protokollaufbewahrung",
        "auditLogViewer": "Prüfprotokoll-Viewer",
        "refresh": "Aktualisieren",
        "refreshAuditLogs": "Prüfprotokolle aktualisieren",
        "auditLogViewerFilters": "Prüfprotokoll-Viewer - Filter",
        "reset": "Zurücksetzen",
        "csv": "CSV",
        "json": "JSON",
        "startDate": "Startdatum",
        "endDate": "Enddatum",
        "username": "Benutzername",
        "action": "Aktion",
        "category": "Kategorie",
        "status": "Status",
        "filterByUsername": "Nach Benutzername filtern",
        "allActions": "Alle Aktionen",
        "allCategories": "Alle Kategorien",
        "allStatuses": "Alle Status",
        "loadingAuditLogs": "Prüfprotokolle werden geladen...",
        "noAuditLogsFound": "Keine Prüfprotokolle gefunden",
        "tableNumber": "#",
        "timestamp": "Zeitstempel",
        "user": "Benutzer",
        "actionHeader": "Aktion",
        "categoryHeader": "Kategorie",
        "statusHeader": "Status",
        "target": "Ziel",
        "actions": "Aktionen",
        "system": "System",
        "viewDetails": "Details anzeigen",
        "loadingMore": "Lade weitere...",
        "noMoreLogsToLoad": "Keine weiteren Protokolle zu laden",
        "loadedXOfYTotal": "{loaded} von {total} insgesamt geladen ({percentage}% geladen)",
        "noLogsAvailable": "Keine Protokolle verfügbar",
        "resetToTop": "Zum Anfang zurücksetzen",
        "auditLogDetails": "Prüfprotokoll-Details",
        "completeInformationForAuditLogEntry": "Vollständige Informationen für Prüfprotokolleintrag #{id}",
        "timestampLabel": "Zeitstempel",
        "statusLabel": "Status",
        "userLabel": "Benutzer",
        "categoryLabel": "Kategorie",
        "actionLabel": "Aktion",
        "ipAddress": "IP-Adresse",
        "targetType": "Zieltyp",
        "targetId": "Ziel-ID",
        "userAgent": "User-Agent",
        "details": "Details",
        "errorMessage": "Fehlermeldung",
        "success": "Erfolg",
        "failure": "Fehler",
        "error": "Fehler",
        "failedToLoadAuditLogs": "Fehler beim Laden der Prüfprotokolle",
        "failedToLoadMoreAuditLogs": "Fehler beim Laden weiterer Prüfprotokolle",
        "failedToLoadFilterValues": "Fehler beim Laden der Filterwerte. Verwende nur geladene Datensätze.",
        "auditLogDownloadedAs": "Prüfprotokoll als {format} heruntergeladen",
        "failedToDownloadAuditLogs": "Fehler beim Herunterladen der Prüfprotokolle"
      },
      "fr": {
        "title": "Journal d'audit",
        "description": "Afficher les entrées du journal d'audit de l'application",
        "retention": "Rétention des journaux",
        "auditLogViewer": "Visualiseur de journal d'audit",
        "refresh": "Actualiser",
        "refreshAuditLogs": "Actualiser les journaux d'audit",
        "auditLogViewerFilters": "Visualiseur de journal d'audit - Filtres",
        "reset": "Réinitialiser",
        "csv": "CSV",
        "json": "JSON",
        "startDate": "Date de début",
        "endDate": "Date de fin",
        "username": "Nom d'utilisateur",
        "action": "Action",
        "category": "Catégorie",
        "status": "Statut",
        "filterByUsername": "Filtrer par nom d'utilisateur",
        "allActions": "Toutes les actions",
        "allCategories": "Toutes les catégories",
        "allStatuses": "Tous les statuts",
        "loadingAuditLogs": "Chargement des journaux d'audit...",
        "noAuditLogsFound": "Aucun journal d'audit trouvé",
        "tableNumber": "#",
        "timestamp": "Horodatage",
        "user": "Utilisateur",
        "actionHeader": "Action",
        "categoryHeader": "Catégorie",
        "statusHeader": "Statut",
        "target": "Cible",
        "actions": "Actions",
        "system": "Système",
        "viewDetails": "Voir les détails",
        "loadingMore": "Chargement de plus...",
        "noMoreLogsToLoad": "Aucun autre journal à charger",
        "loadedXOfYTotal": "{loaded} sur {total} au total chargés ({percentage}% chargés)",
        "noLogsAvailable": "Aucun journal disponible",
        "resetToTop": "Réinitialiser en haut",
        "auditLogDetails": "Détails du journal d'audit",
        "completeInformationForAuditLogEntry": "Informations complètes pour l'entrée du journal d'audit #{id}",
        "timestampLabel": "Horodatage",
        "statusLabel": "Statut",
        "userLabel": "Utilisateur",
        "categoryLabel": "Catégorie",
        "actionLabel": "Action",
        "ipAddress": "Adresse IP",
        "targetType": "Type de cible",
        "targetId": "ID de cible",
        "userAgent": "Agent utilisateur",
        "details": "Détails",
        "errorMessage": "Message d'erreur",
        "success": "Succès",
        "failure": "Échec",
        "error": "Erreur",
        "failedToLoadAuditLogs": "Échec du chargement des journaux d'audit",
        "failedToLoadMoreAuditLogs": "Échec du chargement de plus de journaux d'audit",
        "failedToLoadFilterValues": "Échec du chargement des valeurs de filtre. Utilisation uniquement des enregistrements chargés.",
        "auditLogDownloadedAs": "Journal d'audit téléchargé au format {format}",
        "failedToDownloadAuditLogs": "Échec du téléchargement des journaux d'audit"
      },
      "es": {
        "title": "Registro de auditoría",
        "description": "Ver entradas del registro de auditoría de la aplicación",
        "retention": "Retención de registros",
        "auditLogViewer": "Visor de registro de auditoría",
        "refresh": "Actualizar",
        "refreshAuditLogs": "Actualizar registros de auditoría",
        "auditLogViewerFilters": "Visor de registro de auditoría - Filtros",
        "reset": "Restablecer",
        "csv": "CSV",
        "json": "JSON",
        "startDate": "Fecha de inicio",
        "endDate": "Fecha de fin",
        "username": "Nombre de usuario",
        "action": "Acción",
        "category": "Categoría",
        "status": "Estado",
        "filterByUsername": "Filtrar por nombre de usuario",
        "allActions": "Todas las acciones",
        "allCategories": "Todas las categorías",
        "allStatuses": "Todos los estados",
        "loadingAuditLogs": "Cargando registros de auditoría...",
        "noAuditLogsFound": "No se encontraron registros de auditoría",
        "tableNumber": "#",
        "timestamp": "Marca de tiempo",
        "user": "Usuario",
        "actionHeader": "Acción",
        "categoryHeader": "Categoría",
        "statusHeader": "Estado",
        "target": "Objetivo",
        "actions": "Acciones",
        "system": "Sistema",
        "viewDetails": "Ver detalles",
        "loadingMore": "Cargando más...",
        "noMoreLogsToLoad": "No hay más registros para cargar",
        "loadedXOfYTotal": "{loaded} de {total} total cargados ({percentage}% cargados)",
        "noLogsAvailable": "No hay registros disponibles",
        "resetToTop": "Restablecer al inicio",
        "auditLogDetails": "Detalles del registro de auditoría",
        "completeInformationForAuditLogEntry": "Información completa para la entrada del registro de auditoría #{id}",
        "timestampLabel": "Marca de tiempo",
        "statusLabel": "Estado",
        "userLabel": "Usuario",
        "categoryLabel": "Categoría",
        "actionLabel": "Acción",
        "ipAddress": "Dirección IP",
        "targetType": "Tipo de objetivo",
        "targetId": "ID de objetivo",
        "userAgent": "Agente de usuario",
        "details": "Detalles",
        "errorMessage": "Mensaje de error",
        "success": "Éxito",
        "failure": "Fallo",
        "error": "Error",
        "failedToLoadAuditLogs": "Error al cargar registros de auditoría",
        "failedToLoadMoreAuditLogs": "Error al cargar más registros de auditoría",
        "failedToLoadFilterValues": "Error al cargar valores de filtro. Usando solo registros cargados.",
        "auditLogDownloadedAs": "Registro de auditoría descargado como {format}",
        "failedToDownloadAuditLogs": "Error al descargar registros de auditoría"
      },
      "pt-BR": {
        "title": "Registro de auditoria",
        "description": "Ver entradas do registro de auditoria do aplicativo",
        "retention": "Retenção de registros",
        "auditLogViewer": "Visualizador de registro de auditoria",
        "refresh": "Atualizar",
        "refreshAuditLogs": "Atualizar registros de auditoria",
        "auditLogViewerFilters": "Visualizador de registro de auditoria - Filtros",
        "reset": "Redefinir",
        "csv": "CSV",
        "json": "JSON",
        "startDate": "Data de início",
        "endDate": "Data de término",
        "username": "Nome de usuário",
        "action": "Ação",
        "category": "Categoria",
        "status": "Status",
        "filterByUsername": "Filtrar por nome de usuário",
        "allActions": "Todas as ações",
        "allCategories": "Todas as categorias",
        "allStatuses": "Todos os status",
        "loadingAuditLogs": "Carregando registros de auditoria...",
        "noAuditLogsFound": "Nenhum registro de auditoria encontrado",
        "tableNumber": "#",
        "timestamp": "Data e hora",
        "user": "Usuário",
        "actionHeader": "Ação",
        "categoryHeader": "Categoria",
        "statusHeader": "Status",
        "target": "Destino",
        "actions": "Ações",
        "system": "Sistema",
        "viewDetails": "Ver detalhes",
        "loadingMore": "Carregando mais...",
        "noMoreLogsToLoad": "Não há mais registros para carregar",
        "loadedXOfYTotal": "{loaded} de {total} total carregados ({percentage}% carregados)",
        "noLogsAvailable": "Nenhum registro disponível",
        "resetToTop": "Redefinir para o topo",
        "auditLogDetails": "Detalhes do registro de auditoria",
        "completeInformationForAuditLogEntry": "Informações completas para a entrada do registro de auditoria #{id}",
        "timestampLabel": "Data e hora",
        "statusLabel": "Status",
        "userLabel": "Usuário",
        "categoryLabel": "Categoria",
        "actionLabel": "Ação",
        "ipAddress": "Endereço IP",
        "targetType": "Tipo de destino",
        "targetId": "ID do destino",
        "userAgent": "Agente do usuário",
        "details": "Detalhes",
        "errorMessage": "Mensagem de erro",
        "success": "Sucesso",
        "failure": "Falha",
        "error": "Erro",
        "failedToLoadAuditLogs": "Falha ao carregar registros de auditoria",
        "failedToLoadMoreAuditLogs": "Falha ao carregar mais registros de auditoria",
        "failedToLoadFilterValues": "Falha ao carregar valores de filtro. Usando apenas registros carregados.",
        "auditLogDownloadedAs": "Registro de auditoria baixado como {format}",
        "failedToDownloadAuditLogs": "Falha ao baixar registros de auditoria"
      }
    }
  },
  "localIds": [
    "audit-log-viewer::local::src/components/settings/audit-log-viewer.content.ts"
  ]
} as const;
