/* eslint-disable */
export default {
  "key": "auth",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "login": {
          "title": "Login",
          "subtitle": "Sign in to your account",
          "username": "Username",
          "usernamePlaceholder": "Enter your username",
          "password": "Password",
          "passwordPlaceholder": "Enter your password",
          "rememberMe": "Remember me",
          "forgotPassword": "Forgot password?",
          "loginButton": "Login",
          "loginInProgress": "Logging in...",
          "loginSuccess": "Login successful",
          "loginFailed": "Login failed",
          "invalidCredentials": "Invalid username or password",
          "accountLocked": "Account locked. Please try again later.",
          "sessionExpired": "Session expired. Please login again.",
          "networkError": "Network error. Please check your connection."
        },
        "logout": {
          "title": "Logout",
          "message": "Are you sure you want to logout?",
          "confirm": "Logout",
          "cancel": "Cancel",
          "logoutSuccess": "Logged out successfully",
          "logoutFailed": "Failed to logout"
        },
        "changePassword": {
          "title": "Change Password",
          "description": "Enter your current password and choose a new one",
          "currentPassword": "Current Password",
          "currentPasswordPlaceholder": "Enter your current password",
          "newPassword": "New Password",
          "newPasswordPlaceholder": "Enter your new password",
          "confirmPassword": "Confirm New Password",
          "confirmPasswordPlaceholder": "Confirm your new password",
          "requirements": {
            "minLength": "At least {min} characters",
            "requireUppercase": "At least one uppercase letter",
            "requireLowercase": "At least one lowercase letter",
            "requireNumbers": "At least one number",
            "requireSymbols": "At least one special character"
          },
          "saveButton": "Change Password",
          "cancelButton": "Cancel",
          "changeSuccess": "Password changed successfully",
          "changeFailed": "Failed to change password",
          "currentPasswordIncorrect": "Current password is incorrect",
          "passwordsDoNotMatch": "Passwords do not match"
        },
        "register": {
          "title": "Register Account",
          "subtitle": "Create a new account to get started",
          "username": "Username",
          "usernamePlaceholder": "Choose a username",
          "email": "Email",
          "emailPlaceholder": "Enter your email address",
          "password": "Password",
          "passwordPlaceholder": "Choose a password",
          "confirmPassword": "Confirm Password",
          "confirmPasswordPlaceholder": "Confirm your password",
          "registerButton": "Register",
          "registerInProgress": "Creating account...",
          "registerSuccess": "Account created successfully",
          "registerFailed": "Failed to create account",
          "usernameTaken": "Username is already taken",
          "emailInvalid": "Invalid email address",
          "passwordsDoNotMatch": "Passwords do not match",
          "termsAndConditions": "Terms and Conditions",
          "privacyPolicy": "Privacy Policy"
        },
        "forgotPassword": {
          "title": "Forgot Password",
          "description": "Enter your email address to receive password reset instructions",
          "email": "Email Address",
          "emailPlaceholder": "Enter your email address",
          "sendButton": "Send Reset Link",
          "sendInProgress": "Sending...",
          "sendSuccess": "Reset link sent successfully",
          "sendFailed": "Failed to send reset link",
          "emailNotFound": "Email address not found",
          "backToLogin": "Back to Login"
        },
        "resetPassword": {
          "title": "Reset Password",
          "description": "Enter a new password for your account",
          "newPassword": "New Password",
          "newPasswordPlaceholder": "Enter your new password",
          "confirmPassword": "Confirm Password",
          "confirmPasswordPlaceholder": "Confirm your new password",
          "resetButton": "Reset Password",
          "resetInProgress": "Resetting...",
          "resetSuccess": "Password reset successfully",
          "resetFailed": "Failed to reset password",
          "invalidToken": "Invalid or expired reset token",
          "expiredToken": "Reset token has expired",
          "passwordsDoNotMatch": "Passwords do not match",
          "backToLogin": "Back to Login"
        },
        "twoFactor": {
          "title": "Two-Factor Authentication",
          "description": "Enter the verification code from your authenticator app",
          "code": "Verification Code",
          "codePlaceholder": "Enter 6-digit code",
          "verifyButton": "Verify",
          "verifyInProgress": "Verifying...",
          "verifySuccess": "Verification successful",
          "verifyFailed": "Verification failed",
          "invalidCode": "Invalid verification code",
          "backupCode": "Backup Code",
          "backupCodePlaceholder": "Enter backup code",
          "useBackupCode": "Use Backup Code",
          "resendCode": "Resend Code"
        }
      },
      "de": {
        "login": {
          "title": "Anmelden",
          "subtitle": "Melden Sie sich bei Ihrem Konto an",
          "username": "Benutzername",
          "usernamePlaceholder": "Geben Sie Ihren Benutzernamen ein",
          "password": "Passwort",
          "passwordPlaceholder": "Geben Sie Ihr Passwort ein",
          "rememberMe": "Angemeldet bleiben",
          "forgotPassword": "Passwort vergessen?",
          "loginButton": "Anmelden",
          "loginInProgress": "Anmeldung läuft...",
          "loginSuccess": "Anmeldung erfolgreich",
          "loginFailed": "Anmeldung fehlgeschlagen",
          "invalidCredentials": "Ungültiger Benutzername oder Passwort",
          "accountLocked": "Konto gesperrt. Bitte versuchen Sie es später erneut.",
          "sessionExpired": "Sitzung abgelaufen. Bitte melden Sie sich erneut an.",
          "networkError": "Netzwerkfehler. Bitte überprüfen Sie Ihre Verbindung."
        },
        "logout": {
          "title": "Abmelden",
          "message": "Sind Sie sicher, dass Sie sich abmelden möchten?",
          "confirm": "Abmelden",
          "cancel": "Abbrechen",
          "logoutSuccess": "Erfolgreich abgemeldet",
          "logoutFailed": "Abmelden fehlgeschlagen"
        },
        "changePassword": {
          "title": "Passwort ändern",
          "description": "Geben Sie Ihr aktuelles Passwort ein und wählen Sie ein neues",
          "currentPassword": "Aktuelles Passwort",
          "currentPasswordPlaceholder": "Geben Sie Ihr aktuelles Passwort ein",
          "newPassword": "Neues Passwort",
          "newPasswordPlaceholder": "Geben Sie Ihr neues Passwort ein",
          "confirmPassword": "Neues Passwort bestätigen",
          "confirmPasswordPlaceholder": "Bestätigen Sie Ihr neues Passwort",
          "requirements": {
            "minLength": "Mindestens {min} Zeichen",
            "requireUppercase": "Mindestens ein Großbuchstabe",
            "requireLowercase": "Mindestens ein Kleinbuchstabe",
            "requireNumbers": "Mindestens eine Zahl",
            "requireSymbols": "Mindestens ein Sonderzeichen"
          },
          "saveButton": "Passwort ändern",
          "cancelButton": "Abbrechen",
          "changeSuccess": "Passwort erfolgreich geändert",
          "changeFailed": "Passwortänderung fehlgeschlagen",
          "currentPasswordIncorrect": "Aktuelles Passwort ist falsch",
          "passwordsDoNotMatch": "Passwörter stimmen nicht überein"
        },
        "register": {
          "title": "Konto registrieren",
          "subtitle": "Erstellen Sie ein neues Konto, um zu beginnen",
          "username": "Benutzername",
          "usernamePlaceholder": "Wählen Sie einen Benutzernamen",
          "email": "E-Mail",
          "emailPlaceholder": "Geben Sie Ihre E-Mail-Adresse ein",
          "password": "Passwort",
          "passwordPlaceholder": "Wählen Sie ein Passwort",
          "confirmPassword": "Passwort bestätigen",
          "confirmPasswordPlaceholder": "Bestätigen Sie Ihr Passwort",
          "registerButton": "Registrieren",
          "registerInProgress": "Konto wird erstellt...",
          "registerSuccess": "Konto erfolgreich erstellt",
          "registerFailed": "Kontoerstellung fehlgeschlagen",
          "usernameTaken": "Benutzername ist bereits vergeben",
          "emailInvalid": "Ungültige E-Mail-Adresse",
          "passwordsDoNotMatch": "Passwörter stimmen nicht überein",
          "termsAndConditions": "Allgemeine Geschäftsbedingungen",
          "privacyPolicy": "Datenschutzerklärung"
        },
        "forgotPassword": {
          "title": "Passwort vergessen",
          "description": "Geben Sie Ihre E-Mail-Adresse ein, um Anweisungen zum Zurücksetzen des Passworts zu erhalten",
          "email": "E-Mail-Adresse",
          "emailPlaceholder": "Geben Sie Ihre E-Mail-Adresse ein",
          "sendButton": "Reset-Link senden",
          "sendInProgress": "Wird gesendet...",
          "sendSuccess": "Reset-Link erfolgreich gesendet",
          "sendFailed": "Reset-Link konnte nicht gesendet werden",
          "emailNotFound": "E-Mail-Adresse nicht gefunden",
          "backToLogin": "Zurück zum Login"
        },
        "resetPassword": {
          "title": "Passwort zurücksetzen",
          "description": "Geben Sie ein neues Passwort für Ihr Konto ein",
          "newPassword": "Neues Passwort",
          "newPasswordPlaceholder": "Geben Sie Ihr neues Passwort ein",
          "confirmPassword": "Passwort bestätigen",
          "confirmPasswordPlaceholder": "Bestätigen Sie Ihr neues Passwort",
          "resetButton": "Passwort zurücksetzen",
          "resetInProgress": "Wird zurückgesetzt...",
          "resetSuccess": "Passwort erfolgreich zurückgesetzt",
          "resetFailed": "Passwort zurücksetzen fehlgeschlagen",
          "invalidToken": "Ungültiger oder abgelaufener Reset-Token",
          "expiredToken": "Reset-Token ist abgelaufen",
          "passwordsDoNotMatch": "Passwörter stimmen nicht überein",
          "backToLogin": "Zurück zum Login"
        },
        "twoFactor": {
          "title": "Zwei-Faktor-Authentifizierung",
          "description": "Geben Sie den Bestätigungscode von Ihrer Authenticator-App ein",
          "code": "Bestätigungscode",
          "codePlaceholder": "6-stelligen Code eingeben",
          "verifyButton": "Bestätigen",
          "verifyInProgress": "Wird überprüft...",
          "verifySuccess": "Bestätigung erfolgreich",
          "verifyFailed": "Bestätigung fehlgeschlagen",
          "invalidCode": "Ungültiger Bestätigungscode",
          "backupCode": "Backup-Code",
          "backupCodePlaceholder": "Backup-Code eingeben",
          "useBackupCode": "Backup-Code verwenden",
          "resendCode": "Code erneut senden"
        }
      },
      "fr": {
        "login": {
          "title": "Connexion",
          "subtitle": "Connectez-vous à votre compte",
          "username": "Nom d'utilisateur",
          "usernamePlaceholder": "Entrez votre nom d'utilisateur",
          "password": "Mot de passe",
          "passwordPlaceholder": "Entrez votre mot de passe",
          "rememberMe": "Se souvenir de moi",
          "forgotPassword": "Mot de passe oublié?",
          "loginButton": "Connexion",
          "loginInProgress": "Connexion en cours...",
          "loginSuccess": "Connexion réussie",
          "loginFailed": "Connexion échouée",
          "invalidCredentials": "Nom d'utilisateur ou mot de passe invalide",
          "accountLocked": "Compte verrouillé. Veuillez réessayer plus tard.",
          "sessionExpired": "Session expirée. Veuillez vous reconnecter.",
          "networkError": "Erreur réseau. Veuillez vérifier votre connexion."
        },
        "logout": {
          "title": "Déconnexion",
          "message": "Êtes-vous sûr de vouloir vous déconnecter?",
          "confirm": "Déconnexion",
          "cancel": "Annuler",
          "logoutSuccess": "Déconnecté avec succès",
          "logoutFailed": "Échec de la déconnexion"
        },
        "changePassword": {
          "title": "Changer le mot de passe",
          "description": "Entrez votre mot de passe actuel et choisissez-en un nouveau",
          "currentPassword": "Mot de passe actuel",
          "currentPasswordPlaceholder": "Entrez votre mot de passe actuel",
          "newPassword": "Nouveau mot de passe",
          "newPasswordPlaceholder": "Entrez votre nouveau mot de passe",
          "confirmPassword": "Confirmer le nouveau mot de passe",
          "confirmPasswordPlaceholder": "Confirmez votre nouveau mot de passe",
          "requirements": {
            "minLength": "Au moins {min} caractères",
            "requireUppercase": "Au moins une lettre majuscule",
            "requireLowercase": "Au moins une lettre minuscule",
            "requireNumbers": "Au moins un chiffre",
            "requireSymbols": "Au moins un caractère spécial"
          },
          "saveButton": "Changer le mot de passe",
          "cancelButton": "Annuler",
          "changeSuccess": "Mot de passe changé avec succès",
          "changeFailed": "Échec du changement de mot de passe",
          "currentPasswordIncorrect": "Le mot de passe actuel est incorrect",
          "passwordsDoNotMatch": "Les mots de passe ne correspondent pas"
        },
        "register": {
          "title": "Créer un compte",
          "subtitle": "Créez un nouveau compte pour commencer",
          "username": "Nom d'utilisateur",
          "usernamePlaceholder": "Choisissez un nom d'utilisateur",
          "email": "E-mail",
          "emailPlaceholder": "Entrez votre adresse e-mail",
          "password": "Mot de passe",
          "passwordPlaceholder": "Choisissez un mot de passe",
          "confirmPassword": "Confirmer le mot de passe",
          "confirmPasswordPlaceholder": "Confirmez votre mot de passe",
          "registerButton": "Créer un compte",
          "registerInProgress": "Création du compte...",
          "registerSuccess": "Compte créé avec succès",
          "registerFailed": "Échec de la création du compte",
          "usernameTaken": "Le nom d'utilisateur est déjà pris",
          "emailInvalid": "Adresse e-mail invalide",
          "passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
          "termsAndConditions": "Conditions générales d'utilisation",
          "privacyPolicy": "Politique de confidentialité"
        },
        "forgotPassword": {
          "title": "Mot de passe oublié",
          "description": "Entrez votre adresse e-mail pour recevoir les instructions de réinitialisation du mot de passe",
          "email": "Adresse e-mail",
          "emailPlaceholder": "Entrez votre adresse e-mail",
          "sendButton": "Envoyer le lien de réinitialisation",
          "sendInProgress": "Envoi en cours...",
          "sendSuccess": "Lien de réinitialisation envoyé avec succès",
          "sendFailed": "Échec de l'envoi du lien de réinitialisation",
          "emailNotFound": "Adresse e-mail introuvable",
          "backToLogin": "Retour à la connexion"
        },
        "resetPassword": {
          "title": "Réinitialiser le mot de passe",
          "description": "Entrez un nouveau mot de passe pour votre compte",
          "newPassword": "Nouveau mot de passe",
          "newPasswordPlaceholder": "Entrez votre nouveau mot de passe",
          "confirmPassword": "Confirmer le mot de passe",
          "confirmPasswordPlaceholder": "Confirmez votre nouveau mot de passe",
          "resetButton": "Réinitialiser le mot de passe",
          "resetInProgress": "Réinitialisation...",
          "resetSuccess": "Mot de passe réinitialisé avec succès",
          "resetFailed": "Échec de la réinitialisation du mot de passe",
          "invalidToken": "Jeton de réinitialisation invalide ou expiré",
          "expiredToken": "Le jeton de réinitialisation a expiré",
          "passwordsDoNotMatch": "Les mots de passe ne correspondent pas",
          "backToLogin": "Retour à la connexion"
        },
        "twoFactor": {
          "title": "Authentification à deux facteurs",
          "description": "Entrez le code de vérification de votre application d'authentification",
          "code": "Code de vérification",
          "codePlaceholder": "Entrez le code à 6 chiffres",
          "verifyButton": "Vérifier",
          "verifyInProgress": "Vérification...",
          "verifySuccess": "Vérification réussie",
          "verifyFailed": "Échec de la vérification",
          "invalidCode": "Code de vérification invalide",
          "backupCode": "Code de sauvegarde",
          "backupCodePlaceholder": "Entrez le code de sauvegarde",
          "useBackupCode": "Utiliser le code de sauvegarde",
          "resendCode": "Renvoyer le code"
        }
      },
      "es": {
        "login": {
          "title": "Iniciar sesión",
          "subtitle": "Inicie sesión en su cuenta",
          "username": "Nombre de usuario",
          "usernamePlaceholder": "Ingrese su nombre de usuario",
          "password": "Contraseña",
          "passwordPlaceholder": "Ingrese su contraseña",
          "rememberMe": "Recordarme",
          "forgotPassword": "¿Olvidó su contraseña?",
          "loginButton": "Iniciar sesión",
          "loginInProgress": "Iniciando sesión...",
          "loginSuccess": "Inicio de sesión exitoso",
          "loginFailed": "Inicio de sesión fallido",
          "invalidCredentials": "Nombre de usuario o contraseña inválidos",
          "accountLocked": "Cuenta bloqueada. Por favor inténtelo más tarde.",
          "sessionExpired": "Sesión expirada. Por favor inicie sesión nuevamente.",
          "networkError": "Error de red. Por favor verifique su conexión."
        },
        "logout": {
          "title": "Cerrar sesión",
          "message": "¿Está seguro de que desea cerrar sesión?",
          "confirm": "Cerrar sesión",
          "cancel": "Cancelar",
          "logoutSuccess": "Sesión cerrada exitosamente",
          "logoutFailed": "Falló cerrar sesión"
        },
        "changePassword": {
          "title": "Cambiar contraseña",
          "description": "Ingrese su contraseña actual y elija una nueva",
          "currentPassword": "Contraseña actual",
          "currentPasswordPlaceholder": "Ingrese su contraseña actual",
          "newPassword": "Nueva contraseña",
          "newPasswordPlaceholder": "Ingrese su nueva contraseña",
          "confirmPassword": "Confirmar nueva contraseña",
          "confirmPasswordPlaceholder": "Confirme su nueva contraseña",
          "requirements": {
            "minLength": "Al menos {min} caracteres",
            "requireUppercase": "Al menos una letra mayúscula",
            "requireLowercase": "Al menos una letra minúscula",
            "requireNumbers": "Al menos un número",
            "requireSymbols": "Al menos un carácter especial"
          },
          "saveButton": "Cambiar contraseña",
          "cancelButton": "Cancelar",
          "changeSuccess": "Contraseña cambiada exitosamente",
          "changeFailed": "Falló cambiar contraseña",
          "currentPasswordIncorrect": "La contraseña actual es incorrecta",
          "passwordsDoNotMatch": "Las contraseñas no coinciden"
        },
        "register": {
          "title": "Registrar cuenta",
          "subtitle": "Cree una nueva cuenta para comenzar",
          "username": "Nombre de usuario",
          "usernamePlaceholder": "Elija un nombre de usuario",
          "email": "Correo electrónico",
          "emailPlaceholder": "Ingrese su dirección de correo electrónico",
          "password": "Contraseña",
          "passwordPlaceholder": "Elija una contraseña",
          "confirmPassword": "Confirmar contraseña",
          "confirmPasswordPlaceholder": "Confirme su contraseña",
          "registerButton": "Registrar",
          "registerInProgress": "Creando cuenta...",
          "registerSuccess": "Cuenta creada exitosamente",
          "registerFailed": "Falló crear cuenta",
          "usernameTaken": "El nombre de usuario ya está tomado",
          "emailInvalid": "Dirección de correo electrónico inválida",
          "passwordsDoNotMatch": "Las contraseñas no coinciden",
          "termsAndConditions": "Términos y Condiciones",
          "privacyPolicy": "Política de privacidad"
        },
        "forgotPassword": {
          "title": "¿Olvidó su contraseña?",
          "description": "Ingrese su dirección de correo electrónico para recibir instrucciones de restablecimiento de contraseña",
          "email": "Dirección de correo electrónico",
          "emailPlaceholder": "Ingrese su dirección de correo electrónico",
          "sendButton": "Enviar enlace de restablecimiento",
          "sendInProgress": "Enviando...",
          "sendSuccess": "Enlace de restablecimiento enviado exitosamente",
          "sendFailed": "Falló enviar enlace de restablecimiento",
          "emailNotFound": "Dirección de correo electrónico no encontrada",
          "backToLogin": "Volver al inicio de sesión"
        },
        "resetPassword": {
          "title": "Restablecer contraseña",
          "description": "Ingrese una nueva contraseña para su cuenta",
          "newPassword": "Nueva contraseña",
          "newPasswordPlaceholder": "Ingrese su nueva contraseña",
          "confirmPassword": "Confirmar contraseña",
          "confirmPasswordPlaceholder": "Confirme su nueva contraseña",
          "resetButton": "Restablecer contraseña",
          "resetInProgress": "Restableciendo...",
          "resetSuccess": "Contraseña restablecida exitosamente",
          "resetFailed": "Falló restablecer contraseña",
          "invalidToken": "Token de restablecimiento inválido o expirado",
          "expiredToken": "El token de restablecimiento ha expirado",
          "passwordsDoNotMatch": "Las contraseñas no coinciden",
          "backToLogin": "Volver al inicio de sesión"
        },
        "twoFactor": {
          "title": "Autenticación de dos factores",
          "description": "Ingrese el código de verificación de su aplicación autenticadora",
          "code": "Código de verificación",
          "codePlaceholder": "Ingrese código de 6 dígitos",
          "verifyButton": "Verificar",
          "verifyInProgress": "Verificando...",
          "verifySuccess": "Verificación exitosa",
          "verifyFailed": "Verificación fallida",
          "invalidCode": "Código de verificación inválido",
          "backupCode": "Código de respaldo",
          "backupCodePlaceholder": "Ingrese código de respaldo",
          "useBackupCode": "Usar código de respaldo",
          "resendCode": "Reenviar código"
        }
      },
      "pt-BR": {
        "login": {
          "title": "Login",
          "subtitle": "Entre na sua conta",
          "username": "Nome de usuário",
          "usernamePlaceholder": "Digite seu nome de usuário",
          "password": "Senha",
          "passwordPlaceholder": "Digite sua senha",
          "rememberMe": "Lembrar de mim",
          "forgotPassword": "Esqueceu a senha?",
          "loginButton": "Login",
          "loginInProgress": "Fazendo login...",
          "loginSuccess": "Login bem-sucedido",
          "loginFailed": "Login falhou",
          "invalidCredentials": "Nome de usuário ou senha inválidos",
          "accountLocked": "Conta bloqueada. Por favor, tente novamente mais tarde.",
          "sessionExpired": "Sessão expirada. Por favor, faça login novamente.",
          "networkError": "Erro de rede. Por favor, verifique sua conexão."
        },
        "logout": {
          "title": "Sair",
          "message": "Tem certeza de que deseja sair?",
          "confirm": "Sair",
          "cancel": "Cancelar",
          "logoutSuccess": "Saiu com sucesso",
          "logoutFailed": "Falha ao sair"
        },
        "changePassword": {
          "title": "Alterar senha",
          "description": "Digite sua senha atual e escolha uma nova",
          "currentPassword": "Senha atual",
          "currentPasswordPlaceholder": "Digite sua senha atual",
          "newPassword": "Nova senha",
          "newPasswordPlaceholder": "Digite sua nova senha",
          "confirmPassword": "Confirmar nova senha",
          "confirmPasswordPlaceholder": "Confirme sua nova senha",
          "requirements": {
            "minLength": "Pelo menos {min} caracteres",
            "requireUppercase": "Pelo menos uma letra maiúscula",
            "requireLowercase": "Pelo menos uma letra minúscula",
            "requireNumbers": "Pelo menos um número",
            "requireSymbols": "Pelo menos um caractere especial"
          },
          "saveButton": "Alterar senha",
          "cancelButton": "Cancelar",
          "changeSuccess": "Senha alterada com sucesso",
          "changeFailed": "Falha ao alterar senha",
          "currentPasswordIncorrect": "A senha atual está incorreta",
          "passwordsDoNotMatch": "As senhas não correspondem"
        },
        "register": {
          "title": "Registrar conta",
          "subtitle": "Crie uma nova conta para começar",
          "username": "Nome de usuário",
          "usernamePlaceholder": "Escolha um nome de usuário",
          "email": "E-mail",
          "emailPlaceholder": "Digite seu endereço de e-mail",
          "password": "Senha",
          "passwordPlaceholder": "Escolha uma senha",
          "confirmPassword": "Confirmar senha",
          "confirmPasswordPlaceholder": "Confirme sua senha",
          "registerButton": "Registrar",
          "registerInProgress": "Criando conta...",
          "registerSuccess": "Conta criada com sucesso",
          "registerFailed": "Falha ao criar conta",
          "usernameTaken": "Nome de usuário já está em uso",
          "emailInvalid": "Endereço de e-mail inválido",
          "passwordsDoNotMatch": "As senhas não correspondem",
          "termsAndConditions": "Termos e Condições",
          "privacyPolicy": "Política de Privacidade"
        },
        "forgotPassword": {
          "title": "Esqueceu a senha",
          "description": "Digite seu endereço de e-mail para receber instruções de redefinição de senha",
          "email": "Endereço de E-mail",
          "emailPlaceholder": "Digite seu endereço de e-mail",
          "sendButton": "Enviar link de redefinição",
          "sendInProgress": "Enviando...",
          "sendSuccess": "Link de redefinição enviado com sucesso",
          "sendFailed": "Falha ao enviar link de redefinição",
          "emailNotFound": "Endereço de e-mail não encontrado",
          "backToLogin": "Voltar ao Login"
        },
        "resetPassword": {
          "title": "Redefinir senha",
          "description": "Digite uma nova senha para sua conta",
          "newPassword": "Nova senha",
          "newPasswordPlaceholder": "Digite sua nova senha",
          "confirmPassword": "Confirmar senha",
          "confirmPasswordPlaceholder": "Confirme sua nova senha",
          "resetButton": "Redefinir senha",
          "resetInProgress": "Redefinindo...",
          "resetSuccess": "Senha redefinida com sucesso",
          "resetFailed": "Falha ao redefinir senha",
          "invalidToken": "Token de redefinição inválido ou expirado",
          "expiredToken": "O token de redefinição expirou",
          "passwordsDoNotMatch": "As senhas não correspondem",
          "backToLogin": "Voltar ao Login"
        },
        "twoFactor": {
          "title": "Autenticação de Dois Fatores",
          "description": "Digite o código de verificação do seu aplicativo autenticador",
          "code": "Código de verificação",
          "codePlaceholder": "Digite código de 6 dígitos",
          "verifyButton": "Verificar",
          "verifyInProgress": "Verificando...",
          "verifySuccess": "Verificação bem-sucedida",
          "verifyFailed": "Verificação falhou",
          "invalidCode": "Código de verificação inválido",
          "backupCode": "Código de backup",
          "backupCodePlaceholder": "Digite código de backup",
          "useBackupCode": "Usar código de backup",
          "resendCode": "Reenviar código"
        }
      }
    }
  },
  "localIds": [
    "auth::local::src/app/[locale]/content/auth.content.ts"
  ]
} as const;
