/* eslint-disable */
export default {
  "key": "backup-notifications-form",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Configure Backup Notifications",
        "description": "Configure notification settings for a server or backup when a new backup log is received. Icons indicate additional destinations:",
        "serverDefaults": "for server defaults",
        "customBackupOverrides": "for custom backup overrides",
        "inheritedDestinations": "for inherited destinations",
        "filterByServerName": "Filter by Server Name",
        "searchPlaceholder": "Search by server name or alias...",
        "serverBackup": "Server / Backup",
        "notificationEvents": "Notification Events",
        "ntfyNotifications": "NTFY Notifications",
        "emailNotifications": "Email Notifications",
        "emailNotificationsDisabled": "Email Notifications (disabled)",
        "warnings": "Warnings",
        "errors": "Errors",
        "all": "All",
        "off": "Off",
        "backupNotifications": "Backup Notifications",
        "noServersWithBackups": "No servers with backups found in the database",
        "noServersRegistered": "No servers with backups have been registered yet. Add some backup data first to see backup notification settings."
      },
      "de": {
        "title": "Sicherungsbenachrichtigungen konfigurieren",
        "description": "Konfigurieren Sie Benachrichtigungseinstellungen für einen Server oder eine Sicherung, wenn ein neues Sicherungsprotokoll empfangen wird. Symbole zeigen zusätzliche Ziele an:",
        "serverDefaults": "für Server-Standardeinstellungen",
        "customBackupOverrides": "für benutzerdefinierte Sicherungsüberschreibungen",
        "inheritedDestinations": "für geerbte Ziele",
        "filterByServerName": "Nach Servername filtern",
        "searchPlaceholder": "Nach Servername oder Alias suchen...",
        "serverBackup": "Server / Sicherung",
        "notificationEvents": "Benachrichtigungsereignisse",
        "ntfyNotifications": "NTFY-Benachrichtigungen",
        "emailNotifications": "E-Mail-Benachrichtigungen",
        "emailNotificationsDisabled": "E-Mail-Benachrichtigungen (deaktiviert)",
        "warnings": "Warnungen",
        "errors": "Fehler",
        "all": "Alle",
        "off": "Aus",
        "backupNotifications": "Sicherungsbenachrichtigungen",
        "noServersWithBackups": "Keine Server mit Sicherungen in der Datenbank gefunden",
        "noServersRegistered": "Es wurden noch keine Server mit Sicherungen registriert. Fügen Sie zuerst einige Sicherungsdaten hinzu, um die Einstellungen für Sicherungsbenachrichtigungen anzuzeigen."
      },
      "fr": {
        "title": "Configurer les notifications de sauvegarde",
        "description": "Configurez les paramètres de notification pour un serveur ou une sauvegarde lorsqu'un nouveau journal de sauvegarde est reçu. Les icônes indiquent des destinations supplémentaires:",
        "serverDefaults": "pour les paramètres par défaut du serveur",
        "customBackupOverrides": "pour les remplacements de sauvegarde personnalisés",
        "inheritedDestinations": "pour les destinations héritées",
        "filterByServerName": "Filtrer par nom de serveur",
        "searchPlaceholder": "Rechercher par nom de serveur ou alias...",
        "serverBackup": "Serveur / Sauvegarde",
        "notificationEvents": "Événements de notification",
        "ntfyNotifications": "Notifications NTFY",
        "emailNotifications": "Notifications par e-mail",
        "emailNotificationsDisabled": "Notifications par e-mail (désactivées)",
        "warnings": "Avertissements",
        "errors": "Erreurs",
        "all": "Tous",
        "off": "Désactivé",
        "backupNotifications": "Notifications de sauvegarde",
        "noServersWithBackups": "Aucun serveur avec sauvegardes trouvé dans la base de données",
        "noServersRegistered": "Aucun serveur avec sauvegardes n'a encore été enregistré. Ajoutez d'abord des données de sauvegarde pour voir les paramètres de notification de sauvegarde."
      },
      "es": {
        "title": "Configurar notificaciones de respaldo",
        "description": "Configure los ajustes de notificación para un servidor o respaldo cuando se recibe un nuevo registro de respaldo. Los iconos indican destinos adicionales:",
        "serverDefaults": "para valores predeterminados del servidor",
        "customBackupOverrides": "para anulaciones de respaldo personalizadas",
        "inheritedDestinations": "para destinos heredados",
        "filterByServerName": "Filtrar por nombre del servidor",
        "searchPlaceholder": "Buscar por nombre del servidor o alias...",
        "serverBackup": "Servidor / Respaldo",
        "notificationEvents": "Eventos de notificación",
        "ntfyNotifications": "Notificaciones NTFY",
        "emailNotifications": "Notificaciones por correo electrónico",
        "emailNotificationsDisabled": "Notificaciones por correo electrónico (desactivadas)",
        "warnings": "Advertencias",
        "errors": "Errores",
        "all": "Todos",
        "off": "Desactivado",
        "backupNotifications": "Notificaciones de respaldo",
        "noServersWithBackups": "No se encontraron servidores con respaldos en la base de datos",
        "noServersRegistered": "Aún no se han registrado servidores con respaldos. Agregue primero algunos datos de respaldo para ver la configuración de notificaciones de respaldo."
      },
      "pt-BR": {
        "title": "Configurar notificações de backup",
        "description": "Configure as configurações de notificação para um servidor ou backup quando um novo log de backup é recebido. Os ícones indicam destinos adicionais:",
        "serverDefaults": "para padrões do servidor",
        "customBackupOverrides": "para substituições de backup personalizadas",
        "inheritedDestinations": "para destinos herdados",
        "filterByServerName": "Filtrar por nome do servidor",
        "searchPlaceholder": "Pesquisar por nome do servidor ou alias...",
        "serverBackup": "Servidor / Backup",
        "notificationEvents": "Eventos de notificação",
        "ntfyNotifications": "Notificações NTFY",
        "emailNotifications": "Notificações por e-mail",
        "emailNotificationsDisabled": "Notificações por e-mail (desativadas)",
        "warnings": "Avisos",
        "errors": "Erros",
        "all": "Todos",
        "off": "Desativado",
        "backupNotifications": "Notificações de backup",
        "noServersWithBackups": "Nenhum servidor com backups encontrado no banco de dados",
        "noServersRegistered": "Nenhum servidor com backups foi registrado ainda. Adicione primeiro alguns dados de backup para ver as configurações de notificação de backup."
      }
    }
  },
  "localIds": [
    "backup-notifications-form::local::src/components/settings/backup-notifications-form.content.ts"
  ]
} as const;
