/* eslint-disable */
export default {
  "key": "common",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "ui": {
          "loading": "Loading...",
          "error": "Error",
          "success": "Success",
          "cancel": "Cancel",
          "save": "Save",
          "delete": "Delete",
          "edit": "Edit",
          "add": "Add",
          "search": "Search",
          "filter": "Filter",
          "refresh": "Refresh",
          "close": "Close",
          "confirm": "Confirm",
          "back": "Back",
          "next": "Next",
          "previous": "Previous",
          "submit": "Submit",
          "reset": "Reset",
          "clear": "Clear",
          "select": "Select",
          "selectAll": "Select All",
          "deselectAll": "Deselect All",
          "copy": "Copy",
          "export": "Export",
          "import": "Import",
          "download": "Download",
          "upload": "Upload",
          "view": "View",
          "hide": "Hide",
          "show": "Show",
          "enable": "Enable",
          "disable": "Disable",
          "active": "Active",
          "inactive": "Inactive",
          "online": "Online",
          "offline": "Offline",
          "unknown": "Unknown",
          "yes": "Yes",
          "no": "No",
          "ok": "OK",
          "retry": "Retry",
          "skip": "Skip",
          "continue": "Continue",
          "finish": "Finish",
          "start": "Start",
          "stop": "Stop",
          "pause": "Pause",
          "resume": "Resume"
        },
        "navigation": {
          "dashboard": "Dashboard",
          "servers": "Servers",
          "settings": "Settings",
          "logout": "Logout",
          "profile": "Profile",
          "help": "Help",
          "about": "About"
        },
        "status": {
          "success": "Success",
          "error": "Error",
          "warning": "Warning",
          "info": "Info",
          "loading": "Loading...",
          "pending": "Pending",
          "failed": "Failed",
          "completed": "Completed",
          "cancelled": "Cancelled",
          "timeout": "Timeout",
          "unauthorized": "Unauthorized",
          "forbidden": "Forbidden",
          "notFound": "Not Found",
          "serverError": "Server Error",
          "networkError": "Network Error"
        },
        "time": {
          "now": "Now",
          "today": "Today",
          "yesterday": "Yesterday",
          "tomorrow": "Tomorrow",
          "lastHour": "Last Hour",
          "last24Hours": "Last 24 Hours",
          "last7Days": "Last 7 Days",
          "last30Days": "Last 30 Days",
          "last90Days": "Last 90 Days",
          "lastYear": "Last Year",
          "thisWeek": "This Week",
          "thisMonth": "This Month",
          "thisYear": "This Year"
        }
      },
      "de": {
        "ui": {
          "loading": "Laden...",
          "error": "Fehler",
          "success": "Erfolg",
          "cancel": "Abbrechen",
          "save": "Speichern",
          "delete": "Löschen",
          "edit": "Bearbeiten",
          "add": "Hinzufügen",
          "search": "Suchen",
          "filter": "Filtern",
          "refresh": "Aktualisieren",
          "close": "Schließen",
          "confirm": "Bestätigen",
          "back": "Zurück",
          "next": "Weiter",
          "previous": "Zurück",
          "submit": "Absenden",
          "reset": "Zurücksetzen",
          "clear": "Löschen",
          "select": "Auswählen",
          "selectAll": "Alle auswählen",
          "deselectAll": "Alle abwählen",
          "copy": "Kopieren",
          "export": "Exportieren",
          "import": "Importieren",
          "download": "Herunterladen",
          "upload": "Hochladen",
          "view": "Anzeigen",
          "hide": "Ausblenden",
          "show": "Einblenden",
          "enable": "Aktivieren",
          "disable": "Deaktivieren",
          "active": "Aktiv",
          "inactive": "Inaktiv",
          "online": "Online",
          "offline": "Offline",
          "unknown": "Unbekannt",
          "yes": "Ja",
          "no": "Nein",
          "ok": "OK",
          "retry": "Wiederholen",
          "skip": "Überspringen",
          "continue": "Fortfahren",
          "finish": "Beenden",
          "start": "Starten",
          "stop": "Stoppen",
          "pause": "Pausieren",
          "resume": "Fortsetzen"
        },
        "navigation": {
          "dashboard": "Dashboard",
          "servers": "Server",
          "settings": "Einstellungen",
          "logout": "Abmelden",
          "profile": "Profil",
          "help": "Hilfe",
          "about": "Über"
        },
        "status": {
          "success": "Erfolg",
          "error": "Fehler",
          "warning": "Warnung",
          "info": "Info",
          "loading": "Laden...",
          "pending": "Ausstehend",
          "failed": "Fehlgeschlagen",
          "completed": "Abgeschlossen",
          "cancelled": "Abgebrochen",
          "timeout": "Zeitüberschreitung",
          "unauthorized": "Nicht autorisiert",
          "forbidden": "Verboten",
          "notFound": "Nicht gefunden",
          "serverError": "Serverfehler",
          "networkError": "Netzwerkfehler"
        },
        "time": {
          "now": "Jetzt",
          "today": "Heute",
          "yesterday": "Gestern",
          "tomorrow": "Morgen",
          "lastHour": "Letzte Stunde",
          "last24Hours": "Letzte 24 Stunden",
          "last7Days": "Letzte 7 Tage",
          "last30Days": "Letzte 30 Tage",
          "last90Days": "Letzte 90 Tage",
          "lastYear": "Letztes Jahr",
          "thisWeek": "Diese Woche",
          "thisMonth": "Dieser Monat",
          "thisYear": "Dieses Jahr"
        }
      },
      "fr": {
        "ui": {
          "loading": "Chargement...",
          "error": "Erreur",
          "success": "Succès",
          "cancel": "Annuler",
          "save": "Enregistrer",
          "delete": "Supprimer",
          "edit": "Modifier",
          "add": "Ajouter",
          "search": "Rechercher",
          "filter": "Filtrer",
          "refresh": "Actualiser",
          "close": "Fermer",
          "confirm": "Confirmer",
          "back": "Retour",
          "next": "Suivant",
          "previous": "Précédent",
          "submit": "Soumettre",
          "reset": "Réinitialiser",
          "clear": "Effacer",
          "select": "Sélectionner",
          "selectAll": "Tout sélectionner",
          "deselectAll": "Tout désélectionner",
          "copy": "Copier",
          "export": "Exporter",
          "import": "Importer",
          "download": "Télécharger",
          "upload": "Télécharger",
          "view": "Afficher",
          "hide": "Masquer",
          "show": "Afficher",
          "enable": "Activer",
          "disable": "Désactiver",
          "active": "Actif",
          "inactive": "Inactif",
          "online": "En ligne",
          "offline": "Hors ligne",
          "unknown": "Inconnu",
          "yes": "Oui",
          "no": "Non",
          "ok": "OK",
          "retry": "Réessayer",
          "skip": "Ignorer",
          "continue": "Continuer",
          "finish": "Terminer",
          "start": "Démarrer",
          "stop": "Arrêter",
          "pause": "Pause",
          "resume": "Reprendre"
        },
        "navigation": {
          "dashboard": "Tableau de bord",
          "servers": "Serveurs",
          "settings": "Paramètres",
          "logout": "Déconnexion",
          "profile": "Profil",
          "help": "Aide",
          "about": "À propos"
        },
        "status": {
          "success": "Succès",
          "error": "Erreur",
          "warning": "Avertissement",
          "info": "Info",
          "loading": "Chargement...",
          "pending": "En attente",
          "failed": "Échec",
          "completed": "Terminé",
          "cancelled": "Annulé",
          "timeout": "Délai d'attente dépassé",
          "unauthorized": "Non autorisé",
          "forbidden": "Interdit",
          "notFound": "Non trouvé",
          "serverError": "Erreur serveur",
          "networkError": "Erreur réseau"
        },
        "time": {
          "now": "Maintenant",
          "today": "Aujourd'hui",
          "yesterday": "Hier",
          "tomorrow": "Demain",
          "lastHour": "Dernière heure",
          "last24Hours": "Dernières 24 heures",
          "last7Days": "Derniers 7 jours",
          "last30Days": "Derniers 30 jours",
          "last90Days": "Derniers 90 jours",
          "lastYear": "L'année dernière",
          "thisWeek": "Cette semaine",
          "thisMonth": "Ce mois-ci",
          "thisYear": "Cette année"
        }
      },
      "es": {
        "ui": {
          "loading": "Cargando...",
          "error": "Error",
          "success": "Éxito",
          "cancel": "Cancelar",
          "save": "Guardar",
          "delete": "Eliminar",
          "edit": "Editar",
          "add": "Añadir",
          "search": "Buscar",
          "filter": "Filtrar",
          "refresh": "Actualizar",
          "close": "Cerrar",
          "confirm": "Confirmar",
          "back": "Atrás",
          "next": "Siguiente",
          "previous": "Anterior",
          "submit": "Enviar",
          "reset": "Restablecer",
          "clear": "Limpiar",
          "select": "Seleccionar",
          "selectAll": "Seleccionar todo",
          "deselectAll": "Deseleccionar todo",
          "copy": "Copiar",
          "export": "Exportar",
          "import": "Importar",
          "download": "Descargar",
          "upload": "Subir",
          "view": "Ver",
          "hide": "Ocultar",
          "show": "Mostrar",
          "enable": "Activar",
          "disable": "Desactivar",
          "active": "Activo",
          "inactive": "Inactivo",
          "online": "En línea",
          "offline": "Fuera de línea",
          "unknown": "Desconocido",
          "yes": "Sí",
          "no": "No",
          "ok": "OK",
          "retry": "Reintentar",
          "skip": "Omitir",
          "continue": "Continuar",
          "finish": "Finalizar",
          "start": "Iniciar",
          "stop": "Detener",
          "pause": "Pausar",
          "resume": "Reanudar"
        },
        "navigation": {
          "dashboard": "Panel de control",
          "servers": "Servidores",
          "settings": "Ajustes",
          "logout": "Cerrar sesión",
          "profile": "Perfil",
          "help": "Ayuda",
          "about": "Acerca de"
        },
        "status": {
          "success": "Éxito",
          "error": "Error",
          "warning": "Advertencia",
          "info": "Info",
          "loading": "Cargando...",
          "pending": "Pendiente",
          "failed": "Fallido",
          "completed": "Completado",
          "cancelled": "Cancelado",
          "timeout": "Tiempo de espera agotado",
          "unauthorized": "No autorizado",
          "forbidden": "Prohibido",
          "notFound": "No encontrado",
          "serverError": "Error del servidor",
          "networkError": "Error de red"
        },
        "time": {
          "now": "Ahora",
          "today": "Hoy",
          "yesterday": "Ayer",
          "tomorrow": "Mañana",
          "lastHour": "Última hora",
          "last24Hours": "Últimas 24 horas",
          "last7Days": "Últimos 7 días",
          "last30Days": "Últimos 30 días",
          "last90Days": "Últimos 90 días",
          "lastYear": "El año pasado",
          "thisWeek": "Esta semana",
          "thisMonth": "Este mes",
          "thisYear": "Este año"
        }
      },
      "pt-BR": {
        "ui": {
          "loading": "Carregando...",
          "error": "Erro",
          "success": "Sucesso",
          "cancel": "Cancelar",
          "save": "Salvar",
          "delete": "Excluir",
          "edit": "Editar",
          "add": "Adicionar",
          "search": "Pesquisar",
          "filter": "Filtrar",
          "refresh": "Atualizar",
          "close": "Fechar",
          "confirm": "Confirmar",
          "back": "Voltar",
          "next": "Próximo",
          "previous": "Anterior",
          "submit": "Enviar",
          "reset": "Redefinir",
          "clear": "Limpar",
          "select": "Selecionar",
          "selectAll": "Selecionar todos",
          "deselectAll": "Deselecionar todos",
          "copy": "Copiar",
          "export": "Exportar",
          "import": "Importar",
          "download": "Baixar",
          "upload": "Subir",
          "view": "Visualizar",
          "hide": "Ocultar",
          "show": "Mostrar",
          "enable": "Ativar",
          "disable": "Desativar",
          "active": "Ativo",
          "inactive": "Inativo",
          "online": "Online",
          "offline": "Offline",
          "unknown": "Desconhecido",
          "yes": "Sim",
          "no": "Não",
          "ok": "OK",
          "retry": "Tentar novamente",
          "skip": "Pular",
          "continue": "Continuar",
          "finish": "Finalizar",
          "start": "Iniciar",
          "stop": "Parar",
          "pause": "Pausar",
          "resume": "Retomar"
        },
        "navigation": {
          "dashboard": "Painel",
          "servers": "Servidores",
          "settings": "Configurações",
          "logout": "Sair",
          "profile": "Perfil",
          "help": "Ajuda",
          "about": "Sobre"
        },
        "status": {
          "success": "Sucesso",
          "error": "Erro",
          "warning": "Aviso",
          "info": "Info",
          "loading": "Carregando...",
          "pending": "Pendente",
          "failed": "Falhou",
          "completed": "Concluído",
          "cancelled": "Cancelado",
          "timeout": "Tempo limite excedido",
          "unauthorized": "Não autorizado",
          "forbidden": "Proibido",
          "notFound": "Não encontrado",
          "serverError": "Erro do servidor",
          "networkError": "Erro de rede"
        },
        "time": {
          "now": "Agora",
          "today": "Hoje",
          "yesterday": "Ontem",
          "tomorrow": "Amanhã",
          "lastHour": "Última hora",
          "last24Hours": "Últimas 24 horas",
          "last7Days": "Últimos 7 dias",
          "last30Days": "Últimos 30 dias",
          "last90Days": "Últimos 90 dias",
          "lastYear": "Último ano",
          "thisWeek": "Esta semana",
          "thisMonth": "Este mês",
          "thisYear": "Este ano"
        }
      }
    }
  },
  "localIds": [
    "common::local::src/app/[locale]/content/common.content.ts"
  ]
} as const;
