/* eslint-disable */
export default {
  "key": "dashboard-table",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "servers": {
          "title": "Servers",
          "searchPlaceholder": "Search servers...",
          "filterByStatus": "Filter by Status",
          "filterByType": "Filter by Type",
          "showOnlineOnly": "Show Online Only",
          "showOfflineOnly": "Show Offline Only",
          "showAll": "Show All",
          "noServersFound": "No servers found",
          "serverName": "Server Name",
          "status": "Status",
          "lastBackup": "Last Backup",
          "nextBackup": "Next Backup",
          "actions": "Actions",
          "viewDetails": "View Details",
          "editServer": "Edit Server",
          "deleteServer": "Delete Server",
          "testConnection": "Test Connection",
          "forceBackup": "Force Backup",
          "backupName": "Backup Name",
          "overdueNextRun": "Overdue / Next run",
          "availableVersions": "Available Versions",
          "backupCount": "Backup Count",
          "lastBackupDate": "Last Backup Date",
          "lastBackupStatus": "Last Backup Status",
          "settingsActions": "Settings/Actions",
          "collectDataMessage": "Collect data for your first server by clicking on",
          "collectBackupsLogs": "(Collect backups logs)"
        },
        "backups": {
          "title": "Backups",
          "searchPlaceholder": "Search backups...",
          "filterByStatus": "Filter by Status",
          "filterByServer": "Filter by Server",
          "filterByDate": "Filter by Date",
          "showAll": "Show All",
          "showSuccessful": "Show Successful",
          "showFailed": "Show Failed",
          "showPending": "Show Pending",
          "noBackupsFound": "No backups found",
          "backupId": "Backup ID",
          "serverName": "Server Name",
          "startTime": "Start Time",
          "endTime": "End Time",
          "duration": "Duration",
          "status": "Status",
          "size": "Size",
          "files": "Files",
          "errors": "Errors",
          "warnings": "Warnings",
          "viewDetails": "View Details",
          "downloadLog": "Download Log",
          "retryBackup": "Retry Backup"
        },
        "nextRun": "Next run",
        "checked": "Checked:",
        "lastBackupLabel": "Last backup:",
        "expectedBackup": "Expected backup:",
        "lastNotification": "Last notification:",
        "overdueConfiguration": "Overdue configuration",
        "overdueConfig": "Overdue Config",
        "overdueDetails": "Overdue Details",
        "off": "Off",
        "lastBackup": "Last Backup",
        "settings": "Settings"
      },
      "de": {
        "servers": {
          "title": "Server",
          "searchPlaceholder": "Server suchen...",
          "filterByStatus": "Nach Status filtern",
          "filterByType": "Nach Typ filtern",
          "showOnlineOnly": "Nur Online anzeigen",
          "showOfflineOnly": "Nur Offline anzeigen",
          "showAll": "Alle anzeigen",
          "noServersFound": "Keine Server gefunden",
          "serverName": "Servername",
          "status": "Status",
          "lastBackup": "Letzte Sicherung",
          "nextBackup": "Nächste Sicherung",
          "actions": "Aktionen",
          "viewDetails": "Details anzeigen",
          "editServer": "Server bearbeiten",
          "deleteServer": "Server löschen",
          "testConnection": "Verbindung testen",
          "forceBackup": "Sicherung erzwingen",
          "backupName": "Sicherungsname",
          "overdueNextRun": "Überfällig / Nächster Lauf",
          "availableVersions": "Verfügbare Versionen",
          "backupCount": "Anzahl der Sicherungen",
          "lastBackupDate": "Datum der letzten Sicherung",
          "lastBackupStatus": "Status der letzten Sicherung",
          "settingsActions": "Einstellungen/Aktionen",
          "collectDataMessage": "Sammeln Sie Daten für Ihren ersten Server, indem Sie auf",
          "collectBackupsLogs": "(Sicherungsprotokolle sammeln)"
        },
        "backups": {
          "title": "Sicherungen",
          "searchPlaceholder": "Sicherungen suchen...",
          "filterByStatus": "Nach Status filtern",
          "filterByServer": "Nach Server filtern",
          "filterByDate": "Nach Datum filtern",
          "showAll": "Alle anzeigen",
          "showSuccessful": "Erfolgreiche anzeigen",
          "showFailed": "Fehlgeschlagene anzeigen",
          "showPending": "Ausstehende anzeigen",
          "noBackupsFound": "Keine Sicherungen gefunden",
          "backupId": "Sicherungs-ID",
          "serverName": "Servername",
          "startTime": "Startzeit",
          "endTime": "Endzeit",
          "duration": "Dauer",
          "status": "Status",
          "size": "Größe",
          "files": "Dateien",
          "errors": "Fehler",
          "warnings": "Warnungen",
          "viewDetails": "Details anzeigen",
          "downloadLog": "Log herunterladen",
          "retryBackup": "Sicherung wiederholen"
        },
        "nextRun": "Nächster Lauf",
        "checked": "Geprüft:",
        "lastBackupLabel": "Letzte Sicherung:",
        "expectedBackup": "Erwartete Sicherung:",
        "lastNotification": "Letzte Benachrichtigung:",
        "overdueConfiguration": "Überfälligkeitskonfiguration",
        "overdueConfig": "Überfälligkeits-Konfig",
        "overdueDetails": "Überfälligkeitsdetails",
        "off": "Aus",
        "lastBackup": "Letzte Sicherung",
        "settings": "Einstellungen"
      },
      "fr": {
        "servers": {
          "title": "Serveurs",
          "searchPlaceholder": "Rechercher des serveurs...",
          "filterByStatus": "Filtrer par statut",
          "filterByType": "Filtrer par type",
          "showOnlineOnly": "Afficher uniquement en ligne",
          "showOfflineOnly": "Afficher uniquement hors ligne",
          "showAll": "Afficher tout",
          "noServersFound": "Aucun serveur trouvé",
          "serverName": "Nom du serveur",
          "status": "Statut",
          "lastBackup": "Dernière sauvegarde",
          "nextBackup": "Prochaine sauvegarde",
          "actions": "Actions",
          "viewDetails": "Voir les détails",
          "editServer": "Modifier le serveur",
          "deleteServer": "Supprimer le serveur",
          "testConnection": "Tester la connexion",
          "forceBackup": "Forcer la sauvegarde",
          "backupName": "Nom de sauvegarde",
          "overdueNextRun": "En retard / Prochaine exécution",
          "availableVersions": "Versions disponibles",
          "backupCount": "Nombre de sauvegardes",
          "lastBackupDate": "Date de la dernière sauvegarde",
          "lastBackupStatus": "Statut de la dernière sauvegarde",
          "settingsActions": "Paramètres/Actions",
          "collectDataMessage": "Collectez des données pour votre premier serveur en cliquant sur",
          "collectBackupsLogs": "(Collecter les journaux de sauvegarde)"
        },
        "backups": {
          "title": "Sauvegardes",
          "searchPlaceholder": "Rechercher des sauvegardes...",
          "filterByStatus": "Filtrer par statut",
          "filterByServer": "Filtrer par serveur",
          "filterByDate": "Filtrer par date",
          "showAll": "Afficher tout",
          "showSuccessful": "Afficher les réussis",
          "showFailed": "Afficher les échoués",
          "showPending": "Afficher en attente",
          "noBackupsFound": "Aucune sauvegarde trouvée",
          "backupId": "ID de sauvegarde",
          "serverName": "Nom du serveur",
          "startTime": "Heure de début",
          "endTime": "Heure de fin",
          "duration": "Durée",
          "status": "Statut",
          "size": "Taille",
          "files": "Fichiers",
          "errors": "Erreurs",
          "warnings": "Avertissements",
          "viewDetails": "Voir les détails",
          "downloadLog": "Télécharger le journal",
          "retryBackup": "Réessayer la sauvegarde"
        },
        "nextRun": "Prochaine exécution",
        "checked": "Vérifié:",
        "lastBackupLabel": "Dernière sauvegarde:",
        "expectedBackup": "Sauvegarde attendue:",
        "lastNotification": "Dernière notification:",
        "overdueConfiguration": "Configuration des retards",
        "overdueConfig": "Config des retards",
        "overdueDetails": "Détails des retards",
        "off": "Désactivé",
        "lastBackup": "Dernière sauvegarde",
        "settings": "Paramètres"
      },
      "es": {
        "servers": {
          "title": "Servidores",
          "searchPlaceholder": "Buscar servidores...",
          "filterByStatus": "Filtrar por estado",
          "filterByType": "Filtrar por tipo",
          "showOnlineOnly": "Mostrar solo en línea",
          "showOfflineOnly": "Mostrar solo fuera de línea",
          "showAll": "Mostrar todo",
          "noServersFound": "No se encontraron servidores",
          "serverName": "Nombre del servidor",
          "status": "Estado",
          "lastBackup": "Último respaldo",
          "nextBackup": "Próximo respaldo",
          "actions": "Acciones",
          "viewDetails": "Ver detalles",
          "editServer": "Editar servidor",
          "deleteServer": "Eliminar servidor",
          "testConnection": "Probar conexión",
          "forceBackup": "Forzar respaldo",
          "backupName": "Nombre de respaldo",
          "overdueNextRun": "Vencido / Próxima ejecución",
          "availableVersions": "Versiones disponibles",
          "backupCount": "Cantidad de respaldos",
          "lastBackupDate": "Fecha del último respaldo",
          "lastBackupStatus": "Estado del último respaldo",
          "settingsActions": "Configuración/Acciones",
          "collectDataMessage": "Recopile datos para su primer servidor haciendo clic en",
          "collectBackupsLogs": "(Recopilar registros de respaldo)"
        },
        "backups": {
          "title": "Respaldos",
          "searchPlaceholder": "Buscar respaldos...",
          "filterByStatus": "Filtrar por estado",
          "filterByServer": "Filtrar por servidor",
          "filterByDate": "Filtrar por fecha",
          "showAll": "Mostrar todo",
          "showSuccessful": "Mostrar exitosos",
          "showFailed": "Mostrar fallidos",
          "showPending": "Mostrar pendientes",
          "noBackupsFound": "No se encontraron respaldos",
          "backupId": "ID de respaldo",
          "serverName": "Nombre del servidor",
          "startTime": "Hora de inicio",
          "endTime": "Hora de fin",
          "duration": "Duración",
          "status": "Estado",
          "size": "Tamaño",
          "files": "Archivos",
          "errors": "Errores",
          "warnings": "Advertencias",
          "viewDetails": "Ver detalles",
          "downloadLog": "Descargar registro",
          "retryBackup": "Reintentar respaldo"
        },
        "nextRun": "Próxima ejecución",
        "checked": "Verificado:",
        "lastBackupLabel": "Último respaldo:",
        "expectedBackup": "Respaldo esperado:",
        "lastNotification": "Última notificación:",
        "overdueConfiguration": "Configuración de vencimientos",
        "overdueConfig": "Config de vencimientos",
        "overdueDetails": "Detalles de vencimientos",
        "off": "Desactivado",
        "lastBackup": "Último respaldo",
        "settings": "Configuración"
      },
      "pt-BR": {
        "servers": {
          "title": "Servidores",
          "searchPlaceholder": "Pesquisar servidores...",
          "filterByStatus": "Filtrar por status",
          "filterByType": "Filtrar por tipo",
          "showOnlineOnly": "Mostrar apenas online",
          "showOfflineOnly": "Mostrar apenas offline",
          "showAll": "Mostrar todos",
          "noServersFound": "Nenhum servidor encontrado",
          "serverName": "Nome do servidor",
          "status": "Status",
          "lastBackup": "Último backup",
          "nextBackup": "Próximo backup",
          "actions": "Ações",
          "viewDetails": "Ver detalhes",
          "editServer": "Editar servidor",
          "deleteServer": "Excluir servidor",
          "testConnection": "Testar conexão",
          "forceBackup": "Forçar backup",
          "backupName": "Nome do backup",
          "overdueNextRun": "Atrasado / Próxima execução",
          "availableVersions": "Versões disponíveis",
          "backupCount": "Contagem de backups",
          "lastBackupDate": "Data do último backup",
          "lastBackupStatus": "Status do último backup",
          "settingsActions": "Configurações/Ações",
          "collectDataMessage": "Colete dados para seu primeiro servidor clicando em",
          "collectBackupsLogs": "(Coletar logs de backup)"
        },
        "backups": {
          "title": "Backups",
          "searchPlaceholder": "Pesquisar backups...",
          "filterByStatus": "Filtrar por status",
          "filterByServer": "Filtrar por servidor",
          "filterByDate": "Filtrar por data",
          "showAll": "Mostrar todos",
          "showSuccessful": "Mostrar bem-sucedidos",
          "showFailed": "Mostrar falhados",
          "showPending": "Mostrar pendentes",
          "noBackupsFound": "Nenhum backup encontrado",
          "backupId": "ID do backup",
          "serverName": "Nome do servidor",
          "startTime": "Hora de início",
          "endTime": "Hora de término",
          "duration": "Duração",
          "status": "Status",
          "size": "Tamanho",
          "files": "Arquivos",
          "errors": "Erros",
          "warnings": "Avisos",
          "viewDetails": "Ver detalhes",
          "downloadLog": "Baixar log",
          "retryBackup": "Tentar backup novamente"
        },
        "nextRun": "Próxima execução",
        "checked": "Verificado:",
        "lastBackupLabel": "Último backup:",
        "expectedBackup": "Backup esperado:",
        "lastNotification": "Última notificação:",
        "overdueConfiguration": "Configuração de atrasos",
        "overdueConfig": "Config de atrasos",
        "overdueDetails": "Detalhes de atrasos",
        "off": "Desativado",
        "lastBackup": "Último backup",
        "settings": "Configurações"
      }
    }
  },
  "localIds": [
    "dashboard-table::local::src/components/dashboard/dashboard-table.content.ts"
  ]
} as const;
