/* eslint-disable */
export default {
  "key": "overview-charts-panel",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "backupHistory": "Backup History",
        "successRate": "Success Rate",
        "backupSize": "Backup Size",
        "fileSize": "File Size",
        "storageSize": "Storage Size",
        "backupDuration": "Backup Duration",
        "serverStatus": "Server Status",
        "last7Days": "Last 7 Days",
        "last30Days": "Last 30 Days",
        "last90Days": "Last 90 Days",
        "thisYear": "This Year",
        "successful": "Successful",
        "failed": "Failed",
        "total": "Total",
        "percentage": "Percentage",
        "average": "Average",
        "minimum": "Minimum",
        "maximum": "Maximum",
        "allBackups": " (all backups)",
        "allServersAndBackups": "All Servers & Backups",
        "loadingChartData": "Loading chart data...",
        "errorLoadingChartData": "Error loading chart data",
        "noDataAvailable": "No data available"
      },
      "de": {
        "backupHistory": "Sicherungsverlauf",
        "successRate": "Erfolgsquote",
        "backupSize": "Sicherungsgröße",
        "fileSize": "Dateigröße",
        "storageSize": "Speichergröße",
        "backupDuration": "Sicherungsdauer",
        "serverStatus": "Serverstatus",
        "last7Days": "Letzte 7 Tage",
        "last30Days": "Letzte 30 Tage",
        "last90Days": "Letzte 90 Tage",
        "thisYear": "Dieses Jahr",
        "successful": "Erfolgreich",
        "failed": "Fehlgeschlagen",
        "total": "Gesamt",
        "percentage": "Prozentsatz",
        "average": "Durchschnitt",
        "minimum": "Minimum",
        "maximum": "Maximum",
        "allBackups": " (alle Sicherungen)",
        "allServersAndBackups": "Alle Server & Sicherungen",
        "loadingChartData": "Lade Diagrammdaten...",
        "errorLoadingChartData": "Fehler beim Laden der Diagrammdaten",
        "noDataAvailable": "Keine Daten verfügbar"
      },
      "fr": {
        "backupHistory": "Historique des sauvegardes",
        "successRate": "Taux de réussite",
        "backupSize": "Taille de sauvegarde",
        "fileSize": "Taille de fichier",
        "storageSize": "Taille de stockage",
        "backupDuration": "Durée de sauvegarde",
        "serverStatus": "Statut du serveur",
        "last7Days": "Derniers 7 jours",
        "last30Days": "Derniers 30 jours",
        "last90Days": "Derniers 90 jours",
        "thisYear": "Cette année",
        "successful": "Réussi",
        "failed": "Échoué",
        "total": "Total",
        "percentage": "Pourcentage",
        "average": "Moyenne",
        "minimum": "Minimum",
        "maximum": "Maximum",
        "allBackups": " (toutes les sauvegardes)",
        "allServersAndBackups": "Tous les serveurs et sauvegardes",
        "loadingChartData": "Chargement des données du graphique...",
        "errorLoadingChartData": "Erreur lors du chargement des données du graphique",
        "noDataAvailable": "Aucune donnée disponible"
      },
      "es": {
        "backupHistory": "Historial de respaldos",
        "successRate": "Tasa de éxito",
        "backupSize": "Tamaño de respaldo",
        "fileSize": "Tamaño de archivo",
        "storageSize": "Tamaño de almacenamiento",
        "backupDuration": "Duración de respaldo",
        "serverStatus": "Estado del servidor",
        "last7Days": "Últimos 7 días",
        "last30Days": "Últimos 30 días",
        "last90Days": "Últimos 90 días",
        "thisYear": "Este año",
        "successful": "Exitoso",
        "failed": "Fallido",
        "total": "Total",
        "percentage": "Porcentaje",
        "average": "Promedio",
        "minimum": "Mínimo",
        "maximum": "Máximo",
        "allBackups": " (todos los respaldos)",
        "allServersAndBackups": "Todos los servidores y respaldos",
        "loadingChartData": "Cargando datos del gráfico...",
        "errorLoadingChartData": "Error al cargar datos del gráfico",
        "noDataAvailable": "No hay datos disponibles"
      },
      "pt-BR": {
        "backupHistory": "Histórico de backups",
        "successRate": "Taxa de sucesso",
        "backupSize": "Tamanho do backup",
        "fileSize": "Tamanho do arquivo",
        "storageSize": "Tamanho de armazenamento",
        "backupDuration": "Duração do backup",
        "serverStatus": "Status do servidor",
        "last7Days": "Últimos 7 dias",
        "last30Days": "Últimos 30 dias",
        "last90Days": "Últimos 90 dias",
        "thisYear": "Este ano",
        "successful": "Bem-sucedido",
        "failed": "Falhado",
        "total": "Total",
        "percentage": "Percentual",
        "average": "Média",
        "minimum": "Mínimo",
        "maximum": "Máximo",
        "allBackups": " (todos os backups)",
        "allServersAndBackups": "Todos os servidores e backups",
        "loadingChartData": "Carregando dados do gráfico...",
        "errorLoadingChartData": "Erro ao carregar dados do gráfico",
        "noDataAvailable": "Nenhum dado disponível"
      }
    }
  },
  "localIds": [
    "overview-charts-panel::local::src/components/dashboard/overview-charts-panel.content.ts"
  ]
} as const;
