/* eslint-disable */
export default {
  "key": "overview-cards",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "totalServers": "Total Servers",
        "onlineServers": "Online Servers",
        "offlineServers": "Offline Servers",
        "totalBackups": "Total Backups",
        "successfulBackups": "Successful Backups",
        "failedBackups": "Failed Backups",
        "last24Hours": "Last 24 Hours",
        "last7Days": "Last 7 Days",
        "last30Days": "Last 30 Days",
        "files": "Files",
        "size": "Size",
        "storage": "Storage",
        "last": "Last",
        "backups": "Backups:",
        "noBackupJobsAvailable": "No backup jobs available",
        "noServersFound": "No servers found",
        "collectDataMessage": "Collect data for your first server by clicking on",
        "collectBackupsLogs": "(Collect backups logs)",
        "sortServerName": "Server name (a-z)",
        "sortStatus": "Status (error>warnings>success)",
        "sortLastBackup": "Last backup received (new>old)"
      },
      "de": {
        "totalServers": "Gesamtserver",
        "onlineServers": "Server online",
        "offlineServers": "Server offline",
        "totalBackups": "Gesamtsicherungen",
        "successfulBackups": "Erfolgreiche Sicherungen",
        "failedBackups": "Fehlgeschlagene Sicherungen",
        "last24Hours": "Letzte 24 Stunden",
        "last7Days": "Letzte 7 Tage",
        "last30Days": "Letzte 30 Tage",
        "files": "Dateien",
        "size": "Größe",
        "storage": "Speicher",
        "last": "Letzte",
        "backups": "Sicherungen:",
        "noBackupJobsAvailable": "Keine Backup-Jobs verfügbar",
        "noServersFound": "Keine Server gefunden",
        "collectDataMessage": "Sammeln Sie Daten für Ihren ersten Server, indem Sie auf",
        "collectBackupsLogs": "(Sicherungsprotokolle sammeln)",
        "sortServerName": "Servername (a-z)",
        "sortStatus": "Status (Fehler>Warnungen>Erfolg)",
        "sortLastBackup": "Letzte Sicherung erhalten (neu>alt)"
      },
      "fr": {
        "totalServers": "Total des serveurs",
        "onlineServers": "Serveurs en ligne",
        "offlineServers": "Serveurs hors ligne",
        "totalBackups": "Total des sauvegardes",
        "successfulBackups": "Sauvegardes réussies",
        "failedBackups": "Sauvegardes échouées",
        "last24Hours": "Dernières 24 heures",
        "last7Days": "Derniers 7 jours",
        "last30Days": "Derniers 30 jours",
        "files": "Fichiers",
        "size": "Taille",
        "storage": "Stockage",
        "last": "Dernière",
        "backups": "Sauvegardes:",
        "noBackupJobsAvailable": "Aucune tâche de sauvegarde disponible",
        "noServersFound": "Aucun serveur trouvé",
        "collectDataMessage": "Collectez des données pour votre premier serveur en cliquant sur",
        "collectBackupsLogs": "(Collecter les journaux de sauvegarde)",
        "sortServerName": "Nom du serveur (a-z)",
        "sortStatus": "Statut (erreur>avertissements>succès)",
        "sortLastBackup": "Dernière sauvegarde reçue (nouveau>ancien)"
      },
      "es": {
        "totalServers": "Servidores totales",
        "onlineServers": "Servidores en línea",
        "offlineServers": "Servidores fuera de línea",
        "totalBackups": "Respaldos totales",
        "successfulBackups": "Respaldos exitosos",
        "failedBackups": "Respaldos fallidos",
        "last24Hours": "Últimas 24 horas",
        "last7Days": "Últimos 7 días",
        "last30Days": "Últimos 30 días",
        "files": "Archivos",
        "size": "Tamaño",
        "storage": "Almacenamiento",
        "last": "Última",
        "backups": "Respaldos:",
        "noBackupJobsAvailable": "No hay trabajos de respaldo disponibles",
        "noServersFound": "No se encontraron servidores",
        "collectDataMessage": "Recopile datos para su primer servidor haciendo clic en",
        "collectBackupsLogs": "(Recopilar registros de respaldo)",
        "sortServerName": "Nombre del servidor (a-z)",
        "sortStatus": "Estado (error>advertencias>éxito)",
        "sortLastBackup": "Último respaldo recibido (nuevo>antiguo)"
      },
      "pt-BR": {
        "totalServers": "Total de servidores",
        "onlineServers": "Servidores online",
        "offlineServers": "Servidores offline",
        "totalBackups": "Total de backups",
        "successfulBackups": "Backups bem-sucedidos",
        "failedBackups": "Backups falharam",
        "last24Hours": "Últimas 24 horas",
        "last7Days": "Últimos 7 dias",
        "last30Days": "Últimos 30 dias",
        "files": "Arquivos",
        "size": "Tamanho",
        "storage": "Armazenamento",
        "last": "Última",
        "backups": "Backups:",
        "noBackupJobsAvailable": "Nenhum trabalho de backup disponível",
        "noServersFound": "Nenhum servidor encontrado",
        "collectDataMessage": "Colete dados para seu primeiro servidor clicando em",
        "collectBackupsLogs": "(Coletar logs de backup)",
        "sortServerName": "Nome do servidor (a-z)",
        "sortStatus": "Status (erro>avisos>sucesso)",
        "sortLastBackup": "Último backup recebido (novo>antigo)"
      }
    }
  },
  "localIds": [
    "overview-cards::local::src/components/dashboard/overview-cards.content.ts"
  ]
} as const;
