/* eslint-disable */
export default {
  "key": "overdue-monitoring-form",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "Overdue Backup Monitoring",
        "description": "Configure monitoring for overdue backups",
        "overdueMonitoring": "Overdue Monitoring",
        "noServersWithBackups": "No servers with backups found in the database",
        "noServersRegisteredYet": "No servers with backups have been registered yet. Add some backup data first to see overdue monitoring settings.",
        "configureOverdueMonitoring": "Configure Overdue Monitoring",
        "configureOverdueMonitoringDescription": "Configure overdue backup monitoring settings for each backup. Enable/disable overdue backup monitoring, set the timeout period and notification frequency.",
        "serverName": "Server Name",
        "backupName": "Backup Name",
        "nextRun": "Next Run",
        "overdueBackupMonitoring": "Overdue Backup Monitoring",
        "expectedBackupInterval": "Expected Backup Interval",
        "unit": "Unit",
        "allowedDays": "Allowed Days",
        "enabled": "Enabled",
        "disabled": "Disabled",
        "custom": "Custom",
        "minutes": "Minute(s)",
        "minutesShort": "Min(s)",
        "hours": "Hour(s)",
        "days": "Day(s)",
        "weeks": "Week(s)",
        "months": "Month(s)",
        "years": "Year(s)",
        "notSet": "Not set",
        "customIntervalPlaceholder": "1D2h30m",
        "lastBackup": "Last Backup:",
        "saveOverdueMonitoringSettings": "Save Overdue Monitoring Settings",
        "saving": "Saving...",
        "downloadCSV": "Download CSV",
        "csv": "CSV",
        "checkNow": "Check now",
        "check": "Check",
        "checking": "Checking...",
        "resetNotifications": "Reset notifications",
        "resetting": "Resetting...",
        "overdueTolerance": "Overdue tolerance:",
        "tolerance": "Tolerance:",
        "overdueMonitoringInterval": "Overdue monitoring interval:",
        "monitoringInterval": "Monitoring interval:",
        "interval": "Interval:",
        "notificationFrequency": "Notification frequency:",
        "notificationFreq": "Notification freq:",
        "frequency": "Frequency:",
        "noTolerance": "No tolerance",
        "tolerance5min": "5 min",
        "tolerance15min": "15 min",
        "tolerance30min": "30 min",
        "tolerance1h": "1 hour",
        "tolerance2h": "2 hours",
        "tolerance4h": "4 hours",
        "tolerance6h": "6 hours",
        "tolerance12h": "12 hours",
        "tolerance1d": "1 day",
        "oneTime": "One time",
        "everyDay": "Every day",
        "everyWeek": "Every week",
        "everyMonth": "Every month",
        "overdueBackupCheckComplete": "Overdue Backup Check Complete",
        "checkedBackupsFoundOverdue": "Checked {checked} backups, found {overdue} overdue backups, sent {notifications} notifications.",
        "failedToRunOverdueBackupCheck": "Failed to run overdue backup check",
        "overdueBackupCheckIntervalUpdated": "Overdue backup check interval updated successfully",
        "configurationSavedCronNotRunning": "Configuration saved successfully. Note: Cron service is not running - start it with 'npm run cron:start' to enable scheduled tasks.",
        "failedToUpdateOverdueBackupCheckInterval": "Failed to update overdue backup check interval",
        "overdueMonitoringSettingsSaved": "Overdue monitoring settings saved successfully",
        "failedToSaveOverdueMonitoringSettings": "Failed to save overdue monitoring settings",
        "overdueBackupNotificationsReset": "Overdue backup notifications have been reset",
        "failedToResetOverdueBackupNotifications": "Failed to reset overdue backup notifications",
        "csvFileDownloadedSuccessfully": "CSV file downloaded successfully",
        "failedToGenerateCsvFile": "Failed to generate CSV file",
        "overdueToleranceUpdatedSuccessfully": "Overdue tolerance updated successfully.",
        "failedToUpdateOverdueTolerance": "Failed to update overdue tolerance",
        "notificationFrequencyUpdated": "Notification frequency updated.",
        "failedToUpdateNotificationFrequency": "Failed to update notification frequency",
        "startingCollection": "Starting Collection",
        "collectingBackupLogs": "Collecting backup logs from all configured servers...",
        "invalidIntervalFormat": "Invalid interval format",
        "pleaseEnterValidPositiveNumber": "Please enter a valid positive number",
        "csvGeneratedAt": "CSV Generated At",
        "csvServerName": "Server Name",
        "csvServerId": "Server ID",
        "csvBackupName": "Backup Name",
        "csvLastBackupCfg": "Last Backup (cfg)",
        "csvLastBackupCfgWeekday": "Last Backup (cfg) Weekday",
        "csvLastBackupDb": "Last Backup (DB)",
        "csvNextRun": "Next Run",
        "csvNextRunWeekday": "Next Run Weekday",
        "csvIsOverdue": "Is Overdue",
        "csvMonitoringEnabled": "Monitoring Enabled",
        "csvExpectedInterval": "Expected Interval",
        "csvAllowedWeekdays": "Allowed Weekdays",
        "noPermissionToModifySetting": "You do not have permission to modify this setting. Only administrators can change configurations.",
        "noPermissionToRunOverdueBackupChecks": "You do not have permission to run overdue backup checks. Only administrators can perform this action.",
        "selectTolerance": "Select tolerance",
        "loading": "Loading...",
        "downloadBackupMonitoringDataAsCsv": "Download backup monitoring data as CSV"
      },
      "de": {
        "title": "Überwachung überfälliger Sicherungen",
        "description": "Überwachung für überfällige Sicherungen konfigurieren",
        "overdueMonitoring": "Überwachung überfälliger Sicherungen",
        "noServersWithBackups": "Keine Server mit Sicherungen in der Datenbank gefunden",
        "noServersRegisteredYet": "Es wurden noch keine Server mit Sicherungen registriert. Fügen Sie zuerst einige Sicherungsdaten hinzu, um die Einstellungen für die Überwachung überfälliger Sicherungen zu sehen.",
        "configureOverdueMonitoring": "Überwachung überfälliger Sicherungen konfigurieren",
        "configureOverdueMonitoringDescription": "Konfigurieren Sie die Einstellungen für die Überwachung überfälliger Sicherungen für jede Sicherung. Aktivieren/Deaktivieren Sie die Überwachung überfälliger Sicherungen, legen Sie die Timeout-Periode und die Benachrichtigungshäufigkeit fest.",
        "serverName": "Servername",
        "backupName": "Sicherungsname",
        "nextRun": "Nächster Lauf",
        "overdueBackupMonitoring": "Überwachung überfälliger Sicherungen",
        "expectedBackupInterval": "Erwartetes Sicherungsintervall",
        "unit": "Einheit",
        "allowedDays": "Erlaubte Tage",
        "enabled": "Aktiviert",
        "disabled": "Deaktiviert",
        "custom": "Benutzerdefiniert",
        "minutes": "Minute(n)",
        "minutesShort": "Min(n)",
        "hours": "Stunde(n)",
        "days": "Tag(e)",
        "weeks": "Woche(n)",
        "months": "Monat(e)",
        "years": "Jahr(e)",
        "notSet": "Nicht gesetzt",
        "customIntervalPlaceholder": "1D2h30m",
        "lastBackup": "Letzte Sicherung:",
        "saveOverdueMonitoringSettings": "Einstellungen für Überwachung überfälliger Sicherungen speichern",
        "saving": "Speichern...",
        "downloadCSV": "CSV herunterladen",
        "csv": "CSV",
        "checkNow": "Jetzt prüfen",
        "check": "Prüfen",
        "checking": "Prüfe...",
        "resetNotifications": "Benachrichtigungen zurücksetzen",
        "resetting": "Zurücksetzen...",
        "overdueTolerance": "Überfälligkeitstoleranz:",
        "tolerance": "Toleranz:",
        "overdueMonitoringInterval": "Überwachungsintervall für überfällige Sicherungen:",
        "monitoringInterval": "Überwachungsintervall:",
        "interval": "Intervall:",
        "notificationFrequency": "Benachrichtigungshäufigkeit:",
        "notificationFreq": "Benachrichtigungsfreq:",
        "frequency": "Häufigkeit:",
        "noTolerance": "Keine Toleranz",
        "tolerance5min": "5 Min",
        "tolerance15min": "15 Min",
        "tolerance30min": "30 Min",
        "tolerance1h": "1 Stunde",
        "tolerance2h": "2 Stunden",
        "tolerance4h": "4 Stunden",
        "tolerance6h": "6 Stunden",
        "tolerance12h": "12 Stunden",
        "tolerance1d": "1 Tag",
        "oneTime": "Einmalig",
        "everyDay": "Jeden Tag",
        "everyWeek": "Jede Woche",
        "everyMonth": "Jeden Monat",
        "overdueBackupCheckComplete": "Prüfung überfälliger Sicherungen abgeschlossen",
        "checkedBackupsFoundOverdue": "{checked} Sicherungen geprüft, {overdue} überfällige Sicherungen gefunden, {notifications} Benachrichtigungen gesendet.",
        "failedToRunOverdueBackupCheck": "Fehler beim Ausführen der Prüfung überfälliger Sicherungen",
        "overdueBackupCheckIntervalUpdated": "Intervall für Prüfung überfälliger Sicherungen erfolgreich aktualisiert",
        "configurationSavedCronNotRunning": "Konfiguration erfolgreich gespeichert. Hinweis: Cron-Service läuft nicht - starten Sie ihn mit 'npm run cron:start', um geplante Aufgaben zu aktivieren.",
        "failedToUpdateOverdueBackupCheckInterval": "Fehler beim Aktualisieren des Intervalls für Prüfung überfälliger Sicherungen",
        "overdueMonitoringSettingsSaved": "Einstellungen für Überwachung überfälliger Sicherungen erfolgreich gespeichert",
        "failedToSaveOverdueMonitoringSettings": "Fehler beim Speichern der Einstellungen für Überwachung überfälliger Sicherungen",
        "overdueBackupNotificationsReset": "Benachrichtigungen über überfällige Sicherungen wurden zurückgesetzt",
        "failedToResetOverdueBackupNotifications": "Fehler beim Zurücksetzen der Benachrichtigungen über überfällige Sicherungen",
        "csvFileDownloadedSuccessfully": "CSV-Datei erfolgreich heruntergeladen",
        "failedToGenerateCsvFile": "Fehler beim Generieren der CSV-Datei",
        "overdueToleranceUpdatedSuccessfully": "Überfälligkeitstoleranz erfolgreich aktualisiert.",
        "failedToUpdateOverdueTolerance": "Fehler beim Aktualisieren der Überfälligkeitstoleranz",
        "notificationFrequencyUpdated": "Benachrichtigungshäufigkeit aktualisiert.",
        "failedToUpdateNotificationFrequency": "Fehler beim Aktualisieren der Benachrichtigungshäufigkeit",
        "startingCollection": "Sammlung starten",
        "collectingBackupLogs": "Sammle Backup-Protokolle von allen konfigurierten Servern...",
        "invalidIntervalFormat": "Ungültiges Intervallformat",
        "pleaseEnterValidPositiveNumber": "Bitte geben Sie eine gültige positive Zahl ein",
        "csvGeneratedAt": "CSV generiert am",
        "csvServerName": "Servername",
        "csvServerId": "Server-ID",
        "csvBackupName": "Sicherungsname",
        "csvLastBackupCfg": "Letzte Sicherung (cfg)",
        "csvLastBackupCfgWeekday": "Wochentag der letzten Sicherung (cfg)",
        "csvLastBackupDb": "Letzte Sicherung (DB)",
        "csvNextRun": "Nächster Lauf",
        "csvNextRunWeekday": "Wochentag des nächsten Laufs",
        "csvIsOverdue": "Ist überfällig",
        "csvMonitoringEnabled": "Überwachung aktiviert",
        "csvExpectedInterval": "Erwartetes Intervall",
        "csvAllowedWeekdays": "Erlaubte Wochentage",
        "noPermissionToModifySetting": "Sie haben keine Berechtigung, diese Einstellung zu ändern. Nur Administratoren können Konfigurationen ändern.",
        "noPermissionToRunOverdueBackupChecks": "Sie haben keine Berechtigung, Prüfungen überfälliger Sicherungen auszuführen. Nur Administratoren können diese Aktion ausführen.",
        "selectTolerance": "Toleranz auswählen",
        "loading": "Laden...",
        "downloadBackupMonitoringDataAsCsv": "Backup-Überwachungsdaten als CSV herunterladen"
      },
      "fr": {
        "title": "Surveillance des sauvegardes en retard",
        "description": "Configurer la surveillance des sauvegardes en retard",
        "overdueMonitoring": "Surveillance des sauvegardes en retard",
        "noServersWithBackups": "Aucun serveur avec sauvegardes trouvé dans la base de données",
        "noServersRegisteredYet": "Aucun serveur avec sauvegardes n'a encore été enregistré. Ajoutez d'abord quelques données de sauvegarde pour voir les paramètres de surveillance des sauvegardes en retard.",
        "configureOverdueMonitoring": "Configurer la surveillance des sauvegardes en retard",
        "configureOverdueMonitoringDescription": "Configurez les paramètres de surveillance des sauvegardes en retard pour chaque sauvegarde. Activez/désactivez la surveillance des sauvegardes en retard, définissez la période d'expiration et la fréquence des notifications.",
        "serverName": "Nom du serveur",
        "backupName": "Nom de sauvegarde",
        "nextRun": "Prochaine exécution",
        "overdueBackupMonitoring": "Surveillance des sauvegardes en retard",
        "expectedBackupInterval": "Intervalle de sauvegarde attendu",
        "unit": "Unité",
        "allowedDays": "Jours autorisés",
        "enabled": "Activé",
        "disabled": "Désactivé",
        "custom": "Personnalisé",
        "minutes": "Minute(s)",
        "minutesShort": "Min(s)",
        "hours": "Heure(s)",
        "days": "Jour(s)",
        "weeks": "Semaine(s)",
        "months": "Mois",
        "years": "Année(s)",
        "notSet": "Non défini",
        "customIntervalPlaceholder": "1D2h30m",
        "lastBackup": "Dernière sauvegarde:",
        "saveOverdueMonitoringSettings": "Enregistrer les paramètres de surveillance des sauvegardes en retard",
        "saving": "Enregistrement...",
        "downloadCSV": "Télécharger CSV",
        "csv": "CSV",
        "checkNow": "Vérifier maintenant",
        "check": "Vérifier",
        "checking": "Vérification...",
        "resetNotifications": "Réinitialiser les notifications",
        "resetting": "Réinitialisation...",
        "overdueTolerance": "Tolérance de retard:",
        "tolerance": "Tolérance:",
        "overdueMonitoringInterval": "Intervalle de surveillance des sauvegardes en retard:",
        "monitoringInterval": "Intervalle de surveillance:",
        "interval": "Intervalle:",
        "notificationFrequency": "Fréquence des notifications:",
        "notificationFreq": "Fréq. notifications:",
        "frequency": "Fréquence:",
        "noTolerance": "Aucune tolérance",
        "tolerance5min": "5 min",
        "tolerance15min": "15 min",
        "tolerance30min": "30 min",
        "tolerance1h": "1 heure",
        "tolerance2h": "2 heures",
        "tolerance4h": "4 heures",
        "tolerance6h": "6 heures",
        "tolerance12h": "12 heures",
        "tolerance1d": "1 jour",
        "oneTime": "Une fois",
        "everyDay": "Chaque jour",
        "everyWeek": "Chaque semaine",
        "everyMonth": "Chaque mois",
        "overdueBackupCheckComplete": "Vérification des sauvegardes en retard terminée",
        "checkedBackupsFoundOverdue": "{checked} sauvegardes vérifiées, {overdue} sauvegardes en retard trouvées, {notifications} notifications envoyées.",
        "failedToRunOverdueBackupCheck": "Échec de la vérification des sauvegardes en retard",
        "overdueBackupCheckIntervalUpdated": "Intervalle de vérification des sauvegardes en retard mis à jour avec succès",
        "configurationSavedCronNotRunning": "Configuration enregistrée avec succès. Note: Le service Cron ne fonctionne pas - démarrez-le avec 'npm run cron:start' pour activer les tâches planifiées.",
        "failedToUpdateOverdueBackupCheckInterval": "Échec de la mise à jour de l'intervalle de vérification des sauvegardes en retard",
        "overdueMonitoringSettingsSaved": "Paramètres de surveillance des sauvegardes en retard enregistrés avec succès",
        "failedToSaveOverdueMonitoringSettings": "Échec de l'enregistrement des paramètres de surveillance des sauvegardes en retard",
        "overdueBackupNotificationsReset": "Les notifications de sauvegardes en retard ont été réinitialisées",
        "failedToResetOverdueBackupNotifications": "Échec de la réinitialisation des notifications de sauvegardes en retard",
        "csvFileDownloadedSuccessfully": "Fichier CSV téléchargé avec succès",
        "failedToGenerateCsvFile": "Échec de la génération du fichier CSV",
        "overdueToleranceUpdatedSuccessfully": "Tolérance de retard mise à jour avec succès.",
        "failedToUpdateOverdueTolerance": "Échec de la mise à jour de la tolérance de retard",
        "notificationFrequencyUpdated": "Fréquence des notifications mise à jour.",
        "failedToUpdateNotificationFrequency": "Échec de la mise à jour de la fréquence des notifications",
        "startingCollection": "Démarrage de la collecte",
        "collectingBackupLogs": "Collecte des journaux de sauvegarde de tous les serveurs configurés...",
        "invalidIntervalFormat": "Format d'intervalle invalide",
        "pleaseEnterValidPositiveNumber": "Veuillez entrer un nombre positif valide",
        "csvGeneratedAt": "CSV généré le",
        "csvServerName": "Nom du serveur",
        "csvServerId": "ID du serveur",
        "csvBackupName": "Nom de sauvegarde",
        "csvLastBackupCfg": "Dernière sauvegarde (cfg)",
        "csvLastBackupCfgWeekday": "Jour de la semaine de la dernière sauvegarde (cfg)",
        "csvLastBackupDb": "Dernière sauvegarde (DB)",
        "csvNextRun": "Prochaine exécution",
        "csvNextRunWeekday": "Jour de la semaine de la prochaine exécution",
        "csvIsOverdue": "Est en retard",
        "csvMonitoringEnabled": "Surveillance activée",
        "csvExpectedInterval": "Intervalle attendu",
        "csvAllowedWeekdays": "Jours de la semaine autorisés",
        "noPermissionToModifySetting": "Vous n'avez pas la permission de modifier ce paramètre. Seuls les administrateurs peuvent modifier les configurations.",
        "noPermissionToRunOverdueBackupChecks": "Vous n'avez pas la permission d'exécuter des vérifications de sauvegardes en retard. Seuls les administrateurs peuvent effectuer cette action.",
        "selectTolerance": "Sélectionner la tolérance",
        "loading": "Chargement...",
        "downloadBackupMonitoringDataAsCsv": "Télécharger les données de surveillance des sauvegardes au format CSV"
      },
      "es": {
        "title": "Monitoreo de respaldos vencidos",
        "description": "Configurar monitoreo para respaldos vencidos",
        "overdueMonitoring": "Monitoreo de respaldos vencidos",
        "noServersWithBackups": "No se encontraron servidores con respaldos en la base de datos",
        "noServersRegisteredYet": "Aún no se han registrado servidores con respaldos. Agregue primero algunos datos de respaldo para ver la configuración de monitoreo de respaldos vencidos.",
        "configureOverdueMonitoring": "Configurar monitoreo de respaldos vencidos",
        "configureOverdueMonitoringDescription": "Configure los ajustes de monitoreo de respaldos vencidos para cada respaldo. Habilite/deshabilite el monitoreo de respaldos vencidos, establezca el período de tiempo de espera y la frecuencia de notificaciones.",
        "serverName": "Nombre del servidor",
        "backupName": "Nombre de respaldo",
        "nextRun": "Próxima ejecución",
        "overdueBackupMonitoring": "Monitoreo de respaldos vencidos",
        "expectedBackupInterval": "Intervalo de respaldo esperado",
        "unit": "Unidad",
        "allowedDays": "Días permitidos",
        "enabled": "Habilitado",
        "disabled": "Deshabilitado",
        "custom": "Personalizado",
        "minutes": "Minuto(s)",
        "minutesShort": "Min(s)",
        "hours": "Hora(s)",
        "days": "Día(s)",
        "weeks": "Semana(s)",
        "months": "Mes(es)",
        "years": "Año(s)",
        "notSet": "No establecido",
        "customIntervalPlaceholder": "1D2h30m",
        "lastBackup": "Último respaldo:",
        "saveOverdueMonitoringSettings": "Guardar configuración de monitoreo de respaldos vencidos",
        "saving": "Guardando...",
        "downloadCSV": "Descargar CSV",
        "csv": "CSV",
        "checkNow": "Verificar ahora",
        "check": "Verificar",
        "checking": "Verificando...",
        "resetNotifications": "Restablecer notificaciones",
        "resetting": "Restableciendo...",
        "overdueTolerance": "Tolerancia de vencimiento:",
        "tolerance": "Tolerancia:",
        "overdueMonitoringInterval": "Intervalo de monitoreo de respaldos vencidos:",
        "monitoringInterval": "Intervalo de monitoreo:",
        "interval": "Intervalo:",
        "notificationFrequency": "Frecuencia de notificaciones:",
        "notificationFreq": "Frec. notificaciones:",
        "frequency": "Frecuencia:",
        "noTolerance": "Sin tolerancia",
        "tolerance5min": "5 min",
        "tolerance15min": "15 min",
        "tolerance30min": "30 min",
        "tolerance1h": "1 hora",
        "tolerance2h": "2 horas",
        "tolerance4h": "4 horas",
        "tolerance6h": "6 horas",
        "tolerance12h": "12 horas",
        "tolerance1d": "1 día",
        "oneTime": "Una vez",
        "everyDay": "Todos los días",
        "everyWeek": "Cada semana",
        "everyMonth": "Cada mes",
        "overdueBackupCheckComplete": "Verificación de respaldos vencidos completada",
        "checkedBackupsFoundOverdue": "{checked} respaldos verificados, {overdue} respaldos vencidos encontrados, {notifications} notificaciones enviadas.",
        "failedToRunOverdueBackupCheck": "Error al ejecutar la verificación de respaldos vencidos",
        "overdueBackupCheckIntervalUpdated": "Intervalo de verificación de respaldos vencidos actualizado exitosamente",
        "configurationSavedCronNotRunning": "Configuración guardada exitosamente. Nota: El servicio Cron no está en ejecución - inícielo con 'npm run cron:start' para habilitar tareas programadas.",
        "failedToUpdateOverdueBackupCheckInterval": "Error al actualizar el intervalo de verificación de respaldos vencidos",
        "overdueMonitoringSettingsSaved": "Configuración de monitoreo de respaldos vencidos guardada exitosamente",
        "failedToSaveOverdueMonitoringSettings": "Error al guardar la configuración de monitoreo de respaldos vencidos",
        "overdueBackupNotificationsReset": "Las notificaciones de respaldos vencidos se han restablecido",
        "failedToResetOverdueBackupNotifications": "Error al restablecer las notificaciones de respaldos vencidos",
        "csvFileDownloadedSuccessfully": "Archivo CSV descargado exitosamente",
        "failedToGenerateCsvFile": "Error al generar archivo CSV",
        "overdueToleranceUpdatedSuccessfully": "Tolerancia de vencimiento actualizada exitosamente.",
        "failedToUpdateOverdueTolerance": "Error al actualizar la tolerancia de vencimiento",
        "notificationFrequencyUpdated": "Frecuencia de notificaciones actualizada.",
        "failedToUpdateNotificationFrequency": "Error al actualizar la frecuencia de notificaciones",
        "startingCollection": "Iniciando recopilación",
        "collectingBackupLogs": "Recopilando registros de respaldo de todos los servidores configurados...",
        "invalidIntervalFormat": "Formato de intervalo inválido",
        "pleaseEnterValidPositiveNumber": "Por favor ingrese un número positivo válido",
        "csvGeneratedAt": "CSV generado en",
        "csvServerName": "Nombre del servidor",
        "csvServerId": "ID del servidor",
        "csvBackupName": "Nombre de respaldo",
        "csvLastBackupCfg": "Último respaldo (cfg)",
        "csvLastBackupCfgWeekday": "Día de la semana del último respaldo (cfg)",
        "csvLastBackupDb": "Último respaldo (DB)",
        "csvNextRun": "Próxima ejecución",
        "csvNextRunWeekday": "Día de la semana de la próxima ejecución",
        "csvIsOverdue": "Está vencido",
        "csvMonitoringEnabled": "Monitoreo habilitado",
        "csvExpectedInterval": "Intervalo esperado",
        "csvAllowedWeekdays": "Días de la semana permitidos",
        "noPermissionToModifySetting": "No tiene permiso para modificar esta configuración. Solo los administradores pueden cambiar configuraciones.",
        "noPermissionToRunOverdueBackupChecks": "No tiene permiso para ejecutar verificaciones de respaldos vencidos. Solo los administradores pueden realizar esta acción.",
        "selectTolerance": "Seleccionar tolerancia",
        "loading": "Cargando...",
        "downloadBackupMonitoringDataAsCsv": "Descargar datos de monitoreo de respaldos como CSV"
      },
      "pt-BR": {
        "title": "Monitoramento de backups atrasados",
        "description": "Configurar monitoramento para backups atrasados",
        "overdueMonitoring": "Monitoramento de backups atrasados",
        "noServersWithBackups": "Nenhum servidor com backups encontrado no banco de dados",
        "noServersRegisteredYet": "Nenhum servidor com backups foi registrado ainda. Adicione primeiro alguns dados de backup para ver as configurações de monitoramento de backups atrasados.",
        "configureOverdueMonitoring": "Configurar monitoramento de backups atrasados",
        "configureOverdueMonitoringDescription": "Configure as configurações de monitoramento de backups atrasados para cada backup. Habilite/desabilite o monitoramento de backups atrasados, defina o período de tempo limite e a frequência de notificações.",
        "serverName": "Nome do servidor",
        "backupName": "Nome do backup",
        "nextRun": "Próxima execução",
        "overdueBackupMonitoring": "Monitoramento de backups atrasados",
        "expectedBackupInterval": "Intervalo de backup esperado",
        "unit": "Unidade",
        "allowedDays": "Dias permitidos",
        "enabled": "Habilitado",
        "disabled": "Desabilitado",
        "custom": "Personalizado",
        "minutes": "Minuto(s)",
        "minutesShort": "Min(s)",
        "hours": "Hora(s)",
        "days": "Dia(s)",
        "weeks": "Semana(s)",
        "months": "Mês(es)",
        "years": "Ano(s)",
        "notSet": "Não definido",
        "customIntervalPlaceholder": "1D2h30m",
        "lastBackup": "Último backup:",
        "saveOverdueMonitoringSettings": "Salvar configurações de monitoramento de backups atrasados",
        "saving": "Salvando...",
        "downloadCSV": "Baixar CSV",
        "csv": "CSV",
        "checkNow": "Verificar agora",
        "check": "Verificar",
        "checking": "Verificando...",
        "resetNotifications": "Redefinir notificações",
        "resetting": "Redefinindo...",
        "overdueTolerance": "Tolerância de atraso:",
        "tolerance": "Tolerância:",
        "overdueMonitoringInterval": "Intervalo de monitoramento de backups atrasados:",
        "monitoringInterval": "Intervalo de monitoramento:",
        "interval": "Intervalo:",
        "notificationFrequency": "Frequência de notificações:",
        "notificationFreq": "Freq. notificações:",
        "frequency": "Frequência:",
        "noTolerance": "Sem tolerância",
        "tolerance5min": "5 min",
        "tolerance15min": "15 min",
        "tolerance30min": "30 min",
        "tolerance1h": "1 hora",
        "tolerance2h": "2 horas",
        "tolerance4h": "4 horas",
        "tolerance6h": "6 horas",
        "tolerance12h": "12 horas",
        "tolerance1d": "1 dia",
        "oneTime": "Uma vez",
        "everyDay": "Todos os dias",
        "everyWeek": "Toda semana",
        "everyMonth": "Todo mês",
        "overdueBackupCheckComplete": "Verificação de backups atrasados concluída",
        "checkedBackupsFoundOverdue": "{checked} backups verificados, {overdue} backups atrasados encontrados, {notifications} notificações enviadas.",
        "failedToRunOverdueBackupCheck": "Falha ao executar verificação de backups atrasados",
        "overdueBackupCheckIntervalUpdated": "Intervalo de verificação de backups atrasados atualizado com sucesso",
        "configurationSavedCronNotRunning": "Configuração salva com sucesso. Nota: O serviço Cron não está em execução - inicie-o com 'npm run cron:start' para habilitar tarefas agendadas.",
        "failedToUpdateOverdueBackupCheckInterval": "Falha ao atualizar intervalo de verificação de backups atrasados",
        "overdueMonitoringSettingsSaved": "Configurações de monitoramento de backups atrasados salvas com sucesso",
        "failedToSaveOverdueMonitoringSettings": "Falha ao salvar configurações de monitoramento de backups atrasados",
        "overdueBackupNotificationsReset": "As notificações de backups atrasados foram redefinidas",
        "failedToResetOverdueBackupNotifications": "Falha ao redefinir notificações de backups atrasados",
        "csvFileDownloadedSuccessfully": "Arquivo CSV baixado com sucesso",
        "failedToGenerateCsvFile": "Falha ao gerar arquivo CSV",
        "overdueToleranceUpdatedSuccessfully": "Tolerância de atraso atualizada com sucesso.",
        "failedToUpdateOverdueTolerance": "Falha ao atualizar tolerância de atraso",
        "notificationFrequencyUpdated": "Frequência de notificações atualizada.",
        "failedToUpdateNotificationFrequency": "Falha ao atualizar frequência de notificações",
        "startingCollection": "Iniciando coleta",
        "collectingBackupLogs": "Coletando logs de backup de todos os servidores configurados...",
        "invalidIntervalFormat": "Formato de intervalo inválido",
        "pleaseEnterValidPositiveNumber": "Por favor, insira um número positivo válido",
        "csvGeneratedAt": "CSV gerado em",
        "csvServerName": "Nome do servidor",
        "csvServerId": "ID do servidor",
        "csvBackupName": "Nome do backup",
        "csvLastBackupCfg": "Último backup (cfg)",
        "csvLastBackupCfgWeekday": "Dia da semana do último backup (cfg)",
        "csvLastBackupDb": "Último backup (DB)",
        "csvNextRun": "Próxima execução",
        "csvNextRunWeekday": "Dia da semana da próxima execução",
        "csvIsOverdue": "Está atrasado",
        "csvMonitoringEnabled": "Monitoramento habilitado",
        "csvExpectedInterval": "Intervalo esperado",
        "csvAllowedWeekdays": "Dias da semana permitidos",
        "noPermissionToModifySetting": "Você não tem permissão para modificar esta configuração. Apenas administradores podem alterar configurações.",
        "noPermissionToRunOverdueBackupChecks": "Você não tem permissão para executar verificações de backups atrasados. Apenas administradores podem realizar esta ação.",
        "selectTolerance": "Selecionar tolerância",
        "loading": "Carregando...",
        "downloadBackupMonitoringDataAsCsv": "Baixar dados de monitoramento de backups como CSV"
      }
    }
  },
  "localIds": [
    "overdue-monitoring-form::local::src/components/settings/overdue-monitoring-form.content.ts"
  ]
} as const;
