/* eslint-disable */
export default {
  "key": "server-backup-table",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "backupName": "Backup Name",
        "date": "Date",
        "status": "Status",
        "warnings": "Warnings",
        "errors": "Errors",
        "files": "Files",
        "size": "Size",
        "uploadedSize": "Uploaded Size",
        "duration": "Duration",
        "filterByBackup": "Filter by Backup",
        "allBackups": "All Backups",
        "noBackupsFound": "No backups found",
        "availableVersions": "Available Versions",
        "fileCount": "File Count",
        "fileSize": "File Size",
        "storageSize": "Storage Size",
        "selectBackup": "Select backup",
        "noBackupsFoundForThisServer": "No backups found for this server.",
        "noBackupsFoundForThisMachine": "No backups found for this machine.",
        "noMessagesReceivedForThisBackup": "No messages were received for this backup.",
        "viewDetails": "View Details",
        "previous": "Previous",
        "next": "Next",
        "page": "Page",
        "of": "of"
      },
      "de": {
        "backupName": "Sicherungsname",
        "date": "Datum",
        "status": "Status",
        "warnings": "Warnungen",
        "errors": "Fehler",
        "files": "Dateien",
        "size": "Größe",
        "uploadedSize": "Hochgeladene Größe",
        "duration": "Dauer",
        "filterByBackup": "Nach Sicherung filtern",
        "allBackups": "Alle Sicherungen",
        "noBackupsFound": "Keine Sicherungen gefunden",
        "availableVersions": "Verfügbare Versionen",
        "fileCount": "Dateianzahl",
        "fileSize": "Dateigröße",
        "storageSize": "Speichergröße",
        "selectBackup": "Sicherung auswählen",
        "noBackupsFoundForThisServer": "Keine Sicherungen für diesen Server gefunden.",
        "noBackupsFoundForThisMachine": "Keine Sicherungen für diese Maschine gefunden.",
        "noMessagesReceivedForThisBackup": "Für diese Sicherung wurden keine Nachrichten empfangen.",
        "viewDetails": "Details anzeigen",
        "previous": "Vorherige",
        "next": "Nächste",
        "page": "Seite",
        "of": "von"
      },
      "fr": {
        "backupName": "Nom de sauvegarde",
        "date": "Date",
        "status": "Statut",
        "warnings": "Avertissements",
        "errors": "Erreurs",
        "files": "Fichiers",
        "size": "Taille",
        "uploadedSize": "Taille téléchargée",
        "duration": "Durée",
        "filterByBackup": "Filtrer par sauvegarde",
        "allBackups": "Toutes les sauvegardes",
        "noBackupsFound": "Aucune sauvegarde trouvée",
        "availableVersions": "Versions disponibles",
        "fileCount": "Nombre de fichiers",
        "fileSize": "Taille de fichier",
        "storageSize": "Taille de stockage",
        "selectBackup": "Sélectionner la sauvegarde",
        "noBackupsFoundForThisServer": "Aucune sauvegarde trouvée pour ce serveur.",
        "noBackupsFoundForThisMachine": "Aucune sauvegarde trouvée pour cette machine.",
        "noMessagesReceivedForThisBackup": "Aucun message n'a été reçu pour cette sauvegarde.",
        "viewDetails": "Voir les détails",
        "previous": "Précédent",
        "next": "Suivant",
        "page": "Page",
        "of": "de"
      },
      "es": {
        "backupName": "Nombre de respaldo",
        "date": "Fecha",
        "status": "Estado",
        "warnings": "Advertencias",
        "errors": "Errores",
        "files": "Archivos",
        "size": "Tamaño",
        "uploadedSize": "Tamaño subido",
        "duration": "Duración",
        "filterByBackup": "Filtrar por respaldo",
        "allBackups": "Todos los respaldos",
        "noBackupsFound": "No se encontraron respaldos",
        "availableVersions": "Versiones disponibles",
        "fileCount": "Cantidad de archivos",
        "fileSize": "Tamaño de archivo",
        "storageSize": "Tamaño de almacenamiento",
        "selectBackup": "Seleccionar respaldo",
        "noBackupsFoundForThisServer": "No se encontraron respaldos para este servidor.",
        "noBackupsFoundForThisMachine": "No se encontraron respaldos para esta máquina.",
        "noMessagesReceivedForThisBackup": "No se recibieron mensajes para este respaldo.",
        "viewDetails": "Ver detalles",
        "previous": "Anterior",
        "next": "Siguiente",
        "page": "Página",
        "of": "de"
      },
      "pt-BR": {
        "backupName": "Nome do backup",
        "date": "Data",
        "status": "Status",
        "warnings": "Avisos",
        "errors": "Erros",
        "files": "Arquivos",
        "size": "Tamanho",
        "uploadedSize": "Tamanho enviado",
        "duration": "Duração",
        "filterByBackup": "Filtrar por backup",
        "allBackups": "Todos os backups",
        "noBackupsFound": "Nenhum backup encontrado",
        "availableVersions": "Versões disponíveis",
        "fileCount": "Contagem de arquivos",
        "fileSize": "Tamanho do arquivo",
        "storageSize": "Tamanho de armazenamento",
        "selectBackup": "Selecionar backup",
        "noBackupsFoundForThisServer": "Nenhum backup encontrado para este servidor.",
        "noBackupsFoundForThisMachine": "Nenhum backup encontrado para esta máquina.",
        "noMessagesReceivedForThisBackup": "Nenhuma mensagem foi recebida para este backup.",
        "viewDetails": "Ver detalhes",
        "previous": "Anterior",
        "next": "Próximo",
        "page": "Página",
        "of": "de"
      }
    }
  },
  "localIds": [
    "server-backup-table::local::src/components/server-details/server-backup-table.content.ts"
  ]
} as const;
