/* eslint-disable */
export default {
  "key": "user-management-form",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "title": "User Management",
        "description": "Manage application users and permissions",
        "addUser": "Add User",
        "editUser": "Edit User",
        "deleteUser": "Delete User",
        "cardDescription": "Manage user accounts, roles, and permissions. Create, edit, or delete users and reset passwords.",
        "searchUsers": "Search users...",
        "loadingUsers": "Loading users...",
        "noUsersFoundMatchingSearch": "No users found matching your search",
        "noUsersFound": "No users found",
        "username": "Username",
        "role": "Role",
        "lastLogin": "Last Login",
        "lastUpdate": "Last Update",
        "created": "Created",
        "status": "Status",
        "actions": "Actions",
        "admin": "Admin",
        "user": "User",
        "never": "Never",
        "locked": "Locked",
        "mustChangePassword": "Must Change Password",
        "editUserTitle": "Edit user",
        "resetPasswordTitle": "Reset password",
        "cannotDeleteLastAdmin": "Cannot delete the last admin account",
        "deleteAdminUserWarning": "Delete admin user (warning: this is an admin account)",
        "deleteUserTitle": "Delete user",
        "createNewUser": "Create New User",
        "editUserDialog": "Edit User",
        "deleteUserDialog": "Delete User",
        "passwordReset": "Password Reset",
        "createNewUserDescription": "Create a new user account. You can auto-generate a secure password or set a custom one.",
        "editUserDescription": "Update user information. Use the password reset button to change the password.",
        "deleteUserDescription": "Are you sure you want to delete user {username}? This action cannot be undone.",
        "warningThisIsAdminUser": "Warning: This is an admin user.",
        "passwordResetDescription": "A new temporary password has been generated for {username}.",
        "passwordResetDescriptionGeneric": "A new temporary password has been generated for the user.",
        "copyPasswordNow": "Copy this password now - it will not be shown again!",
        "usernameLabel": "Username",
        "autoGenerateSecurePassword": "Auto-generate secure password",
        "adminUser": "Admin user",
        "requirePasswordChangeOnFirstLogin": "Require password change on first login",
        "requirePasswordChangeOnNextLogin": "Require password change on next login",
        "enterUsername": "Enter username",
        "enterPassword": "Enter password",
        "passwordRequirements": "Password Requirements:",
        "atLeastXCharactersLong": "At least {minLength} characters long",
        "containsUppercaseLetter": "Contains at least one uppercase letter (A-Z)",
        "containsLowercaseLetter": "Contains at least one lowercase letter (a-z)",
        "containsNumber": "Contains at least one number (0-9)",
        "cancel": "Cancel",
        "createUser": "Create User",
        "creating": "Creating...",
        "saveChanges": "Save Changes",
        "saving": "Saving...",
        "delete": "Delete",
        "deleting": "Deleting...",
        "close": "Close",
        "temporaryPassword": "Temporary Password",
        "copyPassword": "Copy password",
        "userWillBeRequiredToChangePassword": "The user will be required to change this password on first login.",
        "failedToLoadUsers": "Failed to load users",
        "usernameRequired": "Username is required",
        "passwordRequiredWhenNotAutoGenerating": "Password is required when not auto-generating",
        "failedToCreateUser": "Failed to create user",
        "userCreatedSuccessfully": "User created successfully",
        "failedToUpdateUser": "Failed to update user",
        "userUpdatedSuccessfully": "User updated successfully",
        "failedToDeleteUser": "Failed to delete user",
        "userDeletedSuccessfully": "User deleted successfully",
        "failedToResetPassword": "Failed to reset password"
      },
      "de": {
        "title": "Benutzerverwaltung",
        "description": "Anwendungsbenutzer und Berechtigungen verwalten",
        "addUser": "Benutzer hinzufügen",
        "editUser": "Benutzer bearbeiten",
        "deleteUser": "Benutzer löschen",
        "cardDescription": "Benutzerkonten, Rollen und Berechtigungen verwalten. Benutzer erstellen, bearbeiten oder löschen und Passwörter zurücksetzen.",
        "searchUsers": "Benutzer suchen...",
        "loadingUsers": "Benutzer werden geladen...",
        "noUsersFoundMatchingSearch": "Keine Benutzer gefunden, die Ihrer Suche entsprechen",
        "noUsersFound": "Keine Benutzer gefunden",
        "username": "Benutzername",
        "role": "Rolle",
        "lastLogin": "Letzte Anmeldung",
        "lastUpdate": "Letzte Aktualisierung",
        "created": "Erstellt",
        "status": "Status",
        "actions": "Aktionen",
        "admin": "Administrator",
        "user": "Benutzer",
        "never": "Nie",
        "locked": "Gesperrt",
        "mustChangePassword": "Passwort muss geändert werden",
        "editUserTitle": "Benutzer bearbeiten",
        "resetPasswordTitle": "Passwort zurücksetzen",
        "cannotDeleteLastAdmin": "Das letzte Administratorkonto kann nicht gelöscht werden",
        "deleteAdminUserWarning": "Administratorbenutzer löschen (Warnung: Dies ist ein Administratorkonto)",
        "deleteUserTitle": "Benutzer löschen",
        "createNewUser": "Neuen Benutzer erstellen",
        "editUserDialog": "Benutzer bearbeiten",
        "deleteUserDialog": "Benutzer löschen",
        "passwordReset": "Passwort zurücksetzen",
        "createNewUserDescription": "Erstellen Sie ein neues Benutzerkonto. Sie können ein sicheres Passwort automatisch generieren oder ein benutzerdefiniertes festlegen.",
        "editUserDescription": "Aktualisieren Sie Benutzerinformationen. Verwenden Sie die Schaltfläche zum Zurücksetzen des Passworts, um das Passwort zu ändern.",
        "deleteUserDescription": "Sind Sie sicher, dass Sie den Benutzer {username} löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
        "warningThisIsAdminUser": "Warnung: Dies ist ein Administratorbenutzer.",
        "passwordResetDescription": "Ein neues temporäres Passwort wurde für {username} generiert.",
        "passwordResetDescriptionGeneric": "Ein neues temporäres Passwort wurde für den Benutzer generiert.",
        "copyPasswordNow": "Kopieren Sie dieses Passwort jetzt - es wird nicht erneut angezeigt!",
        "usernameLabel": "Benutzername",
        "autoGenerateSecurePassword": "Sicheres Passwort automatisch generieren",
        "adminUser": "Administratorbenutzer",
        "requirePasswordChangeOnFirstLogin": "Passwortänderung bei erster Anmeldung erforderlich",
        "requirePasswordChangeOnNextLogin": "Passwortänderung bei nächster Anmeldung erforderlich",
        "enterUsername": "Benutzername eingeben",
        "enterPassword": "Passwort eingeben",
        "passwordRequirements": "Passwortanforderungen:",
        "atLeastXCharactersLong": "Mindestens {minLength} Zeichen lang",
        "containsUppercaseLetter": "Enthält mindestens einen Großbuchstaben (A-Z)",
        "containsLowercaseLetter": "Enthält mindestens einen Kleinbuchstaben (a-z)",
        "containsNumber": "Enthält mindestens eine Zahl (0-9)",
        "cancel": "Abbrechen",
        "createUser": "Benutzer erstellen",
        "creating": "Wird erstellt...",
        "saveChanges": "Änderungen speichern",
        "saving": "Wird gespeichert...",
        "delete": "Löschen",
        "deleting": "Wird gelöscht...",
        "close": "Schließen",
        "temporaryPassword": "Temporäres Passwort",
        "copyPassword": "Passwort kopieren",
        "userWillBeRequiredToChangePassword": "Der Benutzer muss dieses Passwort bei der ersten Anmeldung ändern.",
        "failedToLoadUsers": "Fehler beim Laden der Benutzer",
        "usernameRequired": "Benutzername ist erforderlich",
        "passwordRequiredWhenNotAutoGenerating": "Passwort ist erforderlich, wenn nicht automatisch generiert",
        "failedToCreateUser": "Fehler beim Erstellen des Benutzers",
        "userCreatedSuccessfully": "Benutzer erfolgreich erstellt",
        "failedToUpdateUser": "Fehler beim Aktualisieren des Benutzers",
        "userUpdatedSuccessfully": "Benutzer erfolgreich aktualisiert",
        "failedToDeleteUser": "Fehler beim Löschen des Benutzers",
        "userDeletedSuccessfully": "Benutzer erfolgreich gelöscht",
        "failedToResetPassword": "Fehler beim Zurücksetzen des Passworts"
      },
      "fr": {
        "title": "Gestion des utilisateurs",
        "description": "Gérer les utilisateurs et les permissions de l'application",
        "addUser": "Ajouter un utilisateur",
        "editUser": "Modifier l'utilisateur",
        "deleteUser": "Supprimer l'utilisateur",
        "cardDescription": "Gérer les comptes utilisateurs, les rôles et les permissions. Créer, modifier ou supprimer des utilisateurs et réinitialiser les mots de passe.",
        "searchUsers": "Rechercher des utilisateurs...",
        "loadingUsers": "Chargement des utilisateurs...",
        "noUsersFoundMatchingSearch": "Aucun utilisateur trouvé correspondant à votre recherche",
        "noUsersFound": "Aucun utilisateur trouvé",
        "username": "Nom d'utilisateur",
        "role": "Rôle",
        "lastLogin": "Dernière connexion",
        "lastUpdate": "Dernière mise à jour",
        "created": "Créé",
        "status": "Statut",
        "actions": "Actions",
        "admin": "Administrateur",
        "user": "Utilisateur",
        "never": "Jamais",
        "locked": "Verrouillé",
        "mustChangePassword": "Doit changer le mot de passe",
        "editUserTitle": "Modifier l'utilisateur",
        "resetPasswordTitle": "Réinitialiser le mot de passe",
        "cannotDeleteLastAdmin": "Impossible de supprimer le dernier compte administrateur",
        "deleteAdminUserWarning": "Supprimer l'utilisateur administrateur (avertissement: ceci est un compte administrateur)",
        "deleteUserTitle": "Supprimer l'utilisateur",
        "createNewUser": "Créer un nouvel utilisateur",
        "editUserDialog": "Modifier l'utilisateur",
        "deleteUserDialog": "Supprimer l'utilisateur",
        "passwordReset": "Réinitialisation du mot de passe",
        "createNewUserDescription": "Créez un nouveau compte utilisateur. Vous pouvez générer automatiquement un mot de passe sécurisé ou en définir un personnalisé.",
        "editUserDescription": "Mettez à jour les informations utilisateur. Utilisez le bouton de réinitialisation du mot de passe pour changer le mot de passe.",
        "deleteUserDescription": "Êtes-vous sûr de vouloir supprimer l'utilisateur {username}? Cette action ne peut pas être annulée.",
        "warningThisIsAdminUser": "Avertissement: Ceci est un utilisateur administrateur.",
        "passwordResetDescription": "Un nouveau mot de passe temporaire a été généré pour {username}.",
        "passwordResetDescriptionGeneric": "Un nouveau mot de passe temporaire a été généré pour l'utilisateur.",
        "copyPasswordNow": "Copiez ce mot de passe maintenant - il ne sera plus affiché!",
        "usernameLabel": "Nom d'utilisateur",
        "autoGenerateSecurePassword": "Générer automatiquement un mot de passe sécurisé",
        "adminUser": "Utilisateur administrateur",
        "requirePasswordChangeOnFirstLogin": "Exiger le changement de mot de passe lors de la première connexion",
        "requirePasswordChangeOnNextLogin": "Exiger le changement de mot de passe lors de la prochaine connexion",
        "enterUsername": "Entrer le nom d'utilisateur",
        "enterPassword": "Entrer le mot de passe",
        "passwordRequirements": "Exigences du mot de passe:",
        "atLeastXCharactersLong": "Au moins {minLength} caractères",
        "containsUppercaseLetter": "Contient au moins une lettre majuscule (A-Z)",
        "containsLowercaseLetter": "Contient au moins une lettre minuscule (a-z)",
        "containsNumber": "Contient au moins un chiffre (0-9)",
        "cancel": "Annuler",
        "createUser": "Créer l'utilisateur",
        "creating": "Création...",
        "saveChanges": "Enregistrer les modifications",
        "saving": "Enregistrement...",
        "delete": "Supprimer",
        "deleting": "Suppression...",
        "close": "Fermer",
        "temporaryPassword": "Mot de passe temporaire",
        "copyPassword": "Copier le mot de passe",
        "userWillBeRequiredToChangePassword": "L'utilisateur devra changer ce mot de passe lors de la première connexion.",
        "failedToLoadUsers": "Échec du chargement des utilisateurs",
        "usernameRequired": "Le nom d'utilisateur est requis",
        "passwordRequiredWhenNotAutoGenerating": "Le mot de passe est requis lorsqu'il n'est pas généré automatiquement",
        "failedToCreateUser": "Échec de la création de l'utilisateur",
        "userCreatedSuccessfully": "Utilisateur créé avec succès",
        "failedToUpdateUser": "Échec de la mise à jour de l'utilisateur",
        "userUpdatedSuccessfully": "Utilisateur mis à jour avec succès",
        "failedToDeleteUser": "Échec de la suppression de l'utilisateur",
        "userDeletedSuccessfully": "Utilisateur supprimé avec succès",
        "failedToResetPassword": "Échec de la réinitialisation du mot de passe"
      },
      "es": {
        "title": "Gestión de usuarios",
        "description": "Administrar usuarios y permisos de la aplicación",
        "addUser": "Agregar usuario",
        "editUser": "Editar usuario",
        "deleteUser": "Eliminar usuario",
        "cardDescription": "Administrar cuentas de usuario, roles y permisos. Crear, editar o eliminar usuarios y restablecer contraseñas.",
        "searchUsers": "Buscar usuarios...",
        "loadingUsers": "Cargando usuarios...",
        "noUsersFoundMatchingSearch": "No se encontraron usuarios que coincidan con su búsqueda",
        "noUsersFound": "No se encontraron usuarios",
        "username": "Nombre de usuario",
        "role": "Rol",
        "lastLogin": "Último inicio de sesión",
        "lastUpdate": "Última actualización",
        "created": "Creado",
        "status": "Estado",
        "actions": "Acciones",
        "admin": "Administrador",
        "user": "Usuario",
        "never": "Nunca",
        "locked": "Bloqueado",
        "mustChangePassword": "Debe cambiar la contraseña",
        "editUserTitle": "Editar usuario",
        "resetPasswordTitle": "Restablecer contraseña",
        "cannotDeleteLastAdmin": "No se puede eliminar la última cuenta de administrador",
        "deleteAdminUserWarning": "Eliminar usuario administrador (advertencia: esta es una cuenta de administrador)",
        "deleteUserTitle": "Eliminar usuario",
        "createNewUser": "Crear nuevo usuario",
        "editUserDialog": "Editar usuario",
        "deleteUserDialog": "Eliminar usuario",
        "passwordReset": "Restablecimiento de contraseña",
        "createNewUserDescription": "Crear una nueva cuenta de usuario. Puede generar automáticamente una contraseña segura o establecer una personalizada.",
        "editUserDescription": "Actualizar información del usuario. Use el botón de restablecimiento de contraseña para cambiar la contraseña.",
        "deleteUserDescription": "¿Está seguro de que desea eliminar al usuario {username}? Esta acción no se puede deshacer.",
        "warningThisIsAdminUser": "Advertencia: Este es un usuario administrador.",
        "passwordResetDescription": "Se ha generado una nueva contraseña temporal para {username}.",
        "passwordResetDescriptionGeneric": "Se ha generado una nueva contraseña temporal para el usuario.",
        "copyPasswordNow": "¡Copie esta contraseña ahora - no se mostrará nuevamente!",
        "usernameLabel": "Nombre de usuario",
        "autoGenerateSecurePassword": "Generar automáticamente contraseña segura",
        "adminUser": "Usuario administrador",
        "requirePasswordChangeOnFirstLogin": "Requerir cambio de contraseña en el primer inicio de sesión",
        "requirePasswordChangeOnNextLogin": "Requerir cambio de contraseña en el próximo inicio de sesión",
        "enterUsername": "Ingresar nombre de usuario",
        "enterPassword": "Ingresar contraseña",
        "passwordRequirements": "Requisitos de contraseña:",
        "atLeastXCharactersLong": "Al menos {minLength} caracteres de longitud",
        "containsUppercaseLetter": "Contiene al menos una letra mayúscula (A-Z)",
        "containsLowercaseLetter": "Contiene al menos una letra minúscula (a-z)",
        "containsNumber": "Contiene al menos un número (0-9)",
        "cancel": "Cancelar",
        "createUser": "Crear usuario",
        "creating": "Creando...",
        "saveChanges": "Guardar cambios",
        "saving": "Guardando...",
        "delete": "Eliminar",
        "deleting": "Eliminando...",
        "close": "Cerrar",
        "temporaryPassword": "Contraseña temporal",
        "copyPassword": "Copiar contraseña",
        "userWillBeRequiredToChangePassword": "El usuario deberá cambiar esta contraseña en el primer inicio de sesión.",
        "failedToLoadUsers": "Error al cargar usuarios",
        "usernameRequired": "El nombre de usuario es obligatorio",
        "passwordRequiredWhenNotAutoGenerating": "La contraseña es obligatoria cuando no se genera automáticamente",
        "failedToCreateUser": "Error al crear usuario",
        "userCreatedSuccessfully": "Usuario creado exitosamente",
        "failedToUpdateUser": "Error al actualizar usuario",
        "userUpdatedSuccessfully": "Usuario actualizado exitosamente",
        "failedToDeleteUser": "Error al eliminar usuario",
        "userDeletedSuccessfully": "Usuario eliminado exitosamente",
        "failedToResetPassword": "Error al restablecer contraseña"
      },
      "pt-BR": {
        "title": "Gerenciamento de usuários",
        "description": "Gerenciar usuários e permissões do aplicativo",
        "addUser": "Adicionar usuário",
        "editUser": "Editar usuário",
        "deleteUser": "Excluir usuário",
        "cardDescription": "Gerenciar contas de usuário, funções e permissões. Criar, editar ou excluir usuários e redefinir senhas.",
        "searchUsers": "Buscar usuários...",
        "loadingUsers": "Carregando usuários...",
        "noUsersFoundMatchingSearch": "Nenhum usuário encontrado correspondente à sua pesquisa",
        "noUsersFound": "Nenhum usuário encontrado",
        "username": "Nome de usuário",
        "role": "Função",
        "lastLogin": "Último login",
        "lastUpdate": "Última atualização",
        "created": "Criado",
        "status": "Status",
        "actions": "Ações",
        "admin": "Administrador",
        "user": "Usuário",
        "never": "Nunca",
        "locked": "Bloqueado",
        "mustChangePassword": "Deve alterar a senha",
        "editUserTitle": "Editar usuário",
        "resetPasswordTitle": "Redefinir senha",
        "cannotDeleteLastAdmin": "Não é possível excluir a última conta de administrador",
        "deleteAdminUserWarning": "Excluir usuário administrador (aviso: esta é uma conta de administrador)",
        "deleteUserTitle": "Excluir usuário",
        "createNewUser": "Criar novo usuário",
        "editUserDialog": "Editar usuário",
        "deleteUserDialog": "Excluir usuário",
        "passwordReset": "Redefinição de senha",
        "createNewUserDescription": "Criar uma nova conta de usuário. Você pode gerar automaticamente uma senha segura ou definir uma personalizada.",
        "editUserDescription": "Atualizar informações do usuário. Use o botão de redefinição de senha para alterar a senha.",
        "deleteUserDescription": "Tem certeza de que deseja excluir o usuário {username}? Esta ação não pode ser desfeita.",
        "warningThisIsAdminUser": "Aviso: Este é um usuário administrador.",
        "passwordResetDescription": "Uma nova senha temporária foi gerada para {username}.",
        "passwordResetDescriptionGeneric": "Uma nova senha temporária foi gerada para o usuário.",
        "copyPasswordNow": "Copie esta senha agora - ela não será mostrada novamente!",
        "usernameLabel": "Nome de usuário",
        "autoGenerateSecurePassword": "Gerar senha segura automaticamente",
        "adminUser": "Usuário administrador",
        "requirePasswordChangeOnFirstLogin": "Exigir alteração de senha no primeiro login",
        "requirePasswordChangeOnNextLogin": "Exigir alteração de senha no próximo login",
        "enterUsername": "Digite o nome de usuário",
        "enterPassword": "Digite a senha",
        "passwordRequirements": "Requisitos de senha:",
        "atLeastXCharactersLong": "Pelo menos {minLength} caracteres",
        "containsUppercaseLetter": "Contém pelo menos uma letra maiúscula (A-Z)",
        "containsLowercaseLetter": "Contém pelo menos uma letra minúscula (a-z)",
        "containsNumber": "Contém pelo menos um número (0-9)",
        "cancel": "Cancelar",
        "createUser": "Criar usuário",
        "creating": "Criando...",
        "saveChanges": "Salvar alterações",
        "saving": "Salvando...",
        "delete": "Excluir",
        "deleting": "Excluindo...",
        "close": "Fechar",
        "temporaryPassword": "Senha temporária",
        "copyPassword": "Copiar senha",
        "userWillBeRequiredToChangePassword": "O usuário será obrigado a alterar esta senha no primeiro login.",
        "failedToLoadUsers": "Falha ao carregar usuários",
        "usernameRequired": "Nome de usuário é obrigatório",
        "passwordRequiredWhenNotAutoGenerating": "Senha é obrigatória quando não está sendo gerada automaticamente",
        "failedToCreateUser": "Falha ao criar usuário",
        "userCreatedSuccessfully": "Usuário criado com sucesso",
        "failedToUpdateUser": "Falha ao atualizar usuário",
        "userUpdatedSuccessfully": "Usuário atualizado com sucesso",
        "failedToDeleteUser": "Falha ao excluir usuário",
        "userDeletedSuccessfully": "Usuário excluído com sucesso",
        "failedToResetPassword": "Falha ao redefinir senha"
      }
    }
  },
  "localIds": [
    "user-management-form::local::src/components/settings/user-management-form.content.ts"
  ]
} as const;
