#!/usr/bin/env node
/**
 * Creates a GitHub release from the local CLI using:
 * - tag/title: v<package.json version>
 * - source notes: documentation/docs/release-notes/<version>.md
 * - GitHub notes: RELEASE_NOTES_github_<version>.md
 *   (generated by scripts/generate-readme-from-intro.sh; gitignored)
 *
 * Publishing the release triggers "Build and Publish Docker Image".
 * The script then deploys the Docusaurus site with `pnpm run deploy`
 * in documentation/ (GitHub Pages, gh-pages branch).
 * Run this from the commit that should be released (typically master,
 * already pushed). The script pushes the tag, not the branch.
 *
 * If the tag (or a GitHub release for it) already exists, it is removed and
 * the tag is recreated at the current HEAD, then pushed — so you can fix a
 * mistaken tag or re-run the release after new commits.
 *
 * Usage:
 *   node scripts/release.mjs
 *   node scripts/release.mjs --dry-run
 *   node scripts/release.mjs --verify-clean=false
 *   pnpm release:github
 *   pnpm release:github:dry
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

let verifyClean = true;
let dryRun = false;

function printHelp() {
  console.log(`Usage: node scripts/release.mjs [--dry-run] [--verify-clean=true|false]

Options:
  --dry-run            Validate and print planned steps; no notes rewrite, deletes, tag, push, release, or docs deploy.
  --verify-clean=true  Require a clean git working tree before and after notes generation (default).
  --verify-clean=false Skip clean-tree checks.

Reads documentation/docs/release-notes/<version>.md, generates
RELEASE_NOTES_github_<version>.md, tags v<version> at HEAD, and publishes
a GitHub release. If that tag or release already exists, they are removed
and the tag is recreated at HEAD, then pushed to origin.
After the release is published, builds and deploys the Docusaurus site.`);
}

for (const arg of process.argv.slice(2)) {
  switch (arg) {
    case "--verify-clean=false":
      verifyClean = false;
      break;
    case "--verify-clean=true":
      verifyClean = true;
      break;
    case "--dry-run":
      dryRun = true;
      break;
    case "-h":
    case "--help":
      printHelp();
      process.exit(0);
      break;
    default:
      console.error(`Unknown argument: ${arg}`);
      process.exit(1);
  }
}

function fail(message) {
  console.error(`Error: ${message}`);
  process.exit(1);
}

/**
 * Run a command with an argv array (no shell). `git` / `gh` are native
 * executables on Windows; using a shell would split `-m "Release v1.5.0"`
 * on spaces and make `git tag` fail with "fatal: too many arguments".
 * @returns {{ status: number, stdout: string, stderr: string }}
 */
function run(command, args, options = {}) {
  const { inherit = false, allowFail = false, cwd = root } = options;
  const result = spawnSync(command, args, {
    cwd,
    encoding: "utf8",
    env: process.env,
    shell: false,
    stdio: inherit ? "inherit" : ["ignore", "pipe", "pipe"],
  });

  if (result.error) {
    fail(`failed to start ${command}: ${result.error.message}`);
  }

  const status = result.status ?? 1;
  if (status !== 0 && !allowFail) {
    const detail = (result.stderr || result.stdout || "").trim();
    if (detail && !inherit) {
      console.error(detail);
    }
    process.exit(status);
  }

  return {
    status,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  };
}

function requireCmd(command) {
  const result = spawnSync(command, ["--version"], {
    cwd: root,
    env: process.env,
    shell: false,
    stdio: "ignore",
  });
  if (result.error || (result.status ?? 1) !== 0) {
    fail(`Missing required command: ${command}`);
  }
}

function workingTreeDirty() {
  const status = run("git", ["status", "--porcelain"]);
  return status.stdout.trim().length > 0;
}

requireCmd("gh");
requireCmd("git");
requireCmd("pnpm");

{
  const inside = run("git", ["rev-parse", "--is-inside-work-tree"], { allowFail: true });
  if (inside.status !== 0 || inside.stdout.trim() !== "true") {
    fail("Not inside a git repository.");
  }
}
{
  const auth = run("gh", ["auth", "status"], { allowFail: true });
  if (auth.status !== 0) {
    fail("GitHub CLI is not authenticated. Run: gh auth login");
  }
}

const packageJsonPath = path.join(root, "package.json");
if (!fs.existsSync(packageJsonPath)) {
  fail("package.json not found in repository root.");
}

let version;
try {
  version = JSON.parse(fs.readFileSync(packageJsonPath, "utf8")).version;
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  fail(`Could not read package.json version: ${message}`);
}
if (!version || typeof version !== "string") {
  fail("Could not read package.json version.");
}

const tag = `v${version}`;
const sourceNotesFile = `documentation/docs/release-notes/${version}.md`;
const sourceNotesPath = path.join(root, "documentation", "docs", "release-notes", `${version}.md`);
const notesFile = `RELEASE_NOTES_github_${version}.md`;
const notesPath = path.join(root, notesFile);
const readmeScript = path.join(root, "scripts", "generate-readme-from-intro.sh");

if (!fs.existsSync(sourceNotesPath)) {
  fail(`Release notes file not found: ${sourceNotesFile}`);
}
if (!fs.existsSync(readmeScript)) {
  fail("scripts/generate-readme-from-intro.sh not found.");
}

if (verifyClean && workingTreeDirty()) {
  fail("Working tree is not clean. Commit/stash changes or run with --verify-clean=false");
}

{
  const remote = run("git", ["remote", "get-url", "origin"], { allowFail: true });
  if (remote.status !== 0) {
    fail("Remote 'origin' not configured.");
  }
}

const headCommit = run("git", ["rev-parse", "HEAD"]).stdout.trim();
const branch = run("git", ["rev-parse", "--abbrev-ref", "HEAD"]).stdout.trim();

function generateGithubNotes() {
  if (dryRun) {
    console.log(`[dry-run] Would generate ${notesFile} from ${sourceNotesFile}`);
    console.log("[dry-run] Would run: bash scripts/generate-readme-from-intro.sh");
    return;
  }

  console.log(`Generating GitHub release notes from ${sourceNotesFile}...`);
  run("bash", [readmeScript], { inherit: true });

  if (!fs.existsSync(notesPath)) {
    fail(`Release notes file was not generated: ${notesFile}`);
  }

  if (verifyClean && workingTreeDirty()) {
    fail(
      "Generating README/release notes changed tracked files. Commit those updates, then run the release again.",
    );
  }
}

generateGithubNotes();

function remoteTagExists() {
  const result = run("git", ["ls-remote", "origin", `refs/tags/${tag}`], { allowFail: true });
  return result.status === 0 && result.stdout.trim().length > 0;
}

function localTagExists() {
  const result = run("git", ["rev-parse", "-q", "--verify", `refs/tags/${tag}`], {
    allowFail: true,
  });
  return result.status === 0;
}

function releaseExists() {
  const result = run("gh", ["release", "view", tag], { allowFail: true });
  return result.status === 0;
}

function recreateTagAtHead() {
  if (dryRun) {
    console.log(`[dry-run] Branch: ${branch}`);
    console.log(`[dry-run] HEAD commit: ${headCommit}`);
    if (releaseExists()) {
      console.log(`[dry-run] Would delete GitHub release: ${tag}`);
    }
    if (remoteTagExists()) {
      console.log(`[dry-run] Would delete remote tag: origin ${tag}`);
    }
    if (localTagExists()) {
      console.log(`[dry-run] Would delete local tag: ${tag}`);
    }
    console.log(`[dry-run] Would create annotated tag ${tag} at HEAD and push to origin.`);
    return;
  }

  if (releaseExists()) {
    console.log(`Deleting existing GitHub release ${tag} (and its tag on the remote)...`);
    run("gh", ["release", "delete", tag, "--yes", "--cleanup-tag"], { inherit: true });
  } else if (remoteTagExists()) {
    console.log(`Deleting remote tag ${tag}...`);
    run("git", ["push", "origin", `:refs/tags/${tag}`], { inherit: true });
  }

  if (localTagExists()) {
    console.log(`Deleting local tag ${tag}...`);
    run("git", ["tag", "-d", tag], { inherit: true });
  }

  console.log(`Creating annotated tag ${tag} at HEAD (${headCommit})...`);
  run("git", ["tag", "-a", tag, "-m", `Release ${tag}`, "HEAD"], { inherit: true });

  console.log(`Pushing tag ${tag} to origin...`);
  run("git", ["push", "origin", `refs/tags/${tag}`], { inherit: true });
}

recreateTagAtHead();

const createArgs = ["release", "create", tag, "--title", tag, "--notes-file", notesFile];

console.log("Release inputs:");
console.log(`  Branch:     ${branch}`);
console.log(`  Tag:        ${tag}`);
console.log(`  Title:      ${tag}`);
console.log(`  Source:     ${sourceNotesFile}`);
console.log(`  Notes file: ${notesFile}`);

const docsDir = path.join(root, "documentation");

function deployDocumentation() {
  if (dryRun) {
    console.log("[dry-run] Would deploy Docusaurus docs: pnpm run deploy (documentation/)");
    return;
  }

  console.log("Deploying Docusaurus documentation to GitHub Pages...");
  run("pnpm", ["run", "deploy"], { inherit: true, cwd: docsDir });
  console.log("Documentation deployed: https://wsj-br.github.io/duplistatus/");
}

if (dryRun) {
  console.log("[dry-run] Would run:");
  console.log(`  gh ${createArgs.map((a) => (/\s/.test(a) ? JSON.stringify(a) : a)).join(" ")}`);
  deployDocumentation();
  process.exit(0);
}

run("gh", createArgs, { inherit: true });
console.log(`Release created successfully: ${tag}`);
deployDocumentation();
console.log("");
console.log("See the progress at the github repository https://github.com/wsj-br/duplistatus/actions");
console.log("");
